### ISSUE TITLE
improve seo

### ISSUE THREAD

**Issue by SimonSiefke** [vuejs/docs#1098]
I find that search results on google look a bit weird

![google](https://user-images.githubusercontent.com/23744935/122648405-7911b500-d129-11eb-9acf-5a8aed90e4fe.png)

Issue 1: line numbers show up in google results (`3 4 5 6 7 8 9 10 11 12`)

Issue 2: It shows ad in google search results (`Watch a free video about the Composition API on Vue Mastery`)

<br>

Ideas: 

Maybe we could use [data-nosippet html attribute](https://developers.google.com/search/docs/advanced/robots/robots_meta_tag#data-nosnippet-attr)  so that those parts won't get indexed by search engine, for example

```html
<span data-nosnippet>Watch a free video about the Composition API on Vue Mastery</span>
```

**Comment by NataliaTepluhina** [comment]
Should be improved with making v3 docs default :)
