### ISSUE TITLE
Line numbers are overflowing in chrome browser. BUG

### ISSUE THREAD

**Issue by immacodder** [vuejs/docs#1099]
![image](https://user-images.githubusercontent.com/60310704/122769031-dda94d00-d2ac-11eb-99e5-1fb7a74f1efa.png)
IDK why this happens, the only log that I get in incognito mode is that the service worker is active, that is it.
It works just fine with firefox tho, I think the problem is in default chrome stylesheets.
But that thing is extremely annoying, because I have to select text and drag it in order to read it.

**Comment by skirtles-code** [comment]
Are you on Linux? I suspect it's this: https://github.com/vuejs/vuepress/issues/2691

**Comment by immacodder** [comment]
Yes, I currently use Debian based distribution

**Comment by immacodder** [comment]
And thanks for a link, I guess I will just zoom to 110% to fix the issue.
