### ISSUE TITLE
The child component uses the parent component's functions

### ISSUE THREAD

**Issue by keke599** [vuejs/docs#1131]
Direct use via UseContext will warn

Extraneous non-emits event listeners (myclick) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option.
It can only be distributed？

**Comment by skirtles-code** [comment]
I'm not entirely sure what you're asking.

This issues list is for reporting problems with the documentation. If you need help with your code then I recommend asking on [Discord](https://chat.vuejs.org/). Someone on there should be able to help you.
