### ISSUE TITLE
Unexpected behavior with non ascii character in v-for

### ISSUE THREAD

**Issue by pablotcarreira** [vuejs/docs#1132]
This code works as expected:

`<q-item clickable v-for="umaregiao in data ? data.regioesDeInteresse : []" :key="umaregiao.id" @click="selecionarRegião(umaregiao)">`

But if I add a non ascii character to v-for variables, the variable inside @click is aways pointing to the first item on the list. Example:

`<q-item clickable v-for="umaregião in data ? data.regioesDeInteresse : []" :key="umaregião.id" @click="selecionarRegião(umaregião)">`

**Comment by skirtles-code** [comment]
Thanks for the report.

This issues list is for reporting problems with the Vue 3 documentation. If you think there's a bug in Vue 3 then you'll need to file it at https://github.com/vuejs/vue-next/issues.

I gave this a quick try with Vue 3.1.4 and everything seemed to be working correctly for me.
