### ISSUE TITLE
Mixup between Composition API and Legacy API is confusing

### ISSUE THREAD

**Issue by gagarine** [vuejs/docs#1139]
It's very confusing if you don't know vuejs at first. You follow the doc and learn all about the "legacy API" and only at the end you learn about the composition API. It would be much better to first learn about the composition API which is also simpler to use. At least in the introduction the two API style should be mentioned so the user can choose accordingly.

I think the doc should focus on the Composition API and move the legacy one in a sub-section. Example such as https://v3.vuejs.org/guide/instance.html#lifecycle-hooks should be in Composition API in my opinion.

**Comment by skirtles-code** [comment]
The addition of the composition API does pose a documentation challenge.

What you're calling the 'legacy API' is more commonly referred to as the 'options API'. Describing it as 'legacy' implies it is deprecated or discouraged, which it isn't. It is alive and well and many users prefer it to the composition API, at least for relatively simple components.

Depending on your background, you may find the composition API easier to use but that isn't a universal experience. Some people find the more functional style very alien. There's a mental leap required for those who haven't encountered that style of programming previously.

The documentation faces similar problems with other choices. e.g. SFC vs non-SFC and global CDN build vs ES modules. There is no easy way to please everybody but we're constantly trying to find ways to make it easier for people to get started. The upcoming introduction of `<script setup>` in 3.2 is likely to motivate a further rethink.

**Comment by NataliaTepluhina** [comment]
Thank you for bringing your perspective here! 

I agree a lot with @skirtles-code points and just want to add that we _intentionally_ left Options API as a default learning path and left Composition API to be an advanced feature. We may rethink this strategy if we see that community is widely adopting one API over another. For now, I am closing the issue.
