### ISSUE TITLE
[Bug] Broken SFC State-driven CSS Variables link

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/docs#1140]
https://v3.vuejs.org/guide/migration/introduction.html#notable-new-features

**Comment by MSib** [comment]
branch "style vars 2" is not present, but there is "style vars"
https://github.com/vuejs/rfcs/blob/style-vars/active-rfcs/0000-sfc-style-variables.md

**Comment by LiuQixuan** [comment]
How to avoid using bind(var) in <style> to render css file, attach  hash values for every css var? Several css files must be loaded for the same component.
