### ISSUE TITLE
[v-if with template] :key attribute on template node?

### ISSUE THREAD

**Issue by malles** [vuejs/docs#1142]
The example at https://v3.vuejs.org/guide/list.html#v-for-on-a-template shows a `:key` attribute on a template tag. Is this possible/useful in Vue3?

```html
<ul>
  <template v-for="item in items" :key="item.msg">
    <li>{{ item.msg }}</li>
    <li class="divider" role="presentation"></li>
  </template>
</ul>
```

**Comment by skirtles-code** [comment]
Yes, in Vue 3 a `<template>` tag can have a `key` when used with a `v-for`. See https://v3.vuejs.org/guide/migration/key-attribute.html#with-template-v-for.

Vue 3 supports fragments and `v-for` is implemented using them. In the example you mentioned, each iteration will create a fragment VNode that has a pair of `<li>` VNodes as children. It is the fragment VNode that receives the `key`.
