### ISSUE TITLE
Caveats in props validator example?

### ISSUE THREAD

**Issue by acadama123** [vuejs/docs#1144]
The examples in [https://v3.vuejs.org/guide/component-props.html#prop-validation](https://v3.vuejs.org/guide/component-props.html#prop-validation) shows that the syntax to add a validator to a prop is:
```
propF: {
  validator(value) {
    // The value must match one of these strings
    return ['success', 'warning', 'danger'].includes(value)
  }
},
```
However, when I used this syntax in my app (which uses Vue3 and TypeScript) like so:
```
type: {
  type: String,
  validator(value: string) {
    return ["Basemap", "Raster"].includes(value);
  },
  required: true,
},
```
it made the prop unable to be called within the component. What I mean is that calling `this.type` or `this.$props.type` would result in the error `Property 'type' does not exist on type 'CreateComponentPublicInstance<ReadOnly>...`. In fact, no prop could be called at all. However, the props can still receive value from the parent component, and the values are indeed stored, as I can see them when running `console.log(this.$props)`, albeit being stored within a `Proxy`.

Eventually, I was able to fix this problem by modifying the code to:
```
type: {
  type: String,
  validator: (value: string) => {
    return ["Basemap", "Raster"].includes(value);
  },
  required: true,
},
```
This syntax makes sense to me, since the entire thing is an object so validator should follow the key-value syntax as well, instead of what was shown in the docs example.

I'm new to Vue and TypeScript, so I'm hesitant to say that the docs are wrong—I'm likely missing something in my readings. But the examples do give off the impression that the `validator() {}` syntax was the right way of doing it, but it wasn't in my case. Perhaps someone can shed a light on this for me regarding this problem? Thank you very much!

Edit: I originally also have this problem with props defaults. However, I realized that I can just pass a default value for props of basic types. Therefore, I changed this issue to only focus on props validator.

**Comment by skirtles-code** [comment]
The example code is correct from a JavaScript perspective. `validator(value) {` is a short-hand for `validator: function(value) {`. As the function doesn't use `this` it shouldn't matter whether it uses an arrow function or a regular function.

I believe what you're hitting is a quirk of TypeScript that forces `validator` and `default` to use arrow functions. It is documented on the TypeScript page here: https://v3.vuejs.org/guide/typescript-support.html#annotating-props.
