### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by olivier65** [vuejs/docs#1147]
On https://v3.vuejs.org/guide/single-file-component.html#building-with-rollup the rollup.config.js should replace  `import commonjs from 'rollup-plugin-commonjs'` with `import commonjs from '@rollup/plugin-commonjs'`.

**Comment by NataliaTepluhina** [comment]
Thank you for reporting it! Fixed via https://github.com/vuejs/docs/commit/ffd8d032eb1bcea4d2e25707ebcc258b47bfac84
