### ISSUE TITLE
How to use javascript native function in inline style?

### ISSUE THREAD

**Issue by sliontc** [vuejs/docs#1150]
I want to arrange the div dynamically with left and top, using following:
`<div :style="{ left: Math.round(x)+'px', top: Math.round(y) + 'px' }"></div>`

But it failed.
So any help is welcome.

**Comment by skirtles-code** [comment]
I suggest asking on the [Vue Discord server](https://chat.vuejs.org/), somebody there should be able to advise. This issues list is just for reporting problems with the Vue 3 documentation.
