### ISSUE TITLE
Minimum Browser versions supported by Vue library

### ISSUE THREAD

**Issue by jesusarockias** [vuejs/docs#1151]
I have searched the documentation but we are not able to find the minimum version of browsers (Chrome, Firefox, etc..) supported by Vue library.

Can anyone please let me know about this browser compatibility details of Vue 2 & 3library.

**Comment by jesusarockias** [comment]
Can anyone help me about this query?

**Comment by cbirdsong** [comment]
The Vue 2 docs [have a support note in the installation section](https://vuejs.org/v2/guide/installation.html#Compatibility-Note), but the Vue 3 installation docs appear to be missing this info.

**Comment by skirtles-code** [comment]
This is some work-in-progress on new documentation in the `next` branch. The new FAQ should include a note about compatibility. The current draft can be seen at https://github.com/vuejs/docs/blob/next/src/about/faq.md.

**Comment by NataliaTepluhina** [comment]
Added in new docs: https://vuejs.org/about/faq.html#what-browsers-does-vue-support
