### ISSUE TITLE
v-for with :key is a requirement apparently not stated in docs

### ISSUE THREAD

**Issue by via-lars** [vuejs/docs#1161]
**Context**:

- Vue3
- Vue cli
- "default project"
- (eslint vue3-essential)
- vue ui task serve

**Issue**:

any `v-for` without `:key` produces a compilation error "error Elements in iteration expect to have 'v-bind:key' directives" even for simple arrays such as `["string1", "string2"]`.

Note: these arrays themself are each a value of an Object property in my data.

**Doc ref**:

https://v3.vuejs.org/guide/list.html#maintaining-state

**Comment by skirtles-code** [comment]
Thanks for the report.

Vue itself does not require the use of a `key` with `v-for`.

I believe the error you're seeing is coming from the Vue ESLint rules: https://eslint.vuejs.org/rules/require-v-for-key.html. These enforce best practices, usually based on the official style guide. The relevant style guide entry in this case is at: https://v3.vuejs.org/style-guide/#keyed-v-for-essential.

The complexity of the array being iterated is not a factor.

I've opened #1164 to link from the section you mentioned to the style guide. I'm not sure what more we can do. Explicitly mentioning the ESLint rules would be outside the scope of the main Vue guide.

**Comment by via-lars** [comment]
Thank you!

Explicitly mentioning ESLint rules is outside the scope I concur.

Close this issue at your leisure.

**Comment by NataliaTepluhina** [comment]
We merged a MR to link to the styleguide so I believe we can safely close the issue now 🙏🏻
