### ISSUE TITLE
v-bind Object still requires the component to export the Objects properties as props - can be clarified in docs

### ISSUE THREAD

**Issue by via-lars** [vuejs/docs#1162]
**Doc ref**:

https://v3.vuejs.org/guide/component-props.html#passing-the-properties-of-an-object

**Issue**:

using the Object bind syntax to pass a complete object by `<blog-post v-bind="post"></blog-post>` with `post` being an Object and `blog-post` being a component, the component still needs to export the props being the Object properties and not just `props: {post: Object}`, eg. `post` being `{id: Number, title: String}` `blog-post` props need to be `props: {id: Number, title: String}`.

This can be stated explicitly in the docs.

**Comment by skirtles-code** [comment]
I'm not sure what change we can make to help clarify this.

Passing an object is covered here, in the section `Passing an Object`:

https://v3.vuejs.org/guide/component-props.html#passing-an-object

In that case, the child component would have a single prop with a `type` of `Object`. Using the `post` prop as an example, that would be `props: { post: Object }`, just like you suggest. From the parent that would be passed as `:post="post"`.

The section you mentioned is about passing the *properties* of an object, not the object itself. It is somewhat analogous to a spread operation. The individual properties of the object are passed, with their property names being used as the prop names.

**Comment by via-lars** [comment]
`props: { myObject: Object }` resulted in a warning in the browser console for me and my template didn't render.

Using `<my-component v-bind="myObject"></my-component>`.

I intended to bind the object from the `data` `myObject` and not as a string.

But I see `myObject` is an attribute value, it "couldn't have" worked as a prop definition.

For the docs, the whole section https://v3.vuejs.org/guide/component-props.html#passing-static-or-dynamic-props could be supplemented with the associated prop definition for each case (currently shows only the passing of the values).

Without trying the following myself now, given a JS object, would `<my-component v-bind:myprop="JSON.stringify(myObject)"></my-component>` work with `props: { myprop: Object }` ? If so, perhaps this too could be added to the documentation for those who have  JS object (perhaps fetched from a server) and not an in-code object as in https://v3.vuejs.org/guide/component-props.html#passing-an-object.
I think I now understand the second example given in that link is an example of passing a JS object directly. I didn't understand the HTML comment above (and still don't) ("`Dynamically assign to the value of a variable.`"). Perhaps better write "Assign a variable directly" and for the above Object case: "Assign an object variable (or object data like the value of another object's property) directly as a prop value" + give the associated prop definition like proposed above.

**Comment by skirtles-code** [comment]
Using the `v-bind` prefix, or the `:` shorthand, makes Vue interpret the template attribute value as a JS expression. That expression is evaluated and the result is used as the actual attribute value. While DOM elements do typically require strings for their attribute values, the props for components can be objects or any other type you need. You shouldn't need to use `JSON.stringify` to convert an object to a string, you can pass the object itself.

It is perfectly valid to use `props: { myObject: Object }` to define a prop that has an object value. However, you need to ensure that you pass an object from the parent template. Using `<my-component v-bind="myObject">` won't do that. Note that the `myObject` in the attribute value here is a property of the parent component, it is not the name of the prop in the child. To pass an object you would need to use `<my-component :my-object="myObject">`, where `my-object` is the prop name. So long as you aren't in an in-DOM template you could also use camelCase, i.e. `<my-component :myObject="myObject">`. `myObject` is serving multiple purposes in this example, which makes it difficult to explain, so I'm going to rewrite the example below with different names:

```js
const ChildComponent = {
  props: { user: Object },
  template: `<div>{{ user.name }}</div>`
}

const ParentComponent = {
  components: { ChildComponent },
  template: `<ChildComponent :user="administrator" />`,

  data () {
    return {
      administrator: { name: 'admin', id: 123 }
    }
  }
}
```

Here is a running example of that same code: https://jsfiddle.net/skirtle/2zn9peco/

So when we write `:user="administrator"`, the `user` part corresponds to the name of the prop in the child component. The use of a `:` prefix leads to the value being interpreted as an expression. The expression here is just `administrator`, which will evaluate to the object in the `administrator` property of the component instance. That property is defined by the `data` function.

The expression bound to the prop doesn't need to be a simple property name. It can be just about anything supported by JS expressions. So, for example, the documentation section you referenced shows how you can use an inline object literal as the expression. The same section in the documentation also uses `post.author`. This will be accessing the `post` property of the current component instance and then accessing its `author` property. You could think of it as the expression `this.post.author`, if that helps to understand it (though you should never include the `this.` in a template).

**Comment by via-lars** [comment]
Thank you very much for your passion and detailed explanation !

i think i understand.

let this issue be for your consideration to extend that doc part and close it at your leisure.
