### ISSUE TITLE
Typo on  vue docs with customElements.register

### ISSUE THREAD

**Issue by aelbore** [vuejs/docs#1165]
Does `customElements.register` is a typo?

![image](https://user-images.githubusercontent.com/18069807/128957465-ec624e65-03f9-4d8d-a16e-09d71c443563.png)

**Comment by skirtles-code** [comment]
For reference, the picture shows this section of the docs: https://v3.vuejs.org/guide/web-components.html#tips-for-a-vue-custom-elements-library

I'm not really familiar with the `customElements` API myself but it does seem that the method is called `define` and not `register`, https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define.
