### ISSUE TITLE
question about one section in style guide.

### ISSUE THREAD

**Issue by wxsms** [vuejs/docs#1169]
In the [Order of words in component names](https://v3.vuejs.org/style-guide/#order-of-words-in-component-names-strongly-recommended) section, there's one explaination about why we should keep our components 'plain' in one directory:

> Refactoring becomes more difficult, because find-and-replace often isn't sufficient to update relative references to a moved component.

As a Jetbrains(IDEA/Webstorm, etc.) user, I don't know that what's the situation in VSCode or other IDEs, but such refactor is never a difficult job in ws. All I need to do is move the files with some drag and clicks, and ws will fix almost all the relative references automatically. 

Therefore, I don't think that this is a suitable reason for the opinion, at least for ws users likely?

**Comment by NataliaTepluhina** [comment]
@wxsms thank you for your opinion! However, there are many other IDEs besides WebStorm and for some of them refactoring might be not that easy like in WS. I'd prefer to keep the current explanation in the styleguide.

**Comment by wxsms** [comment]
@NataliaTepluhina it's totally find. just a small question, thanks for your reply.
