### ISSUE TITLE
Small syntax issue in installation with vite

### ISSUE THREAD

**Issue by techandsoftware** [vuejs/docs#1193]
https://v3.vuejs.org/guide/installation.html#vite

The npm example has:
```
$ npm init vite <project-name> -- --template vue
```

There's an extra -- which stops the command from working properly.

**Comment by sodatea** [comment]
npm 7 requires the extra `--`. Though npm 6 doesn't.

**Comment by techandsoftware** [comment]
Alright, I'll upgrade :)
