### ISSUE TITLE
Video modal on website breaks on wide aspect ratios

### ISSUE THREAD

**Issue by loudar** [vuejs/docs#1212]
When just normally opening the site on my 21:9 screen, I get this:

![Screenshot 2021-08-26 at 12-37-09 Vue js](https://user-images.githubusercontent.com/35202909/131108346-85f8b9d4-97cb-4b80-9d4c-017f328b2766.png)
The modal extends beyond the visible range.

The 'width' property for the '.modal' css class is '75%'. A possible solution would be to use vmin to adapt for all aspect ratios, e.g. '100vmin'.

**Comment by NataliaTepluhina** [comment]
Closing the issue as we have switched to new docs so this shouldn't be an issue anymore
