### ISSUE TITLE
firefox mobile view breaking

### ISSUE THREAD

**Issue by sadn1ck** [vuejs/docs#1217]
## Viewport meta tag missing causing firefox mobile display issues

Issue was posted on 2.x docs https://github.com/vuejs/vuejs.org/issues/2855 about the 3.x docs, just mirroring it here. 
Can confirm said behaviour, probably due to missing viewport tag in the head.

## Fix
 Just need to add
```js
['meta', { name: 'viewport', content: 'width=device-width, initial-scale=1.0' }],
```
to the vuepress config under head (tried locally).

Let me know if can make a PR, thanks.

**Comment by NataliaTepluhina** [comment]
@sadn1ck thank you for reporting this! PRs are very welcome, would you mind creating one? 🙏🏻

**Comment by sadn1ck** [comment]
Done @NataliaTepluhina, you can have a look. Thanks!
