### ISSUE TITLE
[Style Guide] What about the name of child components that are tightly coupled with their single-instance parent ?

### ISSUE THREAD

**Issue by kevhof** [vuejs/docs#1221]
When following these two rules:

1. [Single-instance component names](https://v3.vuejs.org/style-guide/#single-instance-component-names-strongly-recommended)
2. [Tightly coupled component names](https://v3.vuejs.org/style-guide/#tightly-coupled-component-names-strongly-recommended)

Should the child component name also include the prefix `The` ?

For example when the parent is `TheSidebar`, the child should be `TheSidebarElement` or `SidebarElement` ?

**Comment by NataliaTepluhina** [comment]
I would recommend using some common prefix that is relevant to your application (for example, GitLab's component library uses `Gl` or BootstrapVue using `B`: `GlDropdown` or `BDropdown`.

**Comment by kevhof** [comment]
Sorry @NataliaTepluhina, but you are not really answering the question. I think you are talking about [Base component names](https://v3.vuejs.org/style-guide/#base-component-names-strongly-recommended) which I am not.

I want to know how to name a component [that is tightly coupled to its parent](https://v3.vuejs.org/style-guide/#tightly-coupled-component-names-strongly-recommended) [single-instance element](https://v3.vuejs.org/style-guide/#single-instance-component-names-strongly-recommended). For example, the parent is named ```TheSidebar```. The child should be named ```TheSidebarButton``` or ```SidebarButton``` ? Do we have to repeat the prefix ```The``` to all children or only to the parent ?
