### ISSUE TITLE
How can we lazy-load components with new SFC script setup method?

### ISSUE THREAD

**Issue by martonx** [vuejs/docs#1222]
Previously we were able to do this for lazy loading components:

```
<template>
  <div>
    <button @click="isModalVisible = true">Open modal</button>
    <modal-window v-if="isModalVisible" />
  </div>
</template>

<script>
export default {
  data () {
    return {
      isModalVisible: false
    }
  },
  components: {
    ModalWindow: () => import('./ModalWindow.vue')
  }
}
</script>
```

Now how can we do the same with script setup syntax?
I found only this one example in the documentation: https://v3.vuejs.org/api/sfc-script-setup.html#using-components
I tried:
```
<template>
  <div>
    <button @click="isModalVisible = true">Open modal</button>
    <ModalWindow  v-if="isModalVisible" />
  </div>
</template>

<script setup>
import { reactive } from 'vue';

const isModalVisible = reactive(false);
const ModalWindow = () => import('./ModalWindow.vue');
</script>
```

In this case I got "[Vue warn]: Invalid VNode type: undefined (undefined)"
I see in Network tab, the component is loaded, but nothing visible happens except this warning message.

Please advice!

**Comment by skirtles-code** [comment]
I've now had chance to try this myself and it does appear to work as I suggested.

I think the existing documentation is sufficient. Using `defineAsyncComponent` is the correct way to create async components, whether or not you're using `<script setup>`.
