### ISSUE TITLE
Add vue.js changelog link to navbar.

### ISSUE THREAD

**Issue by wxsms** [vuejs/docs#1224]
https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md

This should be useful. I can help with this if sounds good.

**Comment by skirtles-code** [comment]
We're currently in the process of migrating the docs to VitePress (on the `next` branch). I think there'll be some changes to the navigation as part of this, so it might be better to wait until after the migration is finished.

**Comment by skirtles-code** [comment]
The new docs have a link to the changelog at the top of About / Releases.
