### ISSUE TITLE
global component registering fails on reload

### ISSUE THREAD

**Issue by signmeuptwice** [vuejs/docs#1235]
Version

3.2.6

Reproduction link

[codesandbox.io](https://codesandbox.io/s/agitated-feather-1ttzg?file=/src/App.vue)

What is expected?

Component uses OpenLayersMap correctly

What is actually happening?

OpenLayersMap not found inside the created component on reload

in the sandbox you see the map disappear on reload; if you console log the component you will see that on reload `components` is empty inside `_context` so `use()` is not populating correctly

My application is not a full vue application; my menu loads vue instances in the website dynamically

for example I click on Events and this will trigger the following code:

         import OpenLayersMap from 'vue3-openlayers'
        createApp(eventMainComponent,{resumeData:resumeData}).use(OpenLayersMap).mount("#Vue-events")

works like a charm the first time but then I switch to another page lets say blog

then if I reload Events that will execute the same code above I get

        [Vue warn]: injection "ol-format" not found. 

which refers to `const format = inject('ol-format');`

I might say that my page is not a full page reload; this is a new vue instance 
the old instance is discarded by resetting html

**Comment by NataliaTepluhina** [comment]
Hi @signmeuptwice 

This issues list is for reporting problems with the Vue 3 documentation. The problem you're having doesn't appear to be related to the docs.

If you have any further questions I suggest asking on [Vue Discord](https://chat.vuejs.org/).

Thanks.
