### ISSUE TITLE
The theme repository is not public

### ISSUE THREAD

**Issue by DannyFeliz** [vuejs/docs#1243]
I was trying to see the https://github.com/vuejs/docs/tree/next branch of the docs but in the instructions, it's mentioning to clone the `vuejs/theme` repo but it looks like is not public. Is this something expected?

![image](https://user-images.githubusercontent.com/5460365/133517824-b41144d4-3c0f-4b49-90d8-c2768cc4733f.png)

![image](https://user-images.githubusercontent.com/5460365/133517815-64839242-2f22-4679-9393-7f6e548878c0.png)

**Comment by ydcjeff** [comment]
Yes, the theme repo is not public. But you can install the theme:

```sh
yarn add @vue/theme
```
