### ISSUE TITLE
Transition & Animations with Composition API and el example

### ISSUE THREAD

**Issue by weihungchin** [vuejs/docs#1244]
Please provide at least one working example of using the Composition API to access the `el` when working with transition.

**Comment by skirtles-code** [comment]
I'm not exactly sure what you're requesting here. Accessing the `el` under what circumstances? Is there an example using the Options API that you'd like to see converted to the Composition API?

**Comment by NataliaTepluhina** [comment]
Closing as now Transitions section has an both Options and Composition API
