### ISSUE TITLE
examples refactor with composition api

### ISSUE THREAD

**Issue by zhangenming** [vuejs/docs#1248]
i want to refactor  examples  the  https://v3.vuejs.org/examples/markdown.html
but i find this file is empty https://github.com/vuejs/docs/blob/master/src/examples/markdown.md
so, where is the real code...

**Comment by sqal** [comment]
Looks like you don't have to - https://github.com/vuejs/docs/tree/next/src/examples/src

**Comment by skirtles-code** [comment]
Thanks for the offer, but @sqal is correct, the examples are all currently being revised on the `next` branch.

Unless there's a bug in the current examples we can wait for the `next` branch to go live.
