### ISSUE TITLE
clearInterval invalid

### ISSUE THREAD

**Issue by funtionalcode** [vuejs/docs#1249]
Reproduction link
https://codesandbox.io/s/zealous-ramanujan-vf8ry?file=/src/App.vue

Steps to reproduce
Run the above demo

Multiple trigger mousemove and mouseout clearInterval invalid，cause Timer repeat

What is expected?
once Interval

What is actually happening?
many Interval or clearInterval invalid

**Comment by skirtles-code** [comment]
This issues list is for reporting problems with the Vue 3 documentation.

If you need help debugging your code, I suggest asking on [Vue Land Discord](https://chat.vuejs.org/). Thanks!
