### ISSUE TITLE
How to use Namespaced Components?

### ISSUE THREAD

**Issue by gkandemi** [vuejs/docs#1267]
Hi everyone,

is there any body to know how to use namespaced component in Vue3? This is feature announced in Script Setup docs.

https://v3.vuejs.org/api/sfc-script-setup.html#namespaced-components

But I couldn't find any explanation anywhere.

Thanks
Best regards

**Comment by skirtles-code** [comment]
Could you elaborate on what more you need? As far as I can tell everything is already explained in the section you linked.

**Comment by gkandemi** [comment]
Thanks for your response. Well I didn't understand that 
"

> This is useful when you import multiple components from a single file

"

I tried a couple ways to do that but I couldn't. How should I create single file to export multiple components.

Thanks

**Comment by gkandemi** [comment]
> Could you elaborate on what more you need? As far as I can tell everything is already explained in the section you linked.

Thanks for your response. Well I didn't understand that 

> This is useful when you import multiple components from a single file

I tried a couple ways to do that but I couldn't. How should I create single file to export multiple components.

Thanks

**Comment by skirtles-code** [comment]
An example:

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCAqIGFzIEZvcm0gZnJvbSAnLi9mb3JtLWNvbXBvbmVudHMuanMnXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8Rm9ybS5JbnB1dD5cbiAgICA8Rm9ybS5MYWJlbD5sYWJlbDwvRm9ybS5MYWJlbD5cbiAgPC9Gb3JtLklucHV0PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiZm9ybS1jb21wb25lbnRzLmpzIjoiZXhwb3J0IHsgZGVmYXVsdCBhcyBJbnB1dCB9IGZyb20gJy4vSW5wdXQudnVlJ1xuZXhwb3J0IHsgZGVmYXVsdCBhcyBMYWJlbCB9IGZyb20gJy4vTGFiZWwudnVlJyIsIklucHV0LnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPHNsb3QvPlxuICA8aW5wdXQ+XG48L3RlbXBsYXRlPiIsIkxhYmVsLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGxhYmVsPjxzbG90Lz48L2xhYmVsPlxuPC90ZW1wbGF0ZT4ifQ==

When it says 'import multiple components from a single file' it isn't referring to SFCs, it's referring to the entry point for a library.

I think we could tweak the wording to replace the word 'single' and to give the import a `.js` extension.

**Comment by gkandemi** [comment]
Thats perfect! Thanks.

**Comment by LeulAria** [comment]
nice

**Comment by dbzx10299** [comment]
This is also an example [how to use namespaced components](https://play.vuejs.org/#eNp9UsFKxDAQ/ZUhl+7C0h70tFRBl0X04Ip6DEhtp92sbRKSdC0s/XcnKd1Wkb1l5r03eZmXE7vTOj62yNYstbkR2oFF1+pbLkWjlXFwAoMl9FAa1UBE1GiCHowoRiROfOVnEYHLNBnG0SAqHDa6zhxSBZB6IiTTOd5gXfs6TWZEtmLO5kqWoooPVkmyePISznLVaFGj2WknlLScrSEgHsvqWn0/hZ4zLa7Gfr7H/Ouf/sF2vsfZi0GL5oicnTGXmQrdAG/fnrGj8xlsVNHWxL4AvqJVdes9DrT7VhZke8YLbh/DNoWs3u22cyjt+Chv1DP7wOeMdru58PTJ7lV8HXRc9rTFMZcp43m6+z/Zclm2MvfTwQs/FsvhBkPfwkjYL6JCHKMVRKKBDCqiREu655fQ53lZlxPjrMMueKGsrQuXwg3sPg+YuzizVlRyEZyshoF+OAlJPPtjrP8Bm5vukQ==)

`App.vue`
```js
<script setup>
import { ref } from 'vue'
import {Grid} from './Grid.vue'

</script>

<template>
  <Grid />
  <Grid.Cell/>
</template>
```
`Grid.vue`
```js
<script>
import { h } from 'vue'

function Grid_() {
  return h('div', 'im a grid')
}

function Cell() {
  return h('div', 'im a cell')
}

export const Grid = Object.assign(Grid_, {
  Cell
})
</script>
```
