### ISSUE TITLE
"Non-Prop Attributes" page needs updating for SFC setup mode

### ISSUE THREAD

**Issue by berzi** [vuejs/docs#1279]
[Non-Prop Attributes](https://github.com/vuejs/docs/blob/master/src/guide/component-attrs.md) currently makes no mention of what changes need to be done if one is using `setup` mode.

Particularly:
 - [ ] What to replace `$attrs` with? Is there a separate function to import analogous to e.g. `defineProps`?
 - [ ] How to specify `inheritAttrs: false` to disable attribute inheritance?

**Comment by NataliaTepluhina** [comment]
Closing as we have the mentioned switcher in new docs
