### ISSUE TITLE
Vue 3 documentation for props is incomplete

### ISSUE THREAD

**Issue by julie777** [vuejs/docs#1287]
The documentation for props https://v3.vuejs.org/guide/component-props.html is incomplete. Although it shows uses of required and default in the example code, it never really documents all the possible fields in a prop definition object.

Some of the missing information:
- if the type is not specified what is the type
- if required is not specified, is the prop required
- if required is false, what is the value  of the prop when no value is passed to the component
- if default is specified when is the default value used
- can required and default be used together in the same prop definition
- how does validation interact with other fields
- what are the special considerations for object and array props

How to define props and how to pass props to a component are intermixed, making it harder to just find information about definition.

Needs to mention defining props with options api, composition api and script setup, including any differences.

In general the documentation is good about providing examples of correct usage, but often omits detailed information about the topic. Remember that Vue users are developers and need detailed information to avoid problems and make the best decisions.

**Comment by theHacker** [comment]
Addition to that:
`type` is allowed to be an array. (Vue internally even converts it to an array, if it's not - see `validateProp()`)

I would move to explicitly include this example into the section "Prop Validation":
```vue
// Multiple possible types
...
propB: {
    type: [String, Number]
}
...
```

**Comment by bencodezen** [comment]
Thanks for the feedback on this @julie777! We're in the midst of doing a massive redesign on the docs, and just know that once that is released, we'll double-check on this to make sure all key information is documented as expected.
