### ISSUE TITLE
It is getting complicated to find the correct information in the Vue docs because there are now many ways to use Vue

### ISSUE THREAD

**Issue by julie777** [vuejs/docs#1290]
As a relatively new user, I struggle finding the correct information, both in the Vue docs and with google searches. I can handle the Vue 2 vs 3, because at least the Vue docs are different. Of course Vue doc writers can't help with all the past information on StackOverflow, etc.

I would like to suggest changing the Vue 3 docs to 
- 1. make it easier for new users to find the correct information
- 2. group information for convenience of all users
- 3. promote the preferred way of using Vue
- 4. provide examples that work for the way I choose to use Vue

The variation are SFC vs non-SFC, Options API vs Composition API, vs Script Setup.

### SFC
For me, I started with SFCs from the beginning (I am using Quasar) and anytime I see an example in the docs using raw Vue code I find it takes me quite a bit of extra time to decipher it.

I know that the docs promote SFC use, so I would expect the docs to provide examples in SFC format where possible. I would go so far as to relegate all non-SFC documentation to an appendix.

### Which API
Considering the future, I believe that anyone using the composition api will soon migrate to the script setup version. Adding the use of unplugin-vue-components and unplugin-auto-imports to script setup makes Vue a joy to use. I can focus on the problem that I am trying to solve instead of writing a bunch of boilerplate code. Then when you add composables components become so much simpler it is amazing.

To support the future:
- I would suggest writing docs with script setup as the primary API.
- Provide a small comparison section showing how the Composition API is different from the script setup API.
- Provide a section in the docs just for the options API
- Provide appendices, such as the one that already exists for migrating from Vue 2 to Vue 3.
  - options to composition
  - composition to options
  - composition to script setup

I really enjoy Vue and I would like to help make it better and even easier to use.

**Comment by NataliaTepluhina** [comment]
Closing as new docs are default now and they cover most of the mentioned points
