### ISSUE TITLE
Put the Vue version number in the Doc page header.

### ISSUE THREAD

**Issue by julie777** [vuejs/docs#1292]
Currently if I am viewing vue3.vuejs.org pages it is not obvious that I am looking at the view 3 docs. The vuejs.org pages do have a banner to tell me I might be in the wrong place. 

My suggestion is to add the major version number to the titlebar so that it shows

Logo Vue.js 3  (or it could have the word version - version 3)

![image](https://user-images.githubusercontent.com/5090005/138502203-e06e211f-1e4f-47b3-91e9-ec8b9bcd501a.png)

**Comment by skirtles-code** [comment]
Thanks for the suggestion.

There's currently a major overhaul to the docs happening on the `next` branch, which will significantly change the page design. We're currently trying to avoid making any changes that might get lost in that transition.

I do very much agree with your point though. When I'm using other libraries I really value a clear indication of which version of the docs I'm looking at. It isn't always clear, especially coming from an external link.

**Comment by NataliaTepluhina** [comment]
Closing this issue as v3 docs are default now

**Comment by YSavir** [comment]
> Closing this issue as v3 docs are default now

Congrats on the new design and setting V3 as the default!

However, I feel the issue has been closed without addressing the problem. There's a comment and links to Vue2 guides in the guide intro, but I don't see any other such notifications and navigation on other pages. With search engines starting to point to the new pages, there's no indication that we're potentially reading docs for the wrong version, or where to go to find the version we need.

In the Vue2 Docs, there's the handy dropdown below on each guide page and API page that not only makes the current version clear, but provides a quick hop to the version you want. Is there any chance of seeing such a thing on the V3 docs?

<img width="197" alt="Screen Shot 2022-03-10 at 4 39 34 PM" src="https://user-images.githubusercontent.com/5168781/157759621-d9b7df0b-d0e3-4ef9-8526-9afb320429fd.png">
