### ISSUE TITLE
Update deprecated app.config.isCustomElement 

### ISSUE THREAD

**Issue by Miguel-Bento-Github** [vuejs/docs#1294]
`app.config.isCustomElement` is deprecated and should be replaced with `app.config.compilerOptions.isCustomElement`

This can be found at https://v3.vuejs.org/guide/migration/custom-elements-interop.html#_3-x-syntax

Changes can be done at line 55 and 59 of src/guide/migration/custom-elements-interop.md

**Comment by skirtles-code** [comment]
@Miguel-Bento-Github Thanks for the report. Did you want to put in a PR for this yourself? There's an edit link at the bottom of the deployed page if you don't fancy cloning the repo locally.

I can do it if you prefer.

**Comment by Miguel-Bento-Github** [comment]
@skirtles-code Sounds like a good idea, I'll open the PR for this.

Thanks!

**Comment by Miguel-Bento-Github** [comment]
PR can now be found at https://github.com/vuejs/docs/pull/1307
