### ISSUE TITLE
miss inline code commas cause some text  treated as vue component

### ISSUE THREAD

**Issue by klwfwdk** [vuejs/docs#1308]
miss inline code commas \`\`
[url](https://v3.vuejs.org/api/built-in-components.html#component) 

```
When using <component :is="vnode"> and passing vnode of the same type, you need to provide keys:
```

should be

```
When using `<component :is="vnode">` and passing vnode of the same type, you need to provide keys:
```

**Comment by skirtles-code** [comment]
Thanks for the report. I'll create a PR for this. There are a couple of other problems with the `key` section that I'd also like to resolve.
