### ISSUE TITLE
Project not serving on path with "/" sign 

### ISSUE THREAD

**Issue by casvangrunsven** [vuejs/docs#1309]
Hi,
One of my folders is called "TU/e", which is obviously not so smart because of the "/" sign. The absolute path will be resolved to `/Users/casvangrunsven/Documents/TU:e/Thesis/ambi-2` by macOS (note that the "/" is resolved to ":").

However, when I run `npm run serve`, the project can not be served. The error message is `sh: vue-cli-service: command not found`. A suggestion would be to generate a clearer error message.

**Comment by skirtles-code** [comment]
Thanks for the report, but this issues list is for reporting problems with the Vue 3 documentation. The issues list for Vue CLI is at https://github.com/vuejs/vue-cli/issues.
