### ISSUE TITLE
The example in `v-html` is really running

### ISSUE THREAD

**Issue by mehanalavimajd** [vuejs/docs#1323]
Hi i made a better example for `v-html` in #1314 but it seems it isn't working correctly because the vue code is really running 
screenshot:

![image](https://user-images.githubusercontent.com/74927578/141345139-45a2aea9-376c-45d7-b41a-c43d6f4b6824.png)

**Comment by mehanalavimajd** [comment]
Shall I revert my commit or it's the website bug?

**Comment by skirtles-code** [comment]
I've put in a PR. The indentation change seems to have broken the parser.

**Comment by mehanalavimajd** [comment]
This issue will close with #1326
