### ISSUE TITLE
How do you do When I use Jump to the main content link function + vue - while on a router cannot jump to the main content, the page jumps to a # main position, the question how to deal with, please? Thank you!

### ISSUE THREAD

**Issue by lilangtop** [vuejs/docs#1329]
For example in my current position
127.0.0.1: # 3000 / / home
Click on the links to jump to the main content
<a href="#main" > jump to the main content</a>
At this time not to jump to the location of the element id as the "main", the address bar's url voice change
Became so
192.168.0.1: / # 3000 / main
Excuse me, I should how to ensure that each click to jump to the main content link to be able to make ID a "main" elements of the right focus
Thank you
I wish
A happy life!

**Comment by NataliaTepluhina** [comment]
This issues list is for reporting problems with the documentation. Your question doesn't seem to be about the documentation.

There are alternative resources available if you need help debugging your application. Please, ask you question on the [VueLand Discord](http://chat.vuejs.org).
