### ISSUE TITLE
Clicking close button on Black Friday banner redirect to the page

### ISSUE THREAD

**Issue by immacodder** [vuejs/docs#1332]
Visit https://v3.vuejs.org/api/sfc-script-setup.html for example, and try to dismiss the black friday banner.

**Comment by skirtles-code** [comment]
@nicodevs Would you be able to look into this? It seems that the close button doesn't actually close the banner.

**Comment by nicodevs** [comment]
Yes, I'll look into this shortly

**Comment by nicodevs** [comment]
@skirtles-code here's the fix: https://github.com/vuejs/docs/pull/1333
