### ISSUE TITLE
class binding doc issue

### ISSUE THREAD

**Issue by Chandler-Zhu** [vuejs/docs#1334]
in this [page](https://v3.vuejs.org/guide/class-and-style.html#object-syntax), the `text-danger` class is in quotes, but the  `active` class isn't, is that a typo ?

**Comment by skirtles-code** [comment]
Thanks for the report, but I believe the example is correct.

Object literal property keys in JavaScript need to be wrapped in quotes if they contain hyphens.

**Comment by Chandler-Zhu** [comment]
For example, if the class is `font-bold` I need quotes, if it is `flex` then I don't need quotes. Is that correct ?
Does it cause any error if I use quotes in all scenarios ?
