### ISSUE TITLE
defineEmits doesn't work with script setup

### ISSUE THREAD

**Issue by EmilM32** [vuejs/docs#1337]
vue version: `3.2.2`

I'm trying to use `defineEmits` with script setup feature

 ```js
<script lang="ts" setup>
import { defineEmits } from 'vue'

const emit = defineEmits(['update:modelValue'])

const close = () => emit('update:modelValue')
</script>
```

It throws a vue warn:

```
[Vue warn]: defineEmits() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.
```

I have to import here `defineEmits` from `vue`, without that there is an error:

```
Uncaught (in promise) ReferenceError: defineEmits is not defined
```

**Comment by bencodezen** [comment]
Hey @EmilM32! I tried to reproduce this but was unsuccessful in getting these errors. Can you create a reproduction that we can see? I wonder if this is an ESLint or something else going on.

**Comment by skirtles-code** [comment]
I'd suggest checking that the version of `@vue/compiler-sfc` matches the version of `vue`. It shouldn't be necessary to import it, but you'd need a recent version of the compiler for it to be understood.

**Comment by EmilM32** [comment]
`@vue/compiler-sfc` mismatched `vue` version. Works perfect now, thanks!

**Comment by zds-d** [comment]
`const emit = defineEmits(['formSubmit'])` cannot be written in a function ，If it is written in an arrow function, it will also report an error: defineEmits is not defined
