### ISSUE TITLE
「File not found」page appears when click on the 「element-attribute selectors」link

### ISSUE THREAD

**Issue by selvarajmas** [vuejs/docs#1347]
「File not found」page appears when click on the following links under Detailed Explanation

・element-attribute selectors
・class-attribute selectors

Reference page : https://v3.vuejs.org/style-guide/#element-selectors-with-scoped-use-with-caution

![image](https://user-images.githubusercontent.com/22630424/143174939-cc0e8791-4186-41bf-a2c3-d39465251310.png)

**Comment by NataliaTepluhina** [comment]
Thank you! Removed links for now, the explanation is sufficient without them
