### ISSUE TITLE
can't see the video when i try to open the link in a new tab

### ISSUE THREAD

**Issue by selvarajmas** [vuejs/docs#1348]
can't see the video when i try to open the link in a new tab.

Reference Page : https://v3.vuejs.org/guide/introduction.html#what-is-vue-js

![image](https://user-images.githubusercontent.com/22630424/143182022-26d7b296-fd70-4552-a0dd-567f205057f8.png)

**Comment by NataliaTepluhina** [comment]
I believe we don't have video in the new docs, so we can close the issue :)
