### ISSUE TITLE
Teleport documentation is missing `disabled` prop

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/docs#1359]
https://v3.vuejs.org/guide/teleport.html
Should be mentioned in the docs (it's in the API: https://v3.vuejs.org/api/built-in-components.html#teleport)

**Comment by skirtles-code** [comment]
This has been added to the new guide on the `main` branch. That can currently be seen at https://staging.vuejs.org/guide/built-ins/teleport.html#disabling-teleport.
