### ISSUE TITLE
One Way Data Binding Documentation Needs Clarity

### ISSUE THREAD

**Issue by bengreenow** [vuejs/docs#1362]
Please can someone provide some clarity around the statement:

`Note that objects and arrays in JavaScript are passed by reference, so if the prop is an array or object, mutating the object or array itself inside the child component will affect parent state.`

made here: https://v3.vuejs.org/guide/component-props.html#one-way-data-flow
This note does not specifically tell us to avoid doing this as it an anti-pattern or bad practice. In Vue2 this was definitely considered bad practice because the parent would not react to it but in vue3 this does not seem to be the case we've been modifying array and object props by using toRefs in and are unsure if this is still considered a bad approach.

If so, please could clarity be added to the docs surrounding reference types specifically.

**Comment by NataliaTepluhina** [comment]
In Vue 2 mutating object prop in child _will_ affect parent. This is clearly still a bad approach and we state this in `This means you should not attempt to mutate a prop inside a child component.` This applies to any kind of props.

I agree with that we should probably update the warning with something like "you should still avoid changing props in child component as it's breaking one-way data flow"

**Comment by skirtles-code** [comment]
Closing following the changes in #1365.
