### ISSUE TITLE
The function of switching between day and night in the next branch is not found in config.js. It seems to be the VTSwitchAppearance.vue component of @vue/theme. How do I achieve it?

### ISSUE THREAD

**Issue by LBJDJW** [vuejs/docs#1372]
![image](https://user-images.githubusercontent.com/26969731/145060963-6814ba59-42db-4192-8502-4ecc72bf6842.png)
//.vitepress/config.js
themeConfig: {
    logo: '/logo.svg',
    repo: 'vuejs/docs',

    algolia: {
      indexName: 'vuejs-v3',
      appId: 'BH4D9OD16A',
      apiKey: 'bc6e8acb44ed4179c30d0a45d6140d3f'
    },

    carbonAds: {
      code: 'CEBDT27Y',
      placement: 'vuejsorg'
    },

    socialLinks: [
      { icon: 'languages', link: '/translations/' },
      { icon: 'github', link: 'https://github.com/vuejs/' },
      { icon: 'twitter', link: 'https://twitter.com/vuejs' },
      { icon: 'discord', link: 'https://discord.com/invite/HBherRA' }
    ],

    nav,
    sidebar,

    footer: {
      license: {
        text: 'MIT License',
        link: 'https://opensource.org/licenses/MIT'
      },
      copyright: 'Copyright © 2014-2021 Evan You'
    }
  }

**Comment by kiaking** [comment]
Yes it's using VTSwitchAppearance and there's no config to control. This theme is scoped to the new Vue Website and not sure we gonna make it configurable.

What are you trying to achieve here?

**Comment by LBJDJW** [comment]
I just want to learn about the implementation of this VTSwitchAppearance component. I find it very interesting. Thanks for your answer!

**Comment by yyx990803** [comment]
The theme is currently private but we will open source it when the new docs is ready.

**Comment by yyx990803** [comment]
btw you can actually install `@vue/theme` and look at its source code.

**Comment by LBJDJW** [comment]
> btw you can actually install `@vue/theme` and look at its source code.

My question maybe a bit  low，thank you for your reply,Evan.I am your fan！
