### ISSUE TITLE
Suggestion for friendProps or something

### ISSUE THREAD

**Issue by wayland** [vuejs/docs#1382]
Hi all.  

I've discovered what I believe to be a problem with Vue; not a bug per se, just a point where something that should be possible isn't.  Consider this a suggestion for improvement.  

I'm attempting to make a TabView-like component which contains multiple TabPanels.  These two components could be used from any "parent" component.  Now, each of these components can communicate with the parent component just fine, but they can't really communicate with each other in an effective way.  I'll start with some example templates (in SFC style, but the concept is equally applicable elsewhere):

### The Parent Template
```
<template>
        <TabView header="Data Manager" v-model:data="dialog" path="/path/to/tabview">
                <TabPanel header="Sheets" slug="sheets">
                        Content I
                </TabPanel>
                <TabPanel header="Streams">
                        Content II
                </TabPanel>
        </ManagerDialog>
</template>
```

### The View template
The key thing to notice here is that it picks up a bunch of child panels (function not shown, but it grabs the TabPanels shown above), and then uses <component> to create them.  
```
<template>
        <div class="p-tabview p-component">
                <slot name="navigation" :activeIndex="activeIndex">
                        <TabNav v-model:model="model" v-model:activeIndex="activeIndex"/>
                </slot>
                <div class="p-tabview-panels">
                                <slot>
                                        <template v-for="(childPanel, i) of childPanels" :key="getKey(childPanel,i)">
                                                <div class="p-tabview-panel" role="tabpanel" v-if="lazy ? (d_activeIndex === i) : true" v-show="lazy ? true: (d_activeIndex === i)">
                                                        <component :is="childPanel"></component>
                                                </div>
                                        </template>
                                </slot>
                </div>
        </div>
</template>
```
I won't show the <TabPanel> template because the template is trivial.  

### The Problem

So, now to the problem: As both the TabView and TabPanel grow more complicated (as you can see, I want each TabPanel to have a slug that's added to the path of TabView to create Routes like "/path/to/tabview/sheets".  This and other similar functions belong to the TabPanel rather than TabView, but both TabView and TabPanel depend on data from the other.  

This wouldn't be a problem, except neither has a way of passing data to the other.  I've looked at what others do, and they put all the functionality in TabView, and leave TabPanel just being a template with no code.  This might be fine for relatively trivial examples, but as each becomes more complicated, a bunch of TabPanel-related info ends up on TabView until I realise that I need to create a TabPanel Javascript class (or something) to encapsulate all that functionality of TabPanel, because I can't put it on the actual TabPanel because I have no way of communicating with it.  When I have to create a class to model the functionality of another component just because I can't pass data, then the model is broken.  

### A Suggested Solution

What I would propose is that we have a new component thingy called, say, "friendProps".  The friendProps are declared on the TabPanel component, and the data is attached by using v-model and/or v-bind on the <component> tag.  

- From the POV of TabPanel, they're just more slots that you can pass data in/out with.  
- From the POV of TabView, they're just a way of passing data to the component.  
- From the POV of the parent template, they're completely invisible.  

I'm not attached to the name (change it to whatever you feel is useful).  I'm not attached to it being separate from regular props (if you want to make it possible to connect to regular props via <component>, that would also solve the problem).  What I *am* attached to is a way of passing data between these two components.  

Hope this helps.  Thanks!

**Comment by skirtles-code** [comment]
Hi.

This issues list is specifically for the Vue 3 docs, and it seems that you were looking to open a feature request for Vue itself rather than the docs? I'll try to address your suggestion here anyway because I think it does touch on an area that could be improved within the documentation.

If I've understood what you're asking correctly, then I think the desired effect can be achieved using `provide`/`inject`. I've got an example `Tabs` component that I wrote here to demonstrate the technique:

https://skirtles-code.github.io/vue-examples/components/tabs.html

We're currently working on rewriting the Vue 3 docs (on the `next` branch), but I'm hoping that we might be able to include a `Tabs` example similar to the one above somewhere in the docs once we're done with the core material. I don't think this kind of usage pattern for `provide` and `inject` is widely understood at present.

I can recommend the Vue Land Discord at https://chat.vuejs.org/ if you have any other questions or ideas that you'd like to discuss. It should be a good place to get feedback and suggestions before opening a proper feature request or RFC.

**Comment by wayland** [comment]
Correct on all counts, (except I haven't tested whether that solution works with <component> tabs, but that certainly gives me some things to try).  

That's great; thanks very much.  Feel free to do with this ticket as you like (ie. keep or close, whichever is useful to you).
