### ISSUE TITLE
A confusing sandbox instance

### ISSUE THREAD

**Issue by ekkoyr** [vuejs/docs#1383]
The sandbox is in "https://v3.vuejs.org/guide/component-basics.html#dynamic-components" whose name is "this version"https://codepen.io/team/Vue/pen/oNXapXM . There has three "app.component()" and a computed value which is not necessary, and make people confused.

**Comment by NataliaTepluhina** [comment]
@ekkoyr thank you for spotting this! Codepen fixed, it may take some time for embedded one in the docs to update but you can check changes directly on the CodePen
