### ISSUE TITLE
vue next template explorer examples broken in the docs

### ISSUE THREAD

**Issue by Fanna1119** [vuejs/docs#1400]
I realised that the state of https://vue-next-template-explorer.netlify.app is stored in the localstorage.
A while ago i edited a doc example on it by mistake, which seem to cause some kind of caching issue where it displayed my edited code on every page where vue-next-template-explorer.netlify.app examples are embedded and used. 
I tried to delete the localstorage and hard refresh, which ended up just completely breaking it and
 throwing:

```js
template-explorer.global.js:37870 
Uncaught TypeError: Cannot convert undefined or null to object
    at window.init (template-explorer.global.js:37870)
    at Function.t._invokeFactory (loader.js:1036)
    at t.complete (loader.js:1046)
    at s._onModuleComplete (loader.js:1663)
    at s._onModuleComplete (loader.js:1675)
    at s._onModuleComplete (loader.js:1675)
    at s._onModuleComplete (loader.js:1675)
    at s._onModuleComplete (loader.js:1675)
    at s._onModuleComplete (loader.js:1675)
    at s._onModuleComplete (loader.js:1675)

```
![Screenshot from 2021-12-27 13-31-54](https://user-images.githubusercontent.com/4569097/147467637-5e958437-9ffc-4cd8-bfd5-a310912f7260.png)
![Screenshot from 2021-12-27 13-32-24](https://user-images.githubusercontent.com/4569097/147467649-35a7d8c4-88ee-47e7-8cfd-2a72da0dc29a.png)

on firefox(which i never use)
![Screenshot from 2021-12-27 13-38-30](https://user-images.githubusercontent.com/4569097/147468034-4f58ff4f-45d4-4273-b33b-1895b591b856.png)

**Comment by yyx990803** [comment]
This doesn't seem to be related to the new docs. Current v3.vuejs.org is being retired and the template explorer has also moved to a new address at https://template-explorer.vuejs.org - new version should also recover from failed storage read.
