### ISSUE TITLE
grid-component example not working

### ISSUE THREAD

**Issue by ruralcoder** [vuejs/docs#1419]
Issues: 
- Elements in iteration expect to have 'v-bind:key' directives
- Duplicated key 'sortOrders'
- Cannot get the ASC / DSC working with vue 3

**Comment by skirtles-code** [comment]
Thanks for the report.

There's work-in-progress on a new version of the docs on the `next` branch. The grid example has been reworked and is available to preview here:

https://staging.vuejs.org/examples/#grid

This should address the `sortOrders` and sorting problems.

The missing `key` on the iterations may need further attention. I'm not sure how I feel about that.

**Comment by ruralcoder** [comment]
Thanks for looking into this.

Isn't the `:key="id"` a must have in vue v3?

This is what I see in visual studio
<img width="943" alt="Screen Shot 2022-01-19 at 10 40 44 AM" src="https://user-images.githubusercontent.com/12993309/150193754-ed50dd05-15ce-4ff3-adea-0c69ef79257b.png">
