### ISSUE TITLE
Wrong description of custom directive in documentation(vue 3)

### ISSUE THREAD

**Issue by rinbowLi** [vuejs/docs#1428]
![image](https://user-images.githubusercontent.com/38241103/149048459-2e687679-21e2-405c-839f-62a353b2df9b.png)
This is the description in the documentation（vue3）
[the link to the documentation](https://v3.vuejs.org/guide/custom-directive.html)

- test code
```
<script>
import { ref, onMounted,onBeforeMount } from "vue";
export default {
  directives: {
    focus: {
      beforeMount() {
        console.log("custom-directive's beforeMount");
      },
      mounted(el) {
        console.log("custom-directive's mounted");
        el.focus();
      },
    },
  },
  setup() {
    const inputValue = ref("123");


    onBeforeMount(() => {
      console.log("component's onBeforeMount");
    });

    onMounted(() => {
      console.log("component's onMounted");
    });


    return () => (
      <div>
        <h2>{inputValue.value}</h2>
        <input v-model={inputValue.value} v-focus />
      </div>
    );
  },
};
</script>
```

![image](https://user-images.githubusercontent.com/38241103/149048807-5e4d3ba2-2fb7-4ca8-9346-b7f8324250ac.png)

Here is a screenshot of the printout

Obviously the mounted of the custom directive is earlier than the onMounted of the component, so the documentation describes the error

**Comment by NataliaTepluhina** [comment]
Closing the issue as related PR was merged
