### ISSUE TITLE
Template Refs documentation is incomplete when not using script setup

### ISSUE THREAD

**Issue by SatheesA** [vuejs/docs#1436]
on https://staging.vuejs.org/guide/essentials/template-refs.html#ref-on-component there should be mentioned that you should return the template Ref variable for it to work when not using script setup.

on this page it has a working example without using script setup: 
https://v3.vuejs.org/guide/composition-api-template-refs.html

Used a lot of time to find out what was wrong

**Comment by jdbaculard-ap** [comment]
Yes i have the same problem
How i use template ref with script setup. When 
ref="root"
How i use the variable root in my script
Thanks
