### ISSUE TITLE
Clarify V3 Migration strategy for TS Vue.extend

### ISSUE THREAD

**Issue by lukashroch** [vuejs/docs#1446]
Migration strategies for V2 to V3 (https://v3.vuejs.org/guide/migration/migration-build.html#expectations) do not provide info about recommended strategy for Vue.extend Typescript support, which was suggested way for V2.

In V2, Vue.extend could be leveraged to provide additional types for options API like mixins, vuex bindings, $refs etc like following snippet.

```js
type AdditionalNotInferredTypes = {
  $refs: {
    someComponent: InstanceType<typeof someComponent>;
  },
  ...
  vuex bindings etc.
  ...
};

type Mixins = InstanceType<typeof someMixin>;

export default (Vue as VueConstructor<Vue & AdditionalNotInferredTypes & Mixins>).extend({...})
```

Vue.extend seems to be gone in Vue3...? But Options API is still fully supported. So was wondering what's a proper way to provide additional not inferred types. `defineComponent` infers everything to `unknown`.

**Comment by yyx990803** [comment]
https://vuejs.org/api/utility-types.html#componentcustomproperties
