### ISSUE TITLE
Missing pages in style guide

### ISSUE THREAD

**Issue by crystalfp** [vuejs/docs#1487]
All the pages linked from https://staging.vuejs.org/style-guide/ are missing, for example
https://staging.vuejs.org/style-guide/rules-essential.html

**Comment by crystalfp** [comment]
All pages from staging besides the top ones are missing. Has the new documentation found a new home?

**Comment by crystalfp** [comment]
This happens from Firefox. From Chrome everything works.

**Comment by skirtles-code** [comment]
They seem to be working in Firefox for me.

Is it possible you're seeing a cached version of the site?

**Comment by crystalfp** [comment]
I remember something similar happened with [typescript ](https://www.typescriptlang.org/) site and was due to cookies. Anyway, I moved to Chrome and forgot the issue.
Thanks!
mario
