### ISSUE TITLE
Broken link for Special Sponsors

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/docs#1495]
## Steps to reproduce

1. Navigate to vuejs.org homepage
2. Click special sponsor link
3. Nothing happens

<img width="569" alt="Screen Shot 2022-02-07 at 5 58 54 AM" src="https://user-images.githubusercontent.com/2801156/152775675-24ba1cf0-86c8-4385-bee0-a98db1f7b74e.png">

**Comment by NataliaTepluhina** [comment]
Closing as related MR was merged
