### ISSUE TITLE
You found a dead link: /guide/essentials/application.html

### ISSUE THREAD

**Issue by NameNolen** [vuejs/docs#1512]
![image](https://user-images.githubusercontent.com/15980450/153424717-445cac34-5b3d-42ff-b635-03276db69635.png)

I do not know how to recurrence it.
I was browsing the 'Quick Start' page and click somewhere else and use the mouse's fourth button to go back. 
At last click 'Continue the guide' button the end of the page and see that.

**Comment by yyx990803** [comment]
Could be caused by a network error when dynamically fetching the page, or due to non-cleared service worker from v2? Either way this should not happen once you refresh the page. Please open new issue if this happens again.
