### ISSUE TITLE
Wrong information about unwrapping refs in templates

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/docs#1539]
<https://vuejs.org/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates>

Following:

![image](https://user-images.githubusercontent.com/15625235/153826512-9b6cad4a-05f7-40d9-8a65-8d07a0730dd4.png)

is not true:

<https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGEgPSB7IGI6IHJlZigxKSB9XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT57eyBhLmIgfX08L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==>

because:

https://github.com/vuejs/core/commit/f994b974c0a1ac95d313c8ccfc258c6ba3910b6e

**Comment by lidlanca** [comment]
works  - implicit unref in `toDisplayString`
```js
{{ object.foo }}
```
won't work
```js
<button @click='object.foo++'>increment</button>
```

so it might be worth changing the example to better explain where it might fail and where not.
