### ISSUE TITLE
feat: wanted more width content area

### ISSUE THREAD

**Issue by xgqfrms** [vuejs/docs#1540]
# feat: wanted more width content area

> the content area width so narrow,  that caused many screen spaces waster.

https://vuejs.org/guide/introduction.html

![image](https://user-images.githubusercontent.com/7291672/153828911-acb41da0-94e1-4c86-b657-f3acf82e698e.png)

![image](https://user-images.githubusercontent.com/7291672/153829212-d02912fb-3875-43d3-ad25-76663f439563.png)

**Comment by xgqfrms** [comment]
# my suggestion


```diff

.aside {
  width: 320px;
}

.content {
-  max-width:  688px;
+  max-width: cacl(100vw - 2 * 320px);
}

```

**Comment by yyx990803** [comment]
Content isn't the wider the better. [Content being too wide actually makes it harder to read.](https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/)
