### ISSUE TITLE
Documentation: Toggle between composition-API and options-API should be visible per default

### ISSUE THREAD

**Issue by matrium0** [vuejs/docs#1562]
### What problem does this feature solve?
II learned Vue and started with the recommended syntax (script setup / composition) and had the problem that the whole documentation seemed to be written only for options API. It took me very long to even find out how to define props with composition API.

There is a toggle button to switch between the APIs (which is awesome), but sadly it is hidden behind the "API Reference"-drop down and can be easily missed (I certainly did).

### What does the proposed API look like?
It would be really great if displaying the API-Switch-toggle could be the default. If this disrupts the style of the application you could use another flag in localstorage to capture the state of the drop-down. This way it could be opened by default, but users can close it if they don't want to be bothered again

**Comment by yyx990803** [comment]
I should be open by default if you haven't already clicked it in the past - but I've updated it to be open by default in all cases.

**Comment by matrium0** [comment]
I don't think it was opened by default for me before. I believe I cleared localstorage and tried again before creating this request, though maybe I am wrong and I forgot to
Either way - it's always visible now - thank you! Awesome documentation by the way.
