### ISSUE TITLE
How to do Platinum sponsorship activation for ButterCMS

### ISSUE THREAD

**Issue by jakelumetta** [vuejs/docs#1565]
Hi @yyx990803 @NataliaTepluhina

We (ButterCMS) are excited to sponsor VueJs. We submitted the [form](https://airtable.com/shrLcDpZ6g55ZzRq8) on Wednesday. What are next steps?

Thanks!

**Comment by jakelumetta** [comment]
Hi - just following up on this. Is there anything else needed from our end? Thanks!

**Comment by yyx990803** [comment]
Apologies, the system failed to match the records because the form received `buttercms` but the user id is `ButterCMS` which is case-sensitive. I've manually fixed the info and updated the system to normalize the case when matching IDs. The logo is live now.
