### ISSUE TITLE
Onboarding new devs, composition API

### ISSUE THREAD

**Issue by warrior-dev** [vuejs/docs#1566]
We are working on an introductory video of Vue Js (in Spanish) and I noticed that the introduction and quickstart on the official website is focused on the option api, which disagrees with the community recommendation.

Shouldn't we directly introduce the new devs via the composition api?

**Comment by NataliaTepluhina** [comment]
@warrior-dev the guide is written in this way intentionally. We explain different API styles in the `Introduction` right after showing the initial example (that uses Options API indeed). For Quick Start, we can add a Composition API alternative to code snippets like it was done for the rest of the guide.

**Comment by warrior-dev** [comment]
Yes, it would be ideal to integrate the code snippet as in the rest of the guide.

I also think that the first example as soon as you click "get started" at the beginning should be in the composition api, but I guess there is a reason.

Thank you for all the effort, I greatly appreciate it 🔥

**Comment by Simran-B** [comment]
Just stumbled over this as well, looking at [Splitting Up the Modules](https://vuejs.org/guide/quick-start.html#splitting-up-the-modules) in the Quick Start. The toggle for Options and Composition API has no effect, the example always uses the Options API.

I think it would also be helpful to mention the toggle in the Introduction, e.g. in the Which to Choose? section - I completely missed it at first.

**Comment by NataliaTepluhina** [comment]
Quick start was rewritten with Composition API in mind so I am closing this issue
