### ISSUE TITLE
Missing `getCurrentInstance` API

### ISSUE THREAD

**Issue by ydcjeff** [vuejs/docs#1609]
`getCurrentInstance` was previously available on https://v3.vuejs.org and is missing on https://vuejs.org

![Screen Shot 2022-03-09 at 21 15 04](https://user-images.githubusercontent.com/32727188/157465088-89c0df0a-4ce9-41c5-aa2f-ad1035b73b3a.png)

**Comment by skirtles-code** [comment]
I think this is probably intentional. See https://github.com/vuejs/docs/issues/1422#issuecomment-1032120675. While `getCurrentInstance` was added to the docs, the object is returned was never documented and is considered internal.

**Comment by ydcjeff** [comment]
Thanks @skirtles-code
