### ISSUE TITLE
defining a component

### ISSUE THREAD

**Issue by mariusa** [vuejs/docs#1611]
This still uses Vue 2 syntax: https://vuejs.org/guide/essentials/component-basics.html#defining-a-component

How can one define and use a component with Vue 3 `<script setup>` ?

**Comment by skirtles-code** [comment]
By Vue 2 syntax, I assume you mean the Options API? That is still valid Vue 3 syntax and appears throughout the docs.

You can change most of the examples to show Composition API syntax instead by toggling the **API Preference** switch at the top left of the page. Please see https://vuejs.org/guide/introduction.html for more information.

**Comment by mariusa** [comment]
Thank you, I missed that!
