### ISSUE TITLE
Missing explanation of the Callback Flush Timing `'sync'` option

### ISSUE THREAD

**Issue by DrJume** [vuejs/docs#1612]
https://vuejs.org/guide/essentials/watchers.html#callback-flush-timing

**Comment by skirtles-code** [comment]
I suspect it's intentionally missing from that section, as `sync` is an escape-hatch for edge cases and not necessarily something that needs to be covered in the main guide. However, it doesn't currently seem to be explained anywhere else, and I'd definitely agree that it needs to be explained somewhere.

**Comment by skirtles-code** [comment]
A brief explanation of `flush: 'sync'` was added in #1895. The explanation is in the API docs, rather than the guide.
