### ISSUE TITLE
Add documentation on fragments

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs#162]

**Comment by edimitchel** [comment]
@bencodezen is it possible to use fragments manually ? i.e. when I want to create an wrapper in a component which I cannot split. We can use `template` for that but I'm asking if a new global component will be added, like <fragment> ou <> ?

**Comment by bencodezen** [comment]
Hey @edimitchel! To make sure I understood the question correctly, are you asking whether or not fragments can be used in global components as a generic wrapper? Also, if possible, could you provide some pseudo-code to show an example of what you're thinking of?

**Comment by edimitchel** [comment]
My bad ! I was totally wrong ! Fragment inside a component is not usefull because multi component is already possible inside any non-root element.
