### ISSUE TITLE
Security of sponsored HBuilder IDE

### ISSUE THREAD

**Issue by federico-ntr** [vuejs/docs#1623]
I wanted to try this sponsored IDE on my work machine, but seeing the download was being stopped I thought it might have raised an alarm on our security tools. I finally managed to download it and I made a VirusTotal scan, the result of which you can see here:

![virustotal result](https://user-images.githubusercontent.com/35468654/158841093-381efa24-568e-4de1-ab18-8f885f61bb98.png)

[Here](https://www.virustotal.com/gui/file/66991d4656e78320f608ad52cee84d8412a8bc3e44558c9483ddb4e87b81b59d?nocache=1) is the direct link to the scan.

Is that product actually to be trusted? Is there an explanation for those two malicious detections?
Thanks in advance.

PS: I saw the banner on Vue 2 docs but it's listed among the sponors of both Vue 2 and Vue 3 docs.

**Comment by yyx990803** [comment]
Thanks for the report. We are not aware of this, but I know the sponsoring company and trust that they will not be intentionally shipping anything malicious. We will report it to the sponsor to let them know.
