### ISSUE TITLE
Options API error in tutorial step 5

### ISSUE THREAD

**Issue by ChloeLiang** [vuejs/docs#1628]
**Actual**

- Visit [Tutorial Step 5](https://vuejs.org/tutorial/#step-5).
- The `onInput` method is using `text.value`.

**Expected**

- It should be `this.text`.

**Screenshot**

<img width="593" alt="Screenshot 2022-03-21 at 12 08 42 PM" src="https://user-images.githubusercontent.com/28077042/159204367-6a6b989f-eebb-4052-83a0-c2d17c04ab71.png">

**Comment by NataliaTepluhina** [comment]
@ChloeLiang thank you for reporting this! Fixed now 🙇🏻
