### ISSUE TITLE
docs wrongly say that in script setup components are automatically registered locally when they are not

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/docs#1638]
## Docs

https://vuejs.org/guide/components/registration.html#local-registration

> When using SFC with `<script setup>`, imported components are automatically registered locally:

If they are registered locally it should be possible to do `<component is="comp" />`

## Plaground

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSc7XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8Y29tcCAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiQ29tcC52dWUiOiI8dGVtcGxhdGU+Zm9vPC90ZW1wbGF0ZT4ifQ==

## Compiled JS

```js
/* Analyzed bindings: {
  "Comp": "setup-const"
} */
import { openBlock as _openBlock, createBlock as _createBlock } from "vue"

import Comp from './Comp.vue';

const __sfc__ = {
  setup(__props) {

  
return (_ctx, _cache) => {
  return (_openBlock(), _createBlock(Comp))
}
}

}
__sfc__.__file = "App.vue"
export default __sfc__
```

**Comment by NataliaTepluhina** [comment]
@jacekkarczmarczyk I am not sure I follow 🤔 `  <component :is="Comp"></component>` works for me on a playground

**Comment by jacekkarczmarczyk** [comment]
playground was mainly to show that the component is not being registered (in compiled JS)

**Comment by skirtles-code** [comment]
@NataliaTepluhina The problem is that a component can't be used via its string name with `is`. It isn't 'locally registered' in the same sense as it would be if it used the `components: {}` option. It isn't really being registered at all.

**Comment by leopiccionia** [comment]
Instead of stating that
> imported components are automatically registered locally

that's false, because there's no registration in the generated code, docs should say something like
> imported components can be locally used without registration

**Comment by leopiccionia** [comment]
I'll open a PR tomorrow, thanks.
