### ISSUE TITLE
Getting the home of an element via ref for vue 3

### ISSUE THREAD

**Issue by Roman-00** [vuejs/docs#1643]
### Discussed in https://github.com/vuejs/docs/discussions/1641

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** March 26, 2022</sup>
Faced with the following problem:

When iterating through and rendering data via v-for, it is not possible to access the home element via ref.

Vue js version - 3.2.31

The documentation states that it can be obtained as follows - https://vuejs.org/guide/essentials/template-refs.html#refs-inside-v-for

Example from the documentation:

![example2](https://user-images.githubusercontent.com/58338625/160226224-bd0191b8-2af0-48ce-b077-c73788aad579.jpg)

My code example:

![example1](https://user-images.githubusercontent.com/58338625/160226255-f2060a63-c82d-4c9b-8b24-6b830a4447d3.jpg)

![example3](https://user-images.githubusercontent.com/58338625/160226282-87e131e3-60be-4106-ac07-ef0cc7afd18f.jpg)

![example4](https://user-images.githubusercontent.com/58338625/160226285-75dad246-6ce5-44e3-a96b-12e819ec88ab.jpg)

but for some reason, it doesn't work.

Maybe someone has already faced such a problem?

</div>

**Comment by skirtles-code** [comment]
I believe this is a core bug rather than a docs problem. See <https://github.com/vuejs/core/issues/5525>. I believe that'll be fixed in the next patch release, but there's a workaround suggested on that issue in the meantime.
