### ISSUE TITLE
globalProperties 在库里面定义全局问题

### ISSUE THREAD

**Issue by jiawenguang** [vuejs/docs#1654]
我在写一个vue3.x的ui库的时候，通过vue/cli的构建目标。
`"lib": "vue-cli-service build --target lib --name ZMZ --dest lib packages/index.js"`
去打包一个库的时候，我们通过globalProperties 定义的全局属性，提示我们globalProperties 未定义，
发现globalProperties 必须通过createApp({})创建以后才能使用，这让我们在进行构建的时候产生了难题。

而vue3已经不允许通过prototype来定义全局。

而在普通的html文件中通过cdn连接的方式引入vue 和我们生成的组件的时候产生的问题

**Comment by skirtles-code** [comment]
I'm not exactly sure what you're asking, but as far as I can tell, the problem you're reporting isn't a documentation issue. This issues list is for reporting problems with the Vue 3 documentation.

If you're looking for help with your code, I suggest trying [Discord](https://chat.vuejs.org/).
