### ISSUE TITLE
Syntax error in list example

### ISSUE THREAD

**Issue by defool** [vuejs/docs#1667]
The example in https://github.com/vuejs/docs/blob/main/src/guide/essentials/list.md:
```
<li v-for="item in items">
  {{ item.message }}
</li>
```
Error in the example:
```
[vue/require-v-for-key]
Elements in iteration expect to have 'v-bind:key' directives.
```
It  indicates that the `:key` attribute is necessary.

**Comment by NataliaTepluhina** [comment]
The `key` attribute is not required on its own and the example will be working without it. The error is brought by ESLint plugin. We intentionally didn't put `key` in the first example to reduce the mental overhead, it's explained later in this section of the docs.
