### ISSUE TITLE
Default export of the module has or is using private name 'Props'.ts

### ISSUE THREAD

**Issue by kmq116** [vuejs/docs#1678]
I create a vue3 + typescript + vite project , when I packaging a component by <script setup lang="ts">, I refer to the documents of  [<script setup>](https://vuejs.org/api/sfc-script-setup.html)  
![微信截图_20220422141917](https://user-images.githubusercontent.com/59247607/164615150-60e035ba-30da-4146-9e00-1c85cd6ea17f.png)  

but get this issue  
![微信截图_20220422142053](https://user-images.githubusercontent.com/59247607/164615383-7bf1611f-53d3-4a18-b806-f8176d7c34d9.png)

then I tried using the following 
![微信截图_20220422142409](https://user-images.githubusercontent.com/59247607/164615757-30d8714e-7722-4d16-a341-e31382117d3e.png)
I can see the error disappear
I wonder what the reason is 🤔

**Comment by jaredmcateer** [comment]
We only see this issue when bundling our code and emitting declarations (ie., `vite build && vue-tsc --emitDeclarationsOnly`) so neither the editor nor our lint command (`vue-tsc --noEmit`) show this as a problem. 

The workaround is to either use inline type definition like @kmq116 has shown above or to export it (e.g., `export interface Props {...}`) but that is not very intuitive, especially when there is no error until the emitting the declarations.

**Comment by kmq116** [comment]
> 

Wow, very thanks !!!

**Comment by skirtles-code** [comment]
I'm reopening this. I don't fully understand it, but the bottom line is that the code shown in the docs leads to an error.
