### ISSUE TITLE
Drop down menu not completely visible on smaller displays

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/docs#1681]
I'm viewing the Vue site on my laptop with a resolution of 3840x2160 (250% scaling). The drop down menu is partially hidden because it is taller than the view port. In this case, the bottom link in Ecosystem is hidden (I wasn't even sure there was more, but on a hunch I shrunk the size in Edge):

![image](https://user-images.githubusercontent.com/393660/164910120-1b915dbe-fc93-4ab9-8360-406f9707fea9.png)

**Comment by WebMechanic** [comment]
+ 1 year in... still broken ;-)

**Ecosystem** menu is cut off on 1040px (1dpr) screens like landscape tablets w/ default 100% zoom.
With browser's chrome visible the last items are hidden and inaccessible (can't use Tab-key to navigate on touch devices).

Maybe check with `@media (max-height: ...)` and go two-columns or turn it into sub-menus.

**Comment by brc-dd** [comment]
should be fixed by #2380 IG
