### ISSUE TITLE
Closing tag doesn't match in figure explaining named slots

### ISSUE THREAD

**Issue by zkriszti** [vuejs/docs#1688]
When explaining named slots, the right part of the explaining figure has a mismatching ending tag. 
URL: https://vuejs.org/guide/components/slots.html#named-slots

Screenshot: 
![closing-tag](https://user-images.githubusercontent.com/21139399/165604586-f6350e4d-32c8-4a35-9b3c-770a8c7fc210.png)

Expected: 
the ending tag should be a </div> closing tag, instead of the present </button> closing tag.

**Comment by NataliaTepluhina** [comment]
Thank you for reporting this! Diagram updated 👍🏻
