### ISSUE TITLE
Ref on Component doesn't work?

### ISSUE THREAD

**Issue by hlf2016** [vuejs/docs#1695]
[Ref on Component](https://staging-cn.vuejs.org/guide/essentials/template-refs.html#ref-on-component)

When I did follow the doc above, I didn't get the expected result.

What I get was just undefine or null.

The pic below is the  result from my code.

### parent component

```
<template>
          <Header ref="jjj"></Header>
</template>
<script setup>

import { onMounted, ref } from 'vue';

// 为了通过组合式 API 获得该模板 ref，我们需要声明一个同名的 ref
const jjj = ref(null)
console.log(jjj)
</script>
```

### sub component
```
<script setup>
import { ref} from 'vue';

const a = 1
const b = ref(2)

defineExpose({
  a,
  b
})
</script>
```
### result
![SCR-20220503-20n](https://user-images.githubusercontent.com/24551738/166295263-29058956-15ad-40d1-afda-0c8328e89872.png)

**Comment by liulinboyi** [comment]
You can look at these examples:

[Example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8SGVhZGVyIHJlZj1cImhlYWRlclwiPjwvSGVhZGVyPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgSGVhZGVyIGZyb20gJy4vSGVhZGVyLnZ1ZSdcblxuLy8g5Li65LqG6YCa6L+H57uE5ZCI5byPIEFQSSDojrflvpfor6XmqKHmnb8gcmVm77yM5oiR5Lus6ZyA6KaB5aOw5piO5LiA5Liq5ZCM5ZCN55qEIHJlZlxuY29uc3QgaGVhZGVyID0gcmVmKG51bGwpXG5jb25zb2xlLmxvZyhoZWFkZXIpXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiSGVhZGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGEgPSAxXG5jb25zdCBiID0gcmVmKDIpXG5cblxuXG5jb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG5kZWZpbmVFeHBvc2Uoe1xuICBhLFxuICBiLFxuICBjdHg6IGluc3RhbmNlLmN0eFxufSlcblxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbnt7YX19IHt7Yn19XG48L3RlbXBsYXRlPiJ9)

[Example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8SGVhZGVyIHJlZj1cImhlYWRlclwiPjwvSGVhZGVyPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgSGVhZGVyIGZyb20gJy4vSGVhZGVyLnZ1ZSdcblxuLy8g5Li65LqG6YCa6L+H57uE5ZCI5byPIEFQSSDojrflvpfor6XmqKHmnb8gcmVm77yM5oiR5Lus6ZyA6KaB5aOw5piO5LiA5Liq5ZCM5ZCN55qEIHJlZlxuY29uc3QgaGVhZGVyID0gcmVmKG51bGwpXG5jb25zb2xlLmxvZyhoZWFkZXIpXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiSGVhZGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGEgPSAxXG5jb25zdCBiID0gcmVmKDIpXG5cblxuLypcbmNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbmRlZmluZUV4cG9zZSh7XG4gIGEsXG4gIGIsXG4gIGN0eDogaW5zdGFuY2UuY3R4XG59KVxuKi9cblxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG57e2F9fSB7e2J9fVxuPC90ZW1wbGF0ZT4ifQ==)

**Comment by phanan** [comment]
👋 Since you're using `<script setup>`, by the time you `console.log` the template ref, your component hasn't been mounted, hence the `null` value. Try putting the log call inside `onMounted()` and you should see the expected behavior.

**Comment by hlf2016** [comment]
> You can look at these examples:
> 
> [Example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8SGVhZGVyIHJlZj1cImhlYWRlclwiPjwvSGVhZGVyPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgSGVhZGVyIGZyb20gJy4vSGVhZGVyLnZ1ZSdcblxuLy8g5Li65LqG6YCa6L+H57uE5ZCI5byPIEFQSSDojrflvpfor6XmqKHmnb8gcmVm77yM5oiR5Lus6ZyA6KaB5aOw5piO5LiA5Liq5ZCM5ZCN55qEIHJlZlxuY29uc3QgaGVhZGVyID0gcmVmKG51bGwpXG5jb25zb2xlLmxvZyhoZWFkZXIpXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiSGVhZGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGEgPSAxXG5jb25zdCBiID0gcmVmKDIpXG5cblxuXG5jb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG5kZWZpbmVFeHBvc2Uoe1xuICBhLFxuICBiLFxuICBjdHg6IGluc3RhbmNlLmN0eFxufSlcblxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbnt7YX19IHt7Yn19XG48L3RlbXBsYXRlPiJ9)
> 
> [Example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8SGVhZGVyIHJlZj1cImhlYWRlclwiPjwvSGVhZGVyPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgSGVhZGVyIGZyb20gJy4vSGVhZGVyLnZ1ZSdcblxuLy8g5Li65LqG6YCa6L+H57uE5ZCI5byPIEFQSSDojrflvpfor6XmqKHmnb8gcmVm77yM5oiR5Lus6ZyA6KaB5aOw5piO5LiA5Liq5ZCM5ZCN55qEIHJlZlxuY29uc3QgaGVhZGVyID0gcmVmKG51bGwpXG5jb25zb2xlLmxvZyhoZWFkZXIpXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiSGVhZGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGEgPSAxXG5jb25zdCBiID0gcmVmKDIpXG5cblxuLypcbmNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbmRlZmluZUV4cG9zZSh7XG4gIGEsXG4gIGIsXG4gIGN0eDogaW5zdGFuY2UuY3R4XG59KVxuKi9cblxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG57e2F9fSB7e2J9fVxuPC90ZW1wbGF0ZT4ifQ==)

It doesnt't work for me or the way I get the result was wrong?
![image](https://user-images.githubusercontent.com/24551738/166400165-96834a88-5f89-4424-9f13-6fac915bc81e.png)

**Comment by hlf2016** [comment]
> 👋 Since you're using `<script setup>`, by the time you `console.log` the template ref, your component hasn't been mounted, hence the `null` value. Try putting the log call inside `onMounted()` and you should see the expected behavior.

It doesn't work for me
![image](https://user-images.githubusercontent.com/24551738/166400747-8ea8de61-7559-4f86-b438-da628a89aff8.png)

**Comment by liulinboyi** [comment]
> > You can look at these examples:
> > [Example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8SGVhZGVyIHJlZj1cImhlYWRlclwiPjwvSGVhZGVyPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgSGVhZGVyIGZyb20gJy4vSGVhZGVyLnZ1ZSdcblxuLy8g5Li65LqG6YCa6L+H57uE5ZCI5byPIEFQSSDojrflvpfor6XmqKHmnb8gcmVm77yM5oiR5Lus6ZyA6KaB5aOw5piO5LiA5Liq5ZCM5ZCN55qEIHJlZlxuY29uc3QgaGVhZGVyID0gcmVmKG51bGwpXG5jb25zb2xlLmxvZyhoZWFkZXIpXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiSGVhZGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGEgPSAxXG5jb25zdCBiID0gcmVmKDIpXG5cblxuXG5jb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG5kZWZpbmVFeHBvc2Uoe1xuICBhLFxuICBiLFxuICBjdHg6IGluc3RhbmNlLmN0eFxufSlcblxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbnt7YX19IHt7Yn19XG48L3RlbXBsYXRlPiJ9)
> > [Example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8SGVhZGVyIHJlZj1cImhlYWRlclwiPjwvSGVhZGVyPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgSGVhZGVyIGZyb20gJy4vSGVhZGVyLnZ1ZSdcblxuLy8g5Li65LqG6YCa6L+H57uE5ZCI5byPIEFQSSDojrflvpfor6XmqKHmnb8gcmVm77yM5oiR5Lus6ZyA6KaB5aOw5piO5LiA5Liq5ZCM5ZCN55qEIHJlZlxuY29uc3QgaGVhZGVyID0gcmVmKG51bGwpXG5jb25zb2xlLmxvZyhoZWFkZXIpXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiSGVhZGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGEgPSAxXG5jb25zdCBiID0gcmVmKDIpXG5cblxuLypcbmNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbmRlZmluZUV4cG9zZSh7XG4gIGEsXG4gIGIsXG4gIGN0eDogaW5zdGFuY2UuY3R4XG59KVxuKi9cblxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG57e2F9fSB7e2J9fVxuPC90ZW1wbGF0ZT4ifQ==)
> 
> It doesnt't work for me or the way I get the result was wrong? ![image](https://user-images.githubusercontent.com/24551738/166400165-96834a88-5f89-4424-9f13-6fac915bc81e.png)

You can look at these examples:

[Example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8SGVhZGVyIHJlZj1cImhlYWRlclwiPjwvSGVhZGVyPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBvbk1vdW50ZWQsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgSGVhZGVyIGZyb20gJy4vSGVhZGVyLnZ1ZSdcblxuLy8g5Li65LqG6YCa6L+H57uE5ZCI5byPIEFQSSDojrflvpfor6XmqKHmnb8gcmVm77yM5oiR5Lus6ZyA6KaB5aOw5piO5LiA5Liq5ZCM5ZCN55qEIHJlZlxuY29uc3QgaGVhZGVyID0gcmVmKG51bGwpXG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGNvbnNvbGUubG9nKGhlYWRlcilcblx0Y29uc29sZS5sb2coaGVhZGVyLnZhbHVlKVxuICBjb25zb2xlLmxvZyhoZWFkZXIudmFsdWUuYSlcbn0pXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiSGVhZGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGEgPSAxXG5jb25zdCBiID0gcmVmKDIpXG5cblxuXG5jb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG5kZWZpbmVFeHBvc2Uoe1xuICBhLFxuICBiLFxuICBjdHg6IGluc3RhbmNlLmN0eFxufSlcblxuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbnt7YX19IHt7Yn19XG48L3RlbXBsYXRlPiJ9)
