### ISSUE TITLE
Reference all components prompt not found

### ISSUE THREAD

**Issue by WorldToCode** [vuejs/docs#1700]
Using ../ or ./ doesn't fix it either
![image](https://user-images.githubusercontent.com/65691266/166886235-8e081116-51cb-469a-9118-884d3fa69d15.png)

**Comment by WorldToCode** [comment]
![image](https://user-images.githubusercontent.com/65691266/166886440-6988458d-71d4-41de-8bcb-48e7bad3f645.png)

**Comment by WorldToCode** [comment]
Found the reason，but the documentation is too little, it's misleading

**Comment by yyx990803** [comment]
Your error is related to build alias configuration and has nothing to do with main Vue documentation.

**Comment by WorldToCode** [comment]
> 您的错误与构建别名配置有关，与主 Vue 文档无关。

Isn't it the problem of not creating js files, importing and exporting components uniformly
![image](https://user-images.githubusercontent.com/65691266/166893443-5b25f72a-69a9-4f7c-8892-053118b294e0.png)
![image](https://user-images.githubusercontent.com/65691266/166893309-17c5189c-36bd-4c81-94ee-3709805faf66.png)
