### ISSUE TITLE
Ambiguous usage "once observed"

### ISSUE THREAD

**Issue by skynavga** [vuejs/docs#1703]
**Document**

https://vuejs.org/api/options-state.html#data

**Improvement**

Define or refer to definition of "observed" as used in

> Once observed, you can no longer add reactive properties to the root data object.

N.B. The terms _observe_ and _observed_ are also used in the [ECMAScript® 2023 Language Specification](https://tc39.es/ecma262/) without any formal definition.

**Comment by skirtles-code** [comment]
This has been carried over from the Vue 2 docs. I agree it needs rewording. I'm also unclear what is meant by 'once observed'.
