### ISSUE TITLE
Tutorial editor doesn't update the prop for a child component

### ISSUE THREAD

**Issue by VG08** [vuejs/docs#1714]
### Steps to reproduce:
1) Open the tutorial - https://vuejs.org/tutorial
2) replace the code with - [this code](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDaGlsZENvbXAgZnJvbSAnLi9DaGlsZENvbXAudnVlJ1xuY29uc3QgcHIgPSByZWYoXCJcIilcbmNvbnN0IGNoaWxkTXNnID0gcmVmKCdObyBjaGlsZCBtc2cgeWV0JylcbmZ1bmN0aW9uIHNldFByb3AoKXtcbiAgcHIudmFsdWUgPSBcIm1zZ1wiXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8Q2hpbGRDb21wIEByZXNwb25zZT1cIihtc2cpPT4gY2hpbGRNc2cgPSBtc2dcIiA6bT1cInByXCIvPlxuICA8cD57eyBjaGlsZE1zZyB9fTwvcD5cbiAgPGJ1dHRvbiBAY2xpY2s9XCJzZXRQcm9wXCI+XG4gICAgR2V0IG1lc3NhZ2VcbiAgPC9idXR0b24+XG4gIDxwPlxuICAgIHt7cHJ9fVxuICA8L3A+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJDaGlsZENvbXAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmNvbnN0IGVtaXQgPSBkZWZpbmVFbWl0cyhbJ3Jlc3BvbnNlJ10pXG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzKFsnbSddKVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDI+e3twcm9wc319PC9oMj5cbjwvdGVtcGxhdGU+In0=
)
3) click the "Get messages" button

### Expected behaviour:
The { "m": "" } changes to { "m": "msg" } as the value of the pr variable was updated to "msg"
### What actually happens:
The { "m": "" } remains the same

**Comment by skirtles-code** [comment]
The docs REPL got updated to the same version as the SFC Playground a few days ago, which may have fixed this.
