### ISSUE TITLE
Reactivity docs question

### ISSUE THREAD

**Issue by MrBrN197** [vuejs/docs#1716]
I'm looking at the reactivity section of the docs and on the `trigger` function  on this line

https://github.com/vuejs/docs/blob/6fa4ba40e2583d130438be90dffecebf7d770f9a/src/guide/extras/reactivity-in-depth.md?plain=1#L79-L82

the `trigger` function is run before the `target[key] = value`. shouldn't this be the other way around? shouldn't the "effects" run with the updated ref value instead of the value it had before the `set` call?

**Comment by skirtles-code** [comment]
I think you're right. It's only pseudo-code but having the call to `trigger` come second does seem more natural.
