### ISSUE TITLE
TransitionGroup documentation for staggering animations should either specify 3rd party library used and provide vanilla example

### ISSUE THREAD

**Issue by alecStewart1** [vuejs/docs#1750]
In [TransitionGroup's Staggering List Transitions](https://vuejs.org/guide/built-ins/transition-group.html#staggering-list-transitions) the following example is used:

```javascript
function onEnter(el, done) {
  gsap.to(el, {
    opacity: 1,
    height: '1.6em',
    delay: el.dataset.index * 0.15,
    onComplete: done
  })
}
```

I understand that in the above example in the documentation and in the example's playground [GSAP](https://greensock.com/gsap/) is used. However it should be specified that 3rd party library is being used and an example using vanilla Javascript (probably using [`HTMLElement.style`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) and maybe even [`Element.animate`](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate)) should be provided.

**Comment by skirtles-code** [comment]
I've added a note about the use of GreenSock in #1772.

I'm not sure having a vanilla JS example would add anything here. The example doesn't need the reader to have prior experience of `gsap`, it's fairly self-explanatory what it's doing. Using `gsap` keeps the example concise, without the distraction of lots of animation code. If we can achieve the same thing without using `gsap` then I'd be all for replacing that example, but I'm not sure we can.

**Comment by skirtles-code** [comment]
> > If we can achieve the same thing without using `gsap` then I'd be all for replacing that example, but I'm not sure we can.
> 
> If it can be done with `gsap` then it can be done without it.

Understood, but I had intended my comment to refer specifically to the conciseness and clarity of the example. I hadn't meant to suggest that it isn't technically possible to achieve the functionality without `gsap`.

The primary objective of the documentation is to teach people about Vue. I think the existing example does that just fine. I would rather avoid using third-party libraries if possible, but it shouldn't be at the expense of making the examples harder to understand. I don't currently see a way to retain the clarity of the example without using a library.
