### ISSUE TITLE
`@vue:*` hooks missing in new documentation

### ISSUE THREAD

**Issue by DrJume** [vuejs/docs#1760]
I could not find any references on documentation pages to the very practical `@vnode-*` hooks.

Currently they are only explained in the migration guide, but sadly they are outdated and shown in the old `@vue:*` format. https://v3-migration.vuejs.org/breaking-changes/vnode-lifecycle-events.html

**Comment by liulinboyi** [comment]
The `@vnodeXXX` usage will be deprecated.

![image](https://user-images.githubusercontent.com/41336612/172682742-a405ee48-d906-4ddd-b9b4-4d5a148fc2b3.png)

**Comment by DrJume** [comment]
Oh ok... I thought only the `@vue:*` notation will be deprecated.

What will be the alternative to `@vnode-*`?

**Comment by DrJume** [comment]
Are you sure this isn't a typo? 
Why would a deprecation of the whole `@vnode-*` feature be placed above compatibility check for the old deprecated? `@vue:*` notation?

**Comment by skirtles-code** [comment]
`@vue:` is the new syntax, introduced in [3.2.25](https://github.com/vuejs/core/blob/main/CHANGELOG.md#3225-2021-12-12). The migration guide originally mentioned `@vnode-` but it was changed once `@vue:` was added.

**Comment by DrJume** [comment]
Thank you for clarifying! 😃

**Comment by NataliaTepluhina** [comment]
From what I recall, the usage of `@vue:` hooks is not encouraged and we didn't document them intentionally.

**Comment by renatodeleao** [comment]
A bit late comment, but I am curious why is the usage not encouraged? The alternative is adding at least 3 boilerplate-ish lines of code for achieving the same result which is not as DX-friendly.

```js
import { onMounted } from 'vue'

const emit =  defineEmits(['mounted'])

onMounted(() => emit('mounted'))
```

**Comment by KaelWD** [comment]
onMounted also doesn't always work if you're using it to access an element inside another component

```html
<template>
  <Component>
    <div ref="el" />
  </Component>
</template>

<script setup>
  const el = ref()
  onMounted(() => {
    el.value
  })
</script>
```
If Component doesn't render its default slot immediately then el.value will still be undefined, with vnode events you can just put `@vue:mounted` on the div instead of onMounted.
