### ISSUE TITLE
The "/tutorial" route breaks the back button

### ISSUE THREAD

**Issue by orenelbaum** [vuejs/docs#1768]
The /tutorial route (https://vuejs.org/tutorial/) breaks the back button. It happens because it redirects automatically to /tutorial/#step-1 without replacing the history entry.
This link is used on the introduction page so this issue should probably be prioritized.

**Comment by orenelbaum** [comment]
#1769

**Comment by NataliaTepluhina** [comment]
Closing because the PR with the fix was merged
