### ISSUE TITLE
The Lighthouse audit link in FAQ is broken

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs#1773]
- Page: https://vuejs.org/about/faq.html#is-vue-fast
- Link: [Lighthouse audit](https://www.webpagetest.org/result/210818_BiDcYB_4a83d7a1f2a7f6fdc76db16a00b4882d/)
- URL: https://www.webpagetest.org/result/210818_BiDcYB_4a83d7a1f2a7f6fdc76db16a00b4882d/

<img width="721" alt="image" src="https://user-images.githubusercontent.com/206848/173219771-ad62c804-a54c-42da-93d6-3f12fa8eeb49.png">

Not sure where this link comes from, seems broken already.

**Comment by NataliaTepluhina** [comment]
@yyx990803 do you remember which page was undergoing Lighthouse audit here?
