### ISSUE TITLE
Unable to report missing search result

### ISSUE THREAD

**Issue by entioentio** [vuejs/docs#1775]
I wanted to report a missing docs item (see printscreen) and got redirect to the page (URL below) which shown 404 on github.
![image](https://user-images.githubusercontent.com/10046841/173603863-378a737c-be26-40a5-8bb1-bf897581105c.png)

`https://github.com/algolia/docsearch-configs/issues/new?template=Missing_results.md&title=[vuejs]+Missing+results+for+query+%22getCurrentInstance%22`

I believe that algolia has undergone some major restructuring and their API works differently now. Maybe a link should be updated? Or perhaps this is algolia's issue?

**Comment by skirtles-code** [comment]
From a quick initial investigation, it looks like the 'Let us know' link is coming from `@docsearch/js`, which is being used via `@vue/theme`.

**Comment by yyx990803** [comment]
`getCurrentInstance` is intentionally undocumented in the latest version of the docs, due to how it's been incorrectly used. It was a mistake documenting it as public API in the previous version of v3 docs.
