### ISSUE TITLE
Misplaced text in header

### ISSUE THREAD

**Issue by iSonce** [vuejs/docs#1776]
I want to view the document on another screen with a smaller width, but when the width is between about 775px and 875px, the Chinese text doesn't display correctly.
![bug](https://user-images.githubusercontent.com/57745505/173621869-c1df0a3f-b9f7-4d5e-9f5a-fa9a93b7a3de.png)

**Comment by yyx990803** [comment]
https://github.com/vuejs/theme/commit/0db8cb4daeef05ddaa6bbd555116b68786005142
