### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by cloudmoonocus** [vuejs/docs#1796]
**Click on the sponsor on the right, jump to the vue document when click the vue school.**

**Comment by Irving2020** [comment]
Are you picking on me ?

**Comment by cloudmoonocus** [comment]
> 你在挑剔我吗？

what？

**Comment by Irving2020** [comment]
That's normal for your description

**Comment by cloudmoonocus** [comment]
> That's normal for your description
But it's not normal to click in my browser

**Comment by cloudmoonocus** [comment]
> That's normal for your description

But it's not normal to click in my browser

**Comment by LinusBorg** [comment]
Well, what's your browser? Also, please test in private mode without any extensions active. Works fine for me in latest Chrome, FF, Brave, Safari and Edge

**Comment by cloudmoonocus** [comment]
It is no problem in private mode. I think it may be a browser extension problem. But there is no major problem, thanks for the reminder.
