### ISSUE TITLE
*.vuejs.org SSL to expire on 2022.6.26

### ISSUE THREAD

**Issue by persiliao** [vuejs/docs#1800]
rt

**Comment by skirtles-code** [comment]
Where are you seeing this? The certificate I see for <https://vuejs.org/> isn't due to expire for months.

**Comment by persiliao** [comment]
@skirtles-code https://staging-cn.vuejs.org/

**Comment by persiliao** [comment]
I use Chrome to see

*.vuejs.org
Issued by: R3
Expired: Sunday, June 26, 2022 at 08:21:21 China Standard Time

**Comment by xfq** [comment]
Perhaps it has been renewed?

FWIW, this is what I see for `*.vuejs.org`:

<img width="485" alt="vue1" src="https://user-images.githubusercontent.com/2863444/175797687-a162073b-9bda-4e86-949d-860dcec6e869.png">

-----

And for `vuejs.org`:

<img width="495" alt="vue2" src="https://user-images.githubusercontent.com/2863444/175797692-880ecc46-d7e0-4f44-bf29-dee4feae91d0.png">

**Comment by yyx990803** [comment]
fixed
