### ISSUE TITLE
Passing plugin options

### ISSUE THREAD

**Issue by uuf6429** [vuejs/docs#1806]
This is more of a support request, but also a suggestion on the documentation..

There's a whole section mentioning plugin options on each code sample, but nowhere does it says where the options come from:
- https://vuejs.org/guide/reusability/plugins.html
- https://github.com/vuejs/docs/edit/main/src/guide/reusability/plugins.md

As far as I could see, this is not even mentioned anywhere else.

----

On a different note, unfortunately, it feels that the documentation is written in a way where there is the assumption that readers are deeply familiar with how everything works and want to know more about what changed or specific topics, which is typically not the case.

**Comment by skirtles-code** [comment]
I'm going to close this.

It isn't clear what is being requested here, as the material does appear to be present in the existing documentation.
