### ISSUE TITLE
Confusing note for IME and v-model

### ISSUE THREAD

**Issue by leyiang** [vuejs/docs#1813]
Guide -> Essentials -> Form Input Bindings

In the #basic-usage section, there is a note for IME:

> ::: tip Note
For languages that require an [IME](https://en.wikipedia.org/wiki/Input_method) (Chinese, Japanese, Korean etc.), you'll notice that `v-model` doesn't get updated during IME composition. If you want to respond to these updates as well, use an `input` event listener and `value` binding instead of using `v-model`.
:::

It says that If we want to get updated duing IME composition, we need to use `input` event instaed of `v-model`.
So I think, ok, maybe `v-model` is using the `change` event.

But when I come to the modifiers.lazy section, it says:

> By default, `v-model` syncs the input with the data after each `input` event (with the exception of IME composition as [stated above](#vmodel-ime-tip)). You can add the `lazy` modifier to instead sync after `change` events:

So `v-model` is using input by default. Which is confusing because I tried the `input` event for IME composition, and it works as expected. Why is `v-model`'s `input` event not updating during IME composition?  I found the answer inside the source code:
```js
e => {
    if (e.target.composing)
        return;
    let domValue = el.value;
    if (trim) {
        domValue = domValue.trim();
    }
    if (castToNumber) {
        domValue = toNumber(domValue);
    }
    el._assign(domValue);
}
```
Vue prevent the IME composition update inside the `input` event.

I was wondering if there should be some modification to the note for IME? Maybe it can shorten the understanding time for future readers?

**Comment by NataliaTepluhina** [comment]
@leyiang thank you for reporting the issue! Yes, it seems we can update the docs for IME. Would you like to create a pull request for this or would you prefer if it's created by the docs team? Either way is fine 😅

**Comment by leyiang** [comment]
@NataliaTepluhina Hi, I just created a pull request at #1827. I think change `Use an input event` to `Use your own input event` can eliminate the confusion that `v-model` is not using `input` event. What do you think?
