### ISSUE TITLE
Profile picture is not reflecting correctly on sponsor page

### ISSUE THREAD

**Issue by hello-addweb** [vuejs/docs#1815]
Hello Team,

I recently changed my company logo but it is not reflected on the sponsor page as it is still showing me my old company logo. 
It would be really helpful if you can help me out with issue.

**Comment by skirtles-code** [comment]
It looks like the image in the docs was updated on July 8th. Could you confirm that this is now using the correct image so we can close this issue? Thanks.

**Comment by hello-addweb** [comment]
No it is still not updated in the sponsor page still showing the old image.

**Comment by NataliaTepluhina** [comment]
@hello-addweb does it also show old logo in incognito mode?

**Comment by hello-addweb** [comment]
No it's showing new logo in incognito mode

**Comment by yyx990803** [comment]
It's due to strong cache headers. I've added cache busting param now.
