### ISSUE TITLE
Can I use vue3 library component in existing vue2 project

### ISSUE THREAD

**Issue by shwetasharma06** [vuejs/docs#1818]
I have an existing project which is now on vue2. Now I have moved my ui-components library  from vue2 to vue3. But when I am creating build of my library and importing that in my vue2 project then yarn start is getting error "Module not found: Error: Can't resolve". Is it because My project and library vue versions are different?

Please someone guide me

**Comment by skirtles-code** [comment]
This issues list is for reporting problems with the documentation.

Please use [the Vue Discord server](https://chat.vuejs.com/) for help questions. Thanks.

**Comment by xfq** [comment]
FWIW, [chat.vuejs.com is down](https://downforeveryoneorjustme.com/chat.vuejs.com) now.

https://discord.com/invite/HBherRA works for me.

**Comment by skirtles-code** [comment]
Sorry, there was a typo in the URL I posted. Should have been `.org`.
