### ISSUE TITLE
Quickstart should be removed and replaced with multiple sections

### ISSUE THREAD

**Issue by aldencolerain** [vuejs/docs#1820]
I have found when helping people get started with Vue that the Quickstart page is very confusing for beginners and that its not "quick" for a beginner.  It would be more user friendly to separated this into multiple sections.

A few issues stand out to me.  Currently the Quickstart page mentions a lot of disparate concepts like import maps, serving static files, Vite, ES modules, vue cli, etc that don't belong in a quick start. The first sentence "Depending on your use case and preference, you can use Vue with or without a build step." is confusing for beginners that may not understand the concept.  The Quickstart page is written using the Composition API but the rest of the docs default to the more beginner friendly Options API.  Also, people may skip the Introduction because they see the words "Quickstart".

Something like this would be better:
- **Try Vue**
  A beginner friendly way to get a positive taste for Vue after reading the introduction.  It could be a demo of the power of view, perhaps bring back an embedded try it widget for this page only so they can try in their browser (StackBlitz).
- **Creating a Vue Application** or **Installation**
  Quick instructions for people who want to create a SPA. Installation instructions for people familiar with SPAs coming from Vue2, React, Angular, etc
- **Using Vue in Static HTML**
  Instructions for those wanting to use Vue without building: static sites, legacy sites, etc.

**Comment by awxiaoxian2020** [comment]
I agree.
