### ISSUE TITLE
The sponsors information on the homepage are still hard coded

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs#1830]
I think we need a way to dynamically load sponsors' data properly.

https://github.com/vuejs/docs/blob/5281fd3f345bed7dbbd1f344b73b0a2699de885f/.vitepress/theme/components/Home.vue#L38

**Comment by skirtles-code** [comment]
Fixed by #1830.

**Comment by Jinjiang** [comment]
Should be #1838 instead I think. Not a big deal anyway. 😅
