### ISSUE TITLE
Add more prerequisites for beginners

### ISSUE THREAD

**Issue by awxiaoxian2020** [vuejs/docs#1837]
> The rest of the documentation assumes basic familiarity with HTML, CSS and JavaScript. If you are totally new to frontend development, it might not be the best idea to jump right into a framework as your first step - grasp the basics and then come back! Prior experience with other frameworks helps, but is not required.

`basic familiarity with HTML, CSS and JavaScript` is a vague description. we can list some points and give some MDN resources for beginners.

**Comment by NataliaTepluhina** [comment]
@awxiaoxian2020 would a link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript be a good addition? I don't think we need to enlist all the things people need to know but we can squeeze this link (or any other one if you have a better idea) in a sentence after `basic familiarity` one

**Comment by awxiaoxian2020** [comment]
> 

My point is what you said.
