### ISSUE TITLE
Add Node.js Version Requirements

### ISSUE THREAD

**Issue by salamander77712** [vuejs/docs#1839]
The "Quick Start" in the "Getting Started" sections lists Node.js as a perquisite for running Vue locally, however, the required version of Node.js isn't listed. This is an issue because Vite uses `node:` import, which isn't support on v15 of Node.js, resulting in errors when attempting to run `npm run dev` or `npm run build`.

**Comment by NataliaTepluhina** [comment]
@salamander77712 thank you! Updated the Node requirement with v15 or higher
