### ISSUE TITLE
Change Style Guide for Vue3 API.

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/docs#184]
The current style guide has sections that use the old API.
I want to change the documentation using the new APIs available in the Vue.js 3.
Specifically, I think the following changes are necessary.

- `Component/instance options order` Section
  - Remove **Side Effects** category
    - Remove `el` option
  - Change **Global Awareness** category
    - Remove `parent` option
  - Remove **Component Type** category
    - Remove `functional` option
  - Remove **Template Modifiers** category
    - Remove `delimiters` option
    - Remove `comments` option
  - Change **Template Dependencies** category
    - Remove `filters` option
  - Change **Composition** category
    - Add `provide`/ `inject` option
  - Change **Interface** category
    - Remove `model` option
    - Remove `propsData` option
    - Add `emits` option
  - Add **Composition API** category
    - Add `setup` option
  - Change **Events** category > Lifecycle Events
    - Replace `beforeDestroy` to `beforeUnmount`
    - Replace `destroyed` to `unmounted`
    - Add `errorCaptured` to Lifecycle Events
    - Add `renderTracked` to Lifecycle Events
    - Add `renderTriggered` to Lifecycle Events
  - Change **Rendering** category
    - Remove `renderError` option
- `Non-flux state management` Section
  - Replace use of `$on` to use `mitt`.
  - Replace use of `Vue.createApp` to use `import {createApp} from 'vue'`

**Comment by qgates** [comment]
@ota-meshi is there a method for specifying custom `delimiters` in Vue 3? Can't find any reference to it in the docs. TIA

**Comment by ota-meshi** [comment]
@qgates I'm not familiar with it because I'm not using it, but I think you can probably specify it with a parser/compile option. I'm not sure where to specify it in your build system.

https://github.com/vuejs/vue-next/blob/64e2f4643602c5980361e66674141e61ba60ef70/packages/compiler-core/src/parse.ts#L45

**Comment by qgates** [comment]
@ota-meshi Thanks for your reply, I did find that in the source 😉 Just not sure what/where to configure. I'm using webpack, care to point me in the right direction? Many thanks again 🙂
