### ISSUE TITLE
Missing search result for computed

### ISSUE THREAD

**Issue by navid074** [vuejs/docs#1840]

**Comment by xfq** [comment]
Which page are you looking for?

-----

This is what I saw:

<img width="1680" alt="computed" src="https://user-images.githubusercontent.com/2863444/179964553-472cdca5-ea62-4975-86dc-384678782992.png">

**Comment by NataliaTepluhina** [comment]
Just like @xfq I cannot reproduce the issue. Searching for `computed` returns the same results as on the screenshot.
