### ISSUE TITLE
"Usage Restrictions" confuses me

### ISSUE THREAD

**Issue by jasonjiwork** [vuejs/docs#1841]
The following is the original text:

> Composables should only be called synchronously in <script setup> or the setup() hook. In some cases, you can also call them in lifecycle hooks like onMounted().
> 
> These are the contexts where Vue is able to determine the current active component instance. Access to an active component instance is necessary so that:
> 
> Lifecycle hooks can be registered to it.
> 
> Computed properties and watchers can be linked to it for disposal on component unmount.
> 
> TIP
> 
> <script setup> is the only place where you can call composables after usage of await. The compiler automatically restores the active instance context after the async operation for you.

I think this information is important, but it's too abbreviated.
It's easy misunderstanding it. Can we add some code examples?
It seems the first sentence and sentence in Tip are contradictory.

**Comment by jasonjiwork** [comment]
Very disappointed. My question has been filed for five days. No response.
It seems Vue core team is not that high efficiency.

**Comment by skirtles-code** [comment]
Thank you for your suggestion.

Unless I'm missing something it doesn't appear to be urgent. I'm unclear why you expect it to be dealt with within 5 days. This is an open source project and the people working on it are volunteers.

**Comment by jasonjiwork** [comment]
Sorry for my reckless comment!
Vue helps me a lot. Thank you for your greate job.
I just want it to be better.
