### ISSUE TITLE
透传Attribute文档看不了

### ISSUE THREAD

**Issue by killervillsy** [vuejs/docs#1848]
![image](https://user-images.githubusercontent.com/68230308/180347115-22f43bbc-1269-48df-a4e9-0b9e0959d7ce.png)

**Comment by xfq** [comment]
I can't reproduce the problem (for both English and Chinese docs):

<img width="1680" alt="en" src="https://user-images.githubusercontent.com/2863444/180447651-8ec97302-78a0-43fc-aba3-55c52bfd1252.png">
<img width="1680" alt="zh" src="https://user-images.githubusercontent.com/2863444/180447685-230ed55b-7b4e-419e-a2c7-a01a17235d5b.png">

**Comment by killervillsy** [comment]
Unbelievable! I was pretty sure I couldn't open this document yesterday as well as this morning, but now it's back to normal.
![image](https://user-images.githubusercontent.com/68230308/180451518-528006f1-a0d9-4d22-941b-866ff68b85aa.png)
