### ISSUE TITLE
In the directive hook documentation arguments are missing

### ISSUE THREAD

**Issue by crystalfp** [vuejs/docs#1861]
In the https://vuejs.org/guide/reusability/custom-directives.html page, in the Directive Hooks section, in the code example only the `created()` hook has the arguments show, the other seems to accept no arguments. In my opinion, it is clear if the `el, binding, vnode, prevVnode` arguments are added to all the hooks, or at least put a `...` to signify there are arguments that are not repeated.

**Comment by Ashebir07** [comment]
In the https://vuejs.org/guide/reusability/custom-directives.html page, in the Directive Hooks section, in the code example only the created() hook has the arguments show, the other seems to accept no arguments. In my opinion,it should not install all the necessary dependenacies.

**Comment by NataliaTepluhina** [comment]
@crystalfp thank you! Makes sense, added arguments to all hooks. It looks a bit repetitive but definitely more explicit than skipping arguments altogether
