### ISSUE TITLE
Step 2, Options API, in the tutorial

### ISSUE THREAD

**Issue by 3-2** [vuejs/docs#1865]
[The tutorial](https://vuejs.org/tutorial/#step-2) says 'In the example code, the object being passed to createApp() is a component.' However, there is no such code  including 'createApp()'.
![telegram-cloud-photo-size-5-6271819732101476396-y](https://user-images.githubusercontent.com/25643218/181244233-0d14d3e4-fbfb-4684-963c-8755d983abbe.jpg)

**Comment by NataliaTepluhina** [comment]
Thank you! This was a leftover from HTML templates, not SFC. Removed it from the SFC description.
