### ISSUE TITLE
"the component" is not clear in emits docs

### ISSUE THREAD

**Issue by ITwrx** [vuejs/docs#1888]
It would be nice if [declaring-emitted-events](https://vuejs.org/guide/components/events.html#declaring-emitted-events) said to define the emits on "the child component" or "the component which emits the event" instead of just "the component", as "the component" could be misinterpreted as "the parent component" or "the listening component".  

Thanks

**Comment by NataliaTepluhina** [comment]
@ITwrx unfortunately, saying `emitted events can be explicitly declared on the component` is equally confusing, and `mitted events can be explicitly declared on the component which emits the event` sounds very repetitive so I wouldn't go with this phrasing. Maybe you have some other ideas on how to make the description more readable?

**Comment by ITwrx** [comment]
in this case, i might would say `events can be explicitly declared on the emitting component`. I believe `emitted` in the beginning of  `emitted events can be explicitly declared on the component` to be superfluous, and past tense is less than ideal when describing the declaration of events which have yet to be emitted.
