### ISSUE TITLE
哪个才是你们vue3的官方网站？

### ISSUE THREAD

**Issue by git136975643** [vuejs/docs#1900]
官网是 https://vuejs.org 还是 https://cn.vuejs.org ？

以下路径404(首页文档菜单下的2个子菜单)：
https://vuejs.org/examples/
https://vuejs.org/tutorial/

**Comment by git136975643** [comment]
气气气，又显示出来了，无语。刚才一段时间访问页面显示文字说是死链接

**Comment by yyx990803** [comment]
一个是英文版一个是中文版，都是官方的。
