### ISSUE TITLE
A translation error in Chinese doc | 中文文档中的错别字

### ISSUE THREAD

**Issue by VincentSHI1230** [vuejs/docs#1908]
文档 https://cn.vuejs.org/about/faq.html#should-i-use-javascript-or-typescript-with-vue 处
> 在向 Vue 添加新特性时，对 TypeScript ~~对~~支持是一个重要的考虑因素。

这似乎是一个错别字——
> 在向 Vue 添加新特性时，对 TypeScript **的**支持是一个重要的考虑因素。

**Comment by xfq** [comment]
Fixed in https://github.com/vuejs-translations/docs-zh-cn/pull/505
