### ISSUE TITLE
The render function cannot be executed again

### ISSUE THREAD

**Issue by zqq-nuli** [vuejs/docs#1918]
When I tried to use the render function to call my component several times, I found that I used the remove method of JavaScript to delete the DOM, but I could not call the function again to make the DOM appear. However, I did not find any API to delete the DOM or delete it in memory

**Comment by skirtles-code** [comment]
I'm unclear what problem is being described here.

This issues list is for reporting problems with the Vue 3 documentation.

I suggest asking for help on the [Vue Discord](https://chat.vuejs.org/) if you are still having a problem.
