### ISSUE TITLE
Is there a mistake in the statement about script in the document? 文档中关于 script 的说法是不是有错误?

### ISSUE THREAD

**Issue by you-hengh** [vuejs/docs#1923]
网址在这里:https://vuejs.org/api/sfc-spec.html#script
实际上 vue3 允许多个 script 在一个 vue 文件中,但文章是这么写的:
> Each *.vue file can contain at most one <script> block at a time (excluding [<script setup>](https://vuejs.org/api/sfc-script-setup.html)).

所以我认为文档的说明是不是错误的? 如果真的是错误的, 还希望能修正文档(同时修正中文文档),谢谢!

---
The url is here:https://vuejs.org/api/sfc-spec.html#script
Vue3 actually allows multiple script in one vue file, but here's what the article says:
> Each *.vue file can contain at most one <script> block at a time (excluding [<script setup>](https://vuejs.org/api/sfc-script-setup.html)).

So do I think the description of the document is wrong? If it is really wrong, I also hope to correct the document (and modify the Chinese document at the same time), thank you!

**Comment by NataliaTepluhina** [comment]
@you-hengh there is no mistake. Vue allows only one `<script>` block in SFC (and one `<script setup>` as mentioned in the doc). If you try to put more than one `<script>`, it will result in the compiler error:
`VueCompilerError: Single file component can contain only one <script> element`
