### ISSUE TITLE
No link to vue3 script

### ISSUE THREAD

**Issue by slim-codes** [vuejs/docs#1947]
The Vue tutorial in MDN is based on version 2. I was trying to update the script tags on the first page of the [Vue tutorial](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started) to version 3 today. However, I was unable to find any link to a script in the current documentation of Vue. I have searched throughout the official documentation and I haven't seen any. I have attached the images below for more clarity.
The documentation website for Vue 2 on the other hand has two links for optimized and unoptimized scripts.
![Screenshot from 2022-09-05 22-20-26](https://user-images.githubusercontent.com/72257135/188514035-5bbaf30a-9f7b-429b-8cd8-483209f93fad.png)

I expected to see a link under the `Standalone` script heading. I have looked all over the website but I can't find any. This heading is irrelevant if it doesn't detail how to use or get the script. It only mentions that Vue can be used as a script. But where is the said script?

![Screenshot from 2022-09-05 22-38-11](https://user-images.githubusercontent.com/72257135/188514521-ac7730b1-cede-4e8e-8e47-d814357a22f5.png)

As you can see, the links in MDN are for Vue 2 and I want to update them to Vue 3. Where can I obtain the official links to the scripts for Vue 3?

![Screenshot from 2022-09-05 22-45-42](https://user-images.githubusercontent.com/72257135/188514985-2d322316-0161-4477-b09d-c494559a5918.png)
Vue 2 website with the 2 scripts available for download

**Comment by skirtles-code** [comment]
I think the information you need can be found in the following two sections:
* <https://vuejs.org/guide/quick-start.html#without-build-tools>
* <https://vuejs.org/guide/best-practices/production-deployment.html#without-build-tools>

There aren't really 'official links' to the files. They're released to the npm registry, so any CDN that reflects the contents of the registry should have the relevant files.

**Comment by slim-codes** [comment]
Alright!
Thanks for the feedback
