### ISSUE TITLE
Sponsor gray/color change is jumpy

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/docs#195]
1. The color change only happens when the top of the sponsor block intersects with viewport top. I scrolled back and forth for a while wondering why they were in grayscale
2. The transition is really quick so it feels jumpy

**Comment by gtsiolis** [comment]
@JessicaSachs I think the color filter is triggered _exactly_ at the same point as seen in the existing docs. See [old](https://github.com/vuejs/vuejs.org/blob/bdf1a2adea5b5d5990b3098c38c05c4ce47da605/themes/vue/layout/index.ejs#L173) v. [new](https://github.com/vuejs/docs-next/blob/be972f06e57ab665fe50f951a5753d8899226e68/src/.vuepress/theme/components/Home.vue#L117).

**Question:** Would you expect the transition to take place sooner when you scroll down?

FWIW, I also find this behavior jumpy.

**Suggestion:** Maybe we could just persist the filter (grayscale) and remove the filter only on hover?

**Comment by skirtles-code** [comment]
There was a bug that *could* cause the transition to occur at the wrong point, though it only happened in specific circumstances. That should now be fixed. The transition should occur when the sponsors block is 100px below the top of the viewport:

![sponsors](https://user-images.githubusercontent.com/65301168/105606488-a8e2a980-5d91-11eb-8cc2-d456db05a3cf.png)

While this is the same threshold used in the Vue 2 docs, the layouts of the pages are not the same, so the effect does feel slightly different. Whether there's enough of a difference to justify changing anything I'm not sure. If I've understood correctly then what @JessicaSachs observed was the transition happening in the wrong place.

**Comment by NataliaTepluhina** [comment]
Closing as we have switched to new docs and this bug is not relevant anymore
