### ISSUE TITLE
How often do the docs deploy?

### ISSUE THREAD

**Issue by awxiaoxian2020** [vuejs/docs#1958]
I found the latest is in Jan. Is it out-of-date?

**Comment by brc-dd** [comment]
That GitHub deployment thing doesn't reflect the Netlify deploys. The docs are deployed on each commit.

**Comment by awxiaoxian2020** [comment]
Actually，I found https://vuejs.org/guide/essentials/reactivity-fundamentals.html seems not to sync with https://github.com/vuejs/docs/blob/main/src/guide/essentials/reactivity-fundamentals.md

Am I understanding something wrong?

**Comment by LinusBorg** [comment]
How are they not in sync?

**Comment by awxiaoxian2020** [comment]
> How/where are they not in sync?

where is the img in github source code?
![11111](https://user-images.githubusercontent.com/69554233/190176163-2f74d60f-7440-4308-b3f0-cee64c4d2c06.png)

**Comment by brc-dd** [comment]
Just FYI: If a heading ends with `**` in the markdown file, it's composition API only and if it ends with `*` then its options API only. So, if that's what you were referring to, then change the API preference in left sidebar.

**Comment by brc-dd** [comment]
> where is the img in github source code?

https://github.com/vuejs/docs/blob/b2d3a52f63e293168037afdaaf4ef3af37373899/src/guide/essentials/reactivity-fundamentals.md?plain=1#L78

**Comment by awxiaoxian2020** [comment]
> > where is the img in github source code?
> 
> https://github.com/vuejs/docs/blob/b2d3a52f63e293168037afdaaf4ef3af37373899/src/guide/essentials/reactivity-fundamentals.md?plain=1#L78

Thanks! Sorry for my fault.
