### ISSUE TITLE
Use Options API/Composition API for introduction

### ISSUE THREAD

**Issue by awxiaoxian2020** [vuejs/docs#1959]
https://github.com/vuejs/docs/blob/b2d3a52f63e293168037afdaaf4ef3af37373899/src/guide/introduction.md?plain=1#L32-L50

**Comment by LinusBorg** [comment]
We already explain both just a bit further down the page, and I don't think it makes sense to present both versions before we have explained that fact.

**Comment by awxiaoxian2020** [comment]
@LinusBorg 
Even so, why not default the example to the Composition API? I personally think it's more concise and makes beginners feel the charm of the Vue framework. While this is indeed a bit subjective, it is also an option.
