### ISSUE TITLE
Tutorial-Computed Property Demo code error

### ISSUE THREAD

**Issue by gongqx** [vuejs/docs#1960]
Tutorial-Computed Property Demo code error
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/43650076/190300627-4609c121-22a2-47c4-9f71-c426fd161ef1.png">

**line**:https://vuejs.org/tutorial/#step-8

**Comment by NataliaTepluhina** [comment]
@gongqx Thank you for reporting the bug! Fixed in https://github.com/vuejs/docs/commit/f25e283bae1a46da9923646bc6e9b4aeaaeb7b2b
