### ISSUE TITLE
runtime-core.esm-bundler.js:7318 Uncaught (in promise) TypeError: parentComponent.ctx.deactivate is not a function

### ISSUE THREAD

**Issue by yiaokan** [vuejs/docs#1971]
这个问题是出现在使用Suspense结合RouterVIew、KeepAlive时出现的情况。我发现官方文档中推荐的suspense和其他组件嵌套使用时的顺讯是错误的。地址：https://cn.vuejs.org/guide/built-ins/suspense.html#error-handling
官方文档的使用顺序是这样：
![image](https://user-images.githubusercontent.com/92811770/192104644-b7e2bde4-d9a8-497e-a1ec-f29cd4e792c2.png)

通过测试之后发现正确的顺序应该是这样：
![image](https://user-images.githubusercontent.com/92811770/192104669-efaff0bd-14cd-4c55-a9a0-3110e852fdf4.png)

**Comment by skirtles-code** [comment]
I believe what's shown in the docs is correct. What you're seeing might be a core bug: <https://github.com/vuejs/core/issues/6222>.

Putting the `<KeepAlive>` outside the `<RouterView>` might prevent the error message, but it won't actually be doing any keep-alive.
