### ISSUE TITLE
createVNode问题

### ISSUE THREAD

**Issue by nianzx** [vuejs/docs#1981]
使用
`const vm1 = createVNode({
      template:`<Test></Test>`,
      components:{
        Test
      }
    });
    render(vm1, div);`

**Comment by nianzx** [comment]
使用上述代码在开发环境中能正常渲染出来，打包后无法正确挂载

**Comment by nianzx** [comment]
const vm1 = createVNode({
      template:`<Test></Test>`,
      components:{
        Test
      }
    });
    render(vm1, div);

**Comment by NataliaTepluhina** [comment]
@nianzx the issue you have is not very clear. I assume you're using a build step (Vite?) and the code doesn't work after the build? If so, I would create an issue in the build tool repository.

**Comment by skirtles-code** [comment]
I'm going to close this. I don't believe there's a problem with the documentation, but we can re-open this issue if I've misunderstood.

**Comment by nianzx** [comment]
@NataliaTepluhina Yes. Use the above code doesn't work after the build.
