### ISSUE TITLE
Add english anchors

### ISSUE THREAD

**Issue by KeziahMoselle** [vuejs/docs#1998]
As stated in https://github.com/vuejs-translations/guidelines#retaining-original-anchors, translated versions of the repo need to add the original english anchors.
But this takes time to add for each translation. I think it would be great to have those anchors in the source repo so they are already ready to go when we are translating.

What do you think?

**Comment by yyx990803** [comment]
This is a good point.

Manually doing this is quite a bit of work though, maybe we can write an automated script to copy them from the [Chinese docs](https://github.com/vuejs-translations/docs-zh-cn) back to the English docs.

/cc @Jinjiang

**Comment by wxsms** [comment]
I've created a PR for this.
