### ISSUE TITLE
vue3文档路由篇章错别字

### ISSUE THREAD

**Issue by wudafei01** [vuejs/docs#2022]
![image](https://user-images.githubusercontent.com/70732213/195975316-74cefae0-0232-480d-b5c2-cf76bf9fbea4.png)
此处文字可能应为：是。

**Comment by skirtles-code** [comment]
Please could you open an issue at <https://github.com/vuejs-translations/docs-zh-cn/issues> instead? I tried to transfer this issue across but GitHub won't let me. Thanks.

**Comment by wudafei01** [comment]
新的issue：https://github.com/vuejs-translations/docs-zh-cn/issues/579
