### ISSUE TITLE
Should add a link to production deployment doc

### ISSUE THREAD

**Issue by aklipfel** [vuejs/docs#2041]
# The Problem
While translating `production-deployment.md` file in French, I came across "Reactivity debugging" that was tricky to translate because this concept was not clear to me and had to look for it on the internet to find the corresponding article.

## Proposed Solution
I would suggest to add a link to the Reactivity Debugging doc, for users that didn't know about this concept like me. 

Linked to #2042

**Comment by skirtles-code** [comment]
Closed by #2042.
