### ISSUE TITLE
Title is not rendered properly for <script setup> page

### ISSUE THREAD

**Issue by milos018** [vuejs/docs#2098]
When visiting https://vuejs.org/api/sfc-script-setup.html#script-setup, the title is not rendered properly. 
I tried fixing it, but this seems to be more of a security measure due to <script> tag. 

![image](https://user-images.githubusercontent.com/46306967/202885668-54567bd3-c40f-453e-abb3-3b256a0d319d.png)

**Comment by Z3rio** [comment]
Seems to be working fine in google chrome, which browser are you using?

**Comment by milos018** [comment]
Oh, you are absolutely right, it was the Grammarly extension, when off it works fine.
