### ISSUE TITLE
possible incorrect statement regarding x-template and element placement restrictions

### ISSUE THREAD

**Issue by schalkneethling** [vuejs/docs#2107]
On https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats there is a tip that states the following:

> It should be noted that the limitations discussed below only apply if you are writing your templates directly in the DOM. They do NOT apply if you are using string templates from the following sources:
> 
> Single-File Components
> Inlined template strings (e.g. template: '...')
> <script type="text/x-template">

I ran into this exact problem with a `tr` element while using an `x-template`:
https://gist.github.com/schalkneethling/3d3440e883f59269618e696c9f5f30a6

Here is what I had to do:
https://forum.vuejs.org/t/tr-component-rendered-outside-of-table/67755/7?u=schalkneethling

Happy to update the docs page if it should indeed not mention `<script type="text/x-template">` in the list.

**Comment by LinusBorg** [comment]
It's not incorrect though, in fact it precisely explains the problem you saw.

You had an "illegal" element in your actual HTML - an element named `<transaction>` inside of a `<tbody>`, which is not allowed. So the browser hoisted it out of the table. What you had in the `<script type="text/x-template">` does not matter here.

Yes, Vue would have replaced that element with proper markup later, but by then it was already parsed by the browser, and hoisted out.

**Comment by schalkneethling** [comment]
> It's not incorrect though, in fact it precisely explains the problem you saw.
> 
> You had an "illegal" element in your actual HTML for the table (not in the `<script type="text/x-template">`) - an element named `<transaction>` inside of a `<tbody>`, which is not allowed. So the browser hoisted it out of the table.
> 
> Yes, Vue would have replaced that element with proper markup later, but by then it was already parsed by the browser, and hoisted out. had you also wrapped the whole table in a `<script type="text/x-template">`, the problem would _not_ happen.

Gotcha! Thank you for the clarification @LinusBorg, I misread the "tip". So, it will not happen inside an `x-template` but will happen when in "plain" HTML that is not part of a single file component. :+1:
