### ISSUE TITLE
dead link in docs guide/built-ins/transition.html

### ISSUE THREAD

**Issue by horanchikk** [vuejs/docs#2120]
link: https://vuejs.org/guide/built-ins/transition.html#transition
![image](https://user-images.githubusercontent.com/46918417/205933689-6e0ff00b-2332-4b7b-92a9-8ce660a044cf.png)
![image](https://user-images.githubusercontent.com/46918417/205933717-79d7bf18-5ccd-4c10-9c2f-3c6a943526fd.png)

**Comment by horanchikk** [comment]
спасибо за фикс :bulb:

**Comment by rockymontana** [comment]
Nevermind. Opened it in a new tab where it magically worked.
