### ISSUE TITLE
Emit increaseBy vs @increase-by

### ISSUE THREAD

**Issue by proyb6** [vuejs/docs#2124]
Confusing by typo error in
https://vuejs.org/guide/components/events.html#event-arguments

**Comment by proyb6** [comment]
This work but typo means it can be error prone and confusing for developers when the code should be in exact characters by characters.

**Comment by skirtles-code** [comment]
I don't see a typo in that code. Copying the exact code, character by character, does work. Here's an example on the SFC Playground:

<https://sfc.vuejs.org/#eNpdkMtugzAQRX9lZFWCqMFWtgiiNrsu+gfegGVap/FDtmmFEP/eMTiozW4eV+fOnZm8Oke/R0lq0gThlYsQZBzdmRulnfURZvBygAUGbzUUKC321ft0GWO0Ju8ouw8SEWXcCGtCBGFHE6FNoPJ04KZhmxWaYBOldrcuSuwA5jmrlyW1zW7xoozwsguy6qeWk9IcoD1n7XMLhhNgSGjYjiNHst1Z6c7Ra7AGQ86JyvMicFLDOkkzvDn1nHzG6ELNWBhECnIN1PoPhhX16Ka0pDLoqvf2J0iPYE4SAu9d0PLvC9JT/6Vr+hxG3JT4whhPUqtYFvdsl6k4An6IrGqAtzyHfoLTCmAb4SHp8gu29ptQ>

The events `increaseBy` and `increase-by` are considered equivalent. The usual convention is to use kebab-case for attributes in the template.

**Comment by skirtles-code** [comment]
Closing. As far as I'm aware, there is not a typo in the event name and nothing needs to be changed.
