### ISSUE TITLE
Dead link /guide/custom-filter.html

### ISSUE THREAD

**Issue by ElisHoli** [vuejs/docs#2130]
There is a dead link at the following URL: https://vuejs.org/guide/custom-filter.html

**Comment by skirtles-code** [comment]
Where did you encounter this link?

Vue 3 doesn't have filters, so they aren't mentioned in the docs.

They're covered in the Vue 2 docs here: <https://v2.vuejs.org/v2/guide/filters.html>.

The migration guide page about their removal is at <https://v3-migration.vuejs.org/breaking-changes/filters.html>.

But neither of those pages call them 'custom filters'. My best guess is that the link originally pointed at the docs for Vue 1, which are now at <https://v1.vuejs.org/guide/custom-filter.html>.

**Comment by skirtles-code** [comment]
I'm going to close this for now. As far as I can tell there isn't a problem with the current docs.
