### ISSUE TITLE
Sentry sponsor link is broken

### ISSUE THREAD

**Issue by hugo-t-b** [vuejs/docs#2137]
The Sentry sponsor link at [sponsors.vuejs.org/data.json](https://sponsors.vuejs.org/data.json) ([sentry.io/for/vue?utm_source=vuejs.org&utm_medium=paid-community](https://sentry.io/for/vue?utm_source=vuejs.org&utm_medium=paid-community)) doesn't start with `https://`, so the Sentry links on the docs site don't work (as they open a non-existent page within the docs site).

**Comment by yyx990803** [comment]
This has been fixed at the data source.
