### ISSUE TITLE
vue3 Is there a solution that supports a lower version of the browser

### ISSUE THREAD

**Issue by huangtizan** [vuejs/docs#2167]

**Comment by skirtles-code** [comment]
See <https://vuejs.org/about/faq.html#what-browsers-does-vue-support>.

This issues list is for reporting problems with the docs. The question in the title is a little vague, but from what I can tell it doesn't relate to a documentation problem. The Vue Discord at <https://chat.vuejs.org/> is a good place to ask help questions. Thanks.
