### ISSUE TITLE
Reactivity Fundamentals page in Guide 404s

### ISSUE THREAD

**Issue by jessejohnson** [vuejs/docs#2180]
The URL for "Reactivity Fundamentals" currently 404s. Here is the link `https://vuejs.org/guide/essentials/reactivity-fundamentals.html`.

It is the next article in the Guide after "Template Syntax"

**Comment by skirtles-code** [comment]
Would you mind checking again? It seems to be working for me now.

**Comment by jessejohnson** [comment]
@skirtles-code yes, it's working for me now. Thanks.
