### ISSUE TITLE
Select multiple form binding does not work

### ISSUE THREAD

**Issue by kriordan37** [vuejs/docs#2197]
https://vuejs.org/guide/essentials/forms.html#select

The example does not work. and i also verified locally on a brand new nuxt3 environment. 

works the same as select without adding multiple to the list

**Comment by skirtles-code** [comment]
It seems to be working for me. The `<select>` is displayed as a list rather than as a dropdown. Multiple items can be selected using `ctrl+click`, `shift+click` or `click+drag`.

**Comment by kriordan37** [comment]
yes I did not realize a ctrl/command click was necessary thank you!
