### ISSUE TITLE
Broken link to "TypeScript unit tests for component type extensions" in Vuejs docs.

### ISSUE THREAD

**Issue by canbax** [vuejs/docs#2206]
Here https://vuejs.org/guide/typescript/options-api.html#typing-event-handlers links for [TypeScript unit tests for component type extensions](https://github.com/vuejs/core/blob/main/test-dts/componentTypeExtensions.test-d.tsx) is broken

**Comment by skirtles-code** [comment]
I believe the new URL is <https://github.com/vuejs/core/blob/main/packages/dts-test/componentTypeExtensions.test-d.tsx>.

**Comment by skirtles-code** [comment]
Fixed by #2223.
