### ISSUE TITLE
Chinese language switch to English language url in more than one slash

### ISSUE THREAD

**Issue by zhoujiahua** [vuejs/docs#2208]
As shown in the picture when I enter the official home page of the document through the (https://vuejs.org) domain name, then switch to the Chinese language document and then switch back to the English document when there will be a slash in the URL. I also checked the other language document switch without this problem, only the Chinese document will have this problem.

> Step 1

![](https://github.com/zhoujiahua/picture/blob/master/2023/1-1.png?raw=true)

> Step 2

![](https://github.com/zhoujiahua/picture/blob/master/2023/1-2.png?raw=true)

> Step 3

![](https://github.com/zhoujiahua/picture/blob/master/2023/1-3.png?raw=true)

> Step 4

![](https://github.com/zhoujiahua/picture/blob/master/2023/2-1.png?raw=true)

> Step 5

![](https://github.com/zhoujiahua/picture/blob/master/2023/2-2.png?raw=true)

**Comment by xfq** [comment]
Related: https://github.com/vuejs/theme/pull/84
