### ISSUE TITLE
chinese doc in guide → build-in → transition has a redundancy word

### ISSUE THREAD

**Issue by kissjanna** [vuejs/docs#2215]
![image](https://user-images.githubusercontent.com/63863023/217164869-d53a1c55-e904-44f2-9aca-ddde70cf8b0d.png)

this should be: `这意味着它在任意的组件中都可以被使用` or `这意味着它在任意级别的组件中都可以被使用`
and I think the first one is better

https://cn.vuejs.org/guide/built-ins/transition.html#the-transition-component

**Comment by xfq** [comment]
原文：

> `<Transition>` is a built-in component: this means it is available in any component's template without having to register it.

改为“这意味着它在任何组件中都可以被使用”可能更符合原文一些。还可以将被动改为主动，即“这意味着在任何组件的模板中都可以使用它”。

**Comment by xfq** [comment]
This is a translation issue, and should be filed against https://github.com/vuejs-translations/docs-zh-cn/issues

**Comment by acyza** [comment]
maybe `别的=其他`

**Comment by skirtles-code** [comment]
If this problem still exists, could you please open an issue in the translation repo, <https://github.com/vuejs-translations/docs-zh-cn/issues>. Thanks.
