### ISSUE TITLE
docs template render error

### ISSUE THREAD

**Issue by Sunny-117** [vuejs/docs#2221]
文档地址：https://vuejs.org/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates

渲染结果有误
![image](https://user-images.githubusercontent.com/73089592/217456227-f70408f1-71b7-409b-ac27-e210cd21d4b7.png)

pr链接：

vuejs：https://github.com/vuejs/docs/pull/2220
vuejs-zh：https://github.com/vuejs-translations/docs-zh-cn/pull/652

**Comment by skirtles-code** [comment]
Fixed by #2222.
