### ISSUE TITLE
Property pass-through parent component v-on binding function call problem

### ISSUE THREAD

**Issue by longh-w** [vuejs/docs#2225]
After $attrs is accessed with an interpolation in the child component, the parent component's click bound function cannot be called

**Comment by NataliaTepluhina** [comment]
@longh-w could you please provide a better description/example? Also, it would be nice to understand what exactly in the docs should be fixed.

If you believe you've encountered a bug, it should be reported in https://github.com/vuejs/core instead

**Comment by longh-w** [comment]
I mean, if I use the $attrs syntax, does the value of the inheritAttrs property default to false

**Comment by longh-w** [comment]
Notice the output of the console
[Uploading demo.zip…]()
