### ISSUE TITLE
Empty file extras/custom-renderer.md

### ISSUE THREAD

**Issue by tlagoda** [vuejs/docs#2238]
The `Custom Renderer` page in the `Extra Topics` section is empty. It seems that the doc has been moved to the `API` section.

From API section:
https://vuejs.org/api/custom-renderer.html

From Extra Topics section:
https://vuejs.org/guide/extras/custom-renderer.html

**Comment by AloisSeckar** [comment]
Not really. From git history it looks like it was always just a heading with no content.

Can we figure out, what info should be there?
