### ISSUE TITLE
Typescript section still suggests Reactivity transform, without warning

### ISSUE THREAD

**Issue by kohasummons** [vuejs/docs#2248]
[Typescript with Composition API](https://github.com/vuejs/docs/blob/main/src/guide/typescript/composition-api.md#typing-component-props) page suggests using the deprecated Reactivity transform as an alternative to `withDefaults` compiler macro.

To help devs move faster, showing a deprecated text box here would be great.

**Comment by AloisSeckar** [comment]
I opened a [PR](https://github.com/vuejs/docs/pull/2249) for this. Suggestions and improvements welcome.

**Comment by NataliaTepluhina** [comment]
I believe we can close this issue now as the recommendation is gone
