### ISSUE TITLE
Unreable images - Composition API FAQ

### ISSUE THREAD

**Issue by tlagoda** [vuejs/docs#2253]
The two images used in the Composition API FAQ page are not clearly readable, even if you zoom in. 

Perhaps the code should be put directly on the page, or a link to github should be used ?

<img width="859" alt="Capture d’écran 2023-02-26 à 22 41 02" src="https://user-images.githubusercontent.com/108621533/221439117-4d766188-3fc2-49f2-b528-520d6a027060.png">
<img width="850" alt="Capture d’écran 2023-02-26 à 22 41 12" src="https://user-images.githubusercontent.com/108621533/221439126-92d184ce-9b79-4dc0-a4fe-2580cfe5cb01.png">

**Comment by skirtles-code** [comment]
I don't think you're supposed to be able to read the words. I think the point of the images is the colors showing where the logical concerns are located within the code.
