### ISSUE TITLE
文档错误,关于条件渲染部分

### ISSUE THREAD

**Issue by emptybamboo** [vuejs/docs#2269]
我在学习时看到,文档提到**如果要使用v-if渲染一组元素,该使用template**
但是我尝试使用div标签内部包裹几个标签,然后在最外层的div标签上使用v-if,一样可以一次渲染一组元素
然后经过查询我发现了**Vue2中`v-if` 只能应用于单个元素或模板**（即 `<template>` 元素）。但是**Vue3中这个限制已经被解除**了。你可以在任何元素上使用 `v-if`，包括普通的 `<div>` 元素，并且在该元素下包含任意数量的子元素。
所以这应该是一个**文档更新的滞后**,位置处于`条件渲染`->`<template> 上的 v-if`->"但如果我们想要切换不止一个元素呢？在这种情况下我们可以在一个 <template> 元素上使用 v-if"

**Comment by skirtles-code** [comment]
I don't believe Vue 3 is any different from Vue 2 in its handling of this scenario.

The reason for putting a `v-if` on a `<template>` tag is that the `<template>` tag won't be rendered in the final DOM. If you put the `v-if` on a `<div>` then you'll get an extra `<div>` element in the rendered DOM. The extra element is not only unnecessary DOM bloat, but it can cause breakages, e.g. for CSS layouts, or for elements like `<tr>` that need to be directly within a specific parent element.

**Comment by so1ve** [comment]
都可以，就是看你要不要渲染一个包裹标签

The both works. Putting v-if on template won't render a wrapper element.

**Comment by skirtles-code** [comment]
Closing, as I don't think there's a documentation problem here.
