### ISSUE TITLE
Can't find menu for  'https://vuejs.org/guide/extras/reactivity-transform.html'

### ISSUE THREAD

**Issue by meitingshuoguo** [vuejs/docs#2278]
There is this page, but no corresponding portal was found. So I wonder if this menu should be added

**Comment by skirtles-code** [comment]
Reactivity Transforms have recently been deprecated. The menu items have been removed but the page itself has been retained for now so that external links can still find it. The page will eventually be removed entirely.

**Comment by meitingshuoguo** [comment]
👌thanks😊
