### ISSUE TITLE
Suspense Documentation Page

### ISSUE THREAD

**Issue by Rizkyfss** [vuejs/docs#2283]
i cant find suspense documentation page

"You found a dead link: /guide/built-ins/suspense.html"

**Comment by skirtles-code** [comment]
Try refreshing. The page does exist.

The 'dead link' page is a bit misleading. If there's any kind of problem loading the page it'll show that error. Even if your internet connection goes down you'll get the same page. As far as I'm aware there's not currently a way for us to show different pages for different errors with VitePress.

**Comment by 680614** [comment]
- [ ] ```

```
