### ISSUE TITLE
Odd comment in SVG example

### ISSUE THREAD

**Issue by tlagoda** [vuejs/docs#2287]
In the index.html of the [SVG example](https://vuejs.org/examples/#svg), there is a comment `Say Hello World with Vue!`.
This is the same comment as in the [Hello World example](https://vuejs.org/examples/#hello-world).

<img width="1092" alt="Capture d’écran 2023-03-14 à 20 22 02" src="https://user-images.githubusercontent.com/108621533/225114906-fcf00205-7913-4176-9751-bae942d563c6.png">

Is this normal?

**Comment by NataliaTepluhina** [comment]
@tlagoda normal but absolutely unnecessary, let's remove the comment 😅 Would you like to open a PR or should I fix this one?

**Comment by tlagoda** [comment]
It's up to you @NataliaTepluhina 😂

**Comment by NataliaTepluhina** [comment]
Fixed in https://github.com/vuejs/docs/commit/76b0fea9879027344bf13d50048b80a97005fdd1
