### ISSUE TITLE
Missing search result for mixin

### ISSUE THREAD

**Issue by sphenginx** [vuejs/docs#2303]
RT.

**Comment by skirtles-code** [comment]
Sorry, I don't understand. What is missing from where?

**Comment by sphenginx** [comment]
Missing the mixin search result, as the follow img:
![image](https://user-images.githubusercontent.com/1829395/227861594-dc2f10cf-7e65-4545-a497-ffb6e372f47b.png)

**Comment by brc-dd** [comment]
Can you try reloading, it appears to be working for me:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/40380293/227862746-50f9cf03-c6a0-4f38-abba-23334565d3a7.png">

**Comment by sphenginx** [comment]
> Can you try reloading, it appears to be working for me:
> 
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/40380293/227862746-50f9cf03-c6a0-4f38-abba-23334565d3a7.png">

Let me try, It worked.
