### ISSUE TITLE
中文官网图片放大不了，看不清楚内容；源码地址也访问不了

### ISSUE THREAD

**Issue by yoghurtxu** [vuejs/docs#2307]
这个页面的图片放大不了https://cn.vuejs.org/guide/extras/composition-api-faq.html#more-flexible-code-organization；
源码地址也访问不了https://gist.github.com/yyx990803/8854f8f6a97631576c14b63c8acd8f2e

**Comment by Jinjiang** [comment]
图片本身就是缩略图。源码访问不了应该是被墙了。
