### ISSUE TITLE
I don't understand the information in this document vur-router

### ISSUE THREAD

**Issue by suzhenghui-sky** [vuejs/docs#2313]
https://router.vuejs.org/zh/guide/essentials/redirect-and-alias.html
![2414736-20230407152744280-106325907](https://user-images.githubusercontent.com/48371536/230586570-31eaae11-879b-40b0-910c-02b7f741bf92.png)
It was not successfully reproduced

 https://router.vuejs.org/zh/guide/essentials/passing-props.html
![图片](https://user-images.githubusercontent.com/48371536/230586755-1a0fcf52-05c3-47dd-b62f-b5bdd2def9d7.png)

Don't understand

**Comment by adrienZ** [comment]
@suzhenghui-sky maybe you should post this in vue-router instead https://github.com/vuejs/vue-router/issues

**Comment by suzhenghui-sky** [comment]
@adrienZ thank you.

**Comment by suzhenghui-sky** [comment]
Thank you. @adrienZ

**Comment by skirtles-code** [comment]
If you think there's a problem with the router docs then please report an issue at <https://github.com/vuejs/router/issues>.

If you're just looking for clarification about how Vue Router works then I suggest asking at <https://github.com/vuejs/router/discussions> or on Discord: <https://chat.vuejs.org/>.

Thanks.
