### ISSUE TITLE
There's no way to write setup（RouterLink，useLink）

### ISSUE THREAD

**Issue by suzhenghui-sky** [vuejs/docs#2316]
![图片](https://user-images.githubusercontent.com/48371536/230819516-64491408-3e0b-4623-aec5-7a42cd5e37f9.png)
![图片](https://user-images.githubusercontent.com/48371536/230819543-9854991e-b4b3-4ad9-a06e-7fef9a84c01a.png)
![图片](https://user-images.githubusercontent.com/48371536/230819564-9c1264b7-aea1-48d9-b169-2726237dd534.png)

**Comment by skirtles-code** [comment]
I'm not exactly sure what issue you're reporting, but it doesn't seem to be a problem with the Vue 3 docs.

If you think there's a problem with the router docs then please report an issue at <https://github.com/vuejs/router/issues>.

If you're just looking for clarification about how Vue Router works then I suggest asking at <https://github.com/vuejs/router/discussions> or on Discord: <https://chat.vuejs.org/>.

Thanks.
