### ISSUE TITLE
The translation is wrong in zh_CN, which affects the reading experience

### ISSUE THREAD

**Issue by CherishMvp** [vuejs/docs#2319]
![image](https://user-images.githubusercontent.com/88085841/231936789-27ee2d7a-5df9-40f8-aa43-fbc4f321c5cb.png)
直接翻译为"将一个ref赋值给一个 reactive 属性时"
"

**Comment by skirtles-code** [comment]
Could you open an issue in the translation repo? <https://github.com/vuejs-translations/docs-zh-cn/issues>. Thanks.

**Comment by yyx990803** [comment]
https://github.com/vuejs-translations/docs-zh-cn/commit/6447f5d8d7364780d363318d40605b4f99f0d726

下次建议直接在正确的仓库下开 PR
