### ISSUE TITLE
[OTHERS] Can't find Vue Style Guides in Vue Website

### ISSUE THREAD

**Issue by at-the-vr** [vuejs/docs#2321]
I see [Vue Style Guides](https://vuejs.org/style-guide/) is a publicly accessible page (really helpful) but I cant find it anywhere in [vuejs.org](https://vuejs.org/)

**Comment by brc-dd** [comment]
Duplicate of #2030

**Comment by at-the-vr** [comment]
I am sorry to miss the Issue, should i close it Divyansh ?

**Comment by brc-dd** [comment]
Yeah.
