### ISSUE TITLE
Missing search result for getCurrentInstancegetCurrentInstance

### ISSUE THREAD

**Issue by sm200435** [vuejs/docs#2335]
官网搜索不到getCurrentInstance（）

**Comment by viniciusteixeiradias** [comment]
> 官网搜索不到getCurrentInstance（）

https://github.com/vuejs/docs/issues/1422#issuecomment-1032120675

**Comment by yyx990803** [comment]
It is intentionally omitted to discourage its usage.

**Comment by jackchoumine** [comment]
> It is intentionally omitted to discourage its usage.

If So, How can I get $el? 
before
```js
const that = getCurrentInstance()
const ele = that.ctx.$el // work well in vue3.1.x but  get undefined in vue3.3.4
```

**Comment by viniciusteixeiradias** [comment]
> > It is intentionally omitted to discourage its usage.
> 
> If so, How can I get $el?
> 
> ```js
> const that = getCurrentInstance()
> const ele = that.ctx.$el // work well in vue3.1.x but  get undefined in vue3.3.4
> ```

Directly accessing the internal properties of Vue components, such as `$el`, is generally not recommended. It's considered a best practice to avoid manipulating internal properties directly, as it can lead to issues and might not be compatible with different versions or future updates.

If you need to access the root element of the component, Vue provides a more reliable approach using the`ref` attribute.
