### ISSUE TITLE
The sponsors on the homepage are not displayed

### ISSUE THREAD

**Issue by ntillier** [vuejs/docs#2358]
On the homepage, the sponsors are not displayed. There are only the `Platinium Sponsors` and `Gold Sponsors` headings, without anything below, which makes it look quite weird.

In the network tab, the page makes a fetch request to https://sponsors.vuejs.org/data.json, with some sponsor arrays in the result, but it seems that they are not displayed (note: there are no errors in the console)

Here is a screenshot:
![image](https://user-images.githubusercontent.com/102358700/236692819-92017b4c-69bc-45fb-8ea7-4f96c04d42a0.png)

**Comment by brc-dd** [comment]
You probably have ad blocker enabled. For me it's working fine 👀

**Comment by ntillier** [comment]
@brc-dd thanks 😅 I disabled the adblock extension and everything is normal again. I'm sorry 🙏
