### ISSUE TITLE
How to create a component in Vue3?

### ISSUE THREAD

**Issue by ramwin** [vuejs/docs#2368]
I'm using vue3 installed by a cdn script.
```
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
```

How should I create a reusable component for different html?

In vue2, I can use
```
var MyComponent = Vue.extend({
    template: '<div>I'm component</div>', 
    props: ['title'],
})
Vue.component('my-component', MyComponent)
```

It doesn't work in Vue3.

The [Defining a component](https://vuejs.org/guide/essentials/component-basics.html#defining-a-component) only shows how to create a component in a sfc.

**Comment by ikxin** [comment]
See also: [defineComponent()](https://vuejs.org/api/general.html#definecomponent)

**Comment by yyx990803** [comment]
Please read the docs.
