### ISSUE TITLE
Quick Start instructions requires adding `npm-run-all`

### ISSUE THREAD

**Issue by kberg** [vuejs/docs#2376]
I followed instructions on the Quick Start instructions page. `package.json` includes this line:

`"build": "run-p type-check build-only",`

To run `run-p` you need to install `npm-run-all`.

**Comment by yyx990803** [comment]
I assume you created the template via `create-vue` - the latest result does include `npm-run-all` in `devDependencies`. If you have a reproduction case where `npm-run-all` is not listed in deps, please report it to https://github.com/vuejs/create-vue and provide more details.
