### ISSUE TITLE
Vue3 from CDN 

### ISSUE THREAD

**Issue by pal-software** [vuejs/docs#2394]
Hello.
In my current prod app I am using SFC (webpack) & vue 2 with vue-router.
But when I tried migrating to vue 3 it became a problem.
Our current application works on the one hand as a regular web application (http/https protocols), and inside a native wrapper application (Android/Apple), where it opens using the "file:///" protocol (so we can't use newfangled vite :) ).
When I tried to configure the build via webpack, I found problems with the output of the information "The resolve component can only be used in render() or setup().". I can resolve this with my components, but I can't resolve this for vue-router (with router-view, router-link & etc).

Attached file include archive with 2 catalogs.  
- vue 2 is a fully configured simple example for vue 2 (unpack, run "npm i", then "_watch" or "_build")
- vue 3 - an attempt to do something similar for vue 3 (unsuccessful :))...

[vue-cdn-samples.zip](https://github.com/vuejs/docs/files/11641481/vue-cdn-samples.zip)

I need some help, please!    :)

P.S.: Sorry for my poor English

**Comment by yyx990803** [comment]
Why are you using webpack but still loading Vue from a CDN? Your webpack bundle already includes Vue, so you are loading two copies of Vue on the same page for no reason.

It happened to work in the Vue 2 case, but in Vue 3 some internals require the app to be mounted using the same copy of Vue that the components are using.

In your `src/index.js`, instead of using `window.Vue`, you should be doing:

```js
import { createApp } from 'vue'
```

Also, the async `init()` looks pointless to me... your entire `init.js` should just be:

```js
import router from './js/router'
import app from './components/app.vue'
import { createApp } from 'vue'

createApp(app).use(router).mount("#id-app")
```

Finally, this really isn't the right place to look for help - please use StackOverflow or https://github.com/vuejs/core/discussions for this kind of questions in the future.

**Comment by pal-software** [comment]
> Why are you using webpack but still loading Vue from a CDN? Your webpack bundle already includes Vue, so you are loading two copies of Vue on the same page for no reason.
> 
> 
> Finally, this really isn't the right place to look for help - please use StackOverflow or https://github.com/vuejs/core/discussions for this kind of questions in the future.

It's not as simple as you thought
If you look closely package.json, then you will see that there are no dependencies on vue & vue-router.
In fact, all dependencies are devDependencies.
And if I was satisfied with the build with vue, then there would be no question.
Why?
My application includes many independed modules. Each of these modules is a separate SPA. 
There are quite a lot of such modules. And I don't want to link the same resources (fonts, libraries,... frameworks) to each of them. All these shared resources are stored centrally. It should be borne in mind that in general, all this application is eventually cached on the user's mobile device.
Therefore, of course, I am glad that they told me how to do what is written in the documentation and that there is such a thing as a 'stackoverflow' website. But the question was asked about something else and it was asked for a reason.

If you're interested, I can give you the numbers   :)

**Comment by pal-software** [comment]
for example... if i make build of every module as you advise (simple, fast and unpretentious), then every module average size is 700KB. when i exclude common resources, then every module average size is 70 KB (and one module - about 1000KB). so if I have 20 modules now (for example), then we have.  14MB (in the first case) or 2.5MB (in the second case).

**Comment by yyx990803** [comment]
Then you need to properly externalize Vue in your webpack config: https://webpack.js.org/configuration/externals/

Again, please do NOT use issues in the documentation repository for general usage questions like this. This is not the right channel.

**Comment by pal-software** [comment]
> Then you need to properly externalize Vue in your webpack config: https://webpack.js.org/configuration/externals/
> 
> Again, please do NOT use issues in the documentation repository for general usage questions like this. This is not the right channel.

Thank you very much.
