### ISSUE TITLE
Component registration should be mentioned in “Components Basics” section

### ISSUE THREAD

**Issue by JianzhengLuo** [vuejs/docs#2395]
# Component registration should be mentioned in "Components Basics" section

## Description

Hello, I'm a beginner of Vue.js, and I really appreciate the excellent documentation you have provided. However, I encountered a problem when I tried to create a nested component with two levels. The second-level component was not rendered at all, and I did not know why.

## Steps to reproduce

1. Create a first-level component and use it in the App.vue file. It works fine without any registration.
2. Create a second-level component and use it in the first-level component file. It does not show up in the browser.
3. Check the console and see no errors or warnings.

## Expected result

The second-level component should be rendered as expected.

## Actual result

The second-level component is not rendered at all.

## Solution

After a long time of debugging, I realized that components need to be registered before they can be used. I followed the instructions in the "Component Registration" section of the documentation and registered my second-level component locally in the first-level component file. Then it worked as expected.

## Suggestion

I wonder if it would be possible to add the component registration requirement to the "Components Basics" section of the documentation, or at least briefly mention it. Because the concept of "registration" is unfamiliar to most people, and many people like me who are "eager to achieve" will not continue to read the advanced part until they encounter a problem. It would be helpful to let beginners know this important step in advance.

Thank you for your time and attention. I hope this feedback is useful for you.

## Metadata

- Labels: documentation, enhancement
- Milestone: Vue 3.x
- Assignee: @vuejs/docs-team
- Project: Vue.js Documentation

**Comment by yyx990803** [comment]
It is indeed mentioned here, did you miss it? https://vuejs.org/guide/essentials/component-basics.html#using-a-component
