### ISSUE TITLE
Is there something wrong with the sponsors section at homepage?

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs/docs#2411]
I noticed in the recent updates that this section is not showing the sponsors of the project anymore, I especially consider this section important because helps those who are looking for jobs since it is possible that the companies sponsoring the project are using it and could themselves hiring professionals to work with the tool.

![Screenshot 2023-06-17 at 05-23-42 Vue js - The Progressive JavaScript Framework Vue js](https://github.com/vuejs/docs/assets/31008635/a914e519-9886-481d-b0d6-66dd53c52a2f)

**Comment by mahmudunnabikajal** [comment]
@nazarepiedady recheck again after removing your browser cache and cookies.

**Comment by colynyu** [comment]
I reinstalled Chrome, still can not display sponsors.

**Comment by colynyu** [comment]
I reinstalled Chrome, but the sponsors still cannot be displayed.

**Comment by brc-dd** [comment]
y'all are probably using some ad blocker

**Comment by colynyu** [comment]
Yes!!! I closed ad blocker and it's fine.  But I was able to get it to display fine around June 14th, maybe the browser plugin has been updated.

**Comment by nazarepiedady** [comment]
It is fine now!
