### ISSUE TITLE
"Page Not Found" on vuejs.org homepage

### ISSUE THREAD

**Issue by winston-yallow** [vuejs/docs#2423]
I sometimes get a "Page Not Found" error on the vuejs.org homepage. This happened a few times randomly so far, but I can't seem to reproduce this on purpose. I wish I could provide more detailed instructions on how to trigger this.

Browser: Firefox 114.0.1 (64-bit)

![image](https://github.com/vuejs/docs/assets/44872771/913bf0e2-1ca8-4b02-b66e-a7b0cfebe636)

**Comment by mahmudunnabikajal** [comment]
@winston-yallow 

Most likely a network issue at your side. Try reloading or disabling extensions. It's opening fine for me.

**Comment by winston-yallow** [comment]
This keeps happening to me, even with no extensions enabled.

For good measure I tried chromium too, with the same result. It's worth mentioning though that the issue never happens on the first load after clearing all local site data like cookies. It only happens on subsequent loads, but not always.

My network is good too. Fast and stable connections, and according to `ip -s link show eth0` no dropped packets.
