### ISSUE TITLE
Suggested testing libraries for vite are outdated

### ISSUE THREAD

**Issue by MefAldemisov** [vuejs/docs#2429]
Guide page dedicated to testing (https://vuejs.org/guide/scaling-up/testing.html#recommendation) lists several libraries, which can be used with `vite` namely:
- [vitest](https://github.com/vitest-dev/vitest)
- [peeky](https://github.com/Akryum/peeky)
- [vite-jest](https://github.com/sodatea/vite-jest)

Peeky and vite-jest repos seem to be dead: 
- last update was more than 6 months ago
- the major version of the tools is 0
- repos contain low number of contributors, sponsors and users

Shouldn't the reference of unreliable resources be removed from the official documentation?

Here is the reference to the file, which should possibly be corrected: https://github.com/vuejs/docs/blob/main/src/guide/scaling-up/testing.md

**Comment by NataliaTepluhina** [comment]
Good catch! Thank you @MefAldemisov, I removed mentioning the outdated libraries
