### ISSUE TITLE
Update Accessibility Documentation on content structure (landmarks)

### ISSUE THREAD

**Issue by dnikub** [vuejs/docs#2440]
Hello,

I noticed that inside your accessibility documentation in the section [Content Structure](https://vuejs.org/guide/best-practices/accessibility.html#content-structure), you have a tip for landmarks that's not up-to-date. The quote I am referring to is this:

> Tip: It is recommended to use landmark HTML elements with redundant landmark role attributes in order to maximize compatibility with legacy [browsers that don't support HTML5 semantic elements](https://caniuse.com/#feat=html5semantic).

**I believe this tip can be removed from the Vue 3 docs** due to multiple reasons:

- The only legacy browser referenced here is IE, which is [not supported anymore since June 2022](https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-11).
- Vue 3 does not support IE, as it uses ES2015 features that cannot be polyfilled in legacy browsers (as you write yourself in your [FAQs](https://vuejs.org/about/faq.html#what-browsers-does-vue-support)).
- Sticking to the semantic HTML element and avoiding adding a redundant ARIA landmark role is recommended. The official [W3C recommendation for ARIA in HTML in 2023](https://www.w3.org/TR/html-aria/#avoid-specifying-redundant-roles) is: 

  > Avoid specifying redundant roles. In practice this particular instance of redundancy will likely not have unforeseen side effects, other than unnecessarily making the markup more verbose, and incorrectly signalling to other authors that this practice is useful.

I recommend **replacing the current tip** with the just-named information. The table of examples for landmark roles you give within your docs implies using the redundant ARIA roles is what one should do.

Thanks!

**Comment by ranjbarreza** [comment]
Hi @dnikub 
I made this PR: https://github.com/vuejs/docs/pull/2996
Could you take a look please?
