### ISSUE TITLE
On https://cn.vuejs.org/examples/#fetching-datas, the preview is missing.

### ISSUE THREAD

**Issue by inblossoms** [vuejs/docs#2443]
During the access process, the error message "Cannot read undefined properties (read 'slice')" is displayed.   As a result, the PREVIEW is lost and cannot be displayed normally.
If this is just my personal problem, please contact me to close this issue.

**Comment by brc-dd** [comment]
The URL appears wrong to me, it should https://cn.vuejs.org/examples/#fetching-data 

It seems to be working fine for me:

<img width="1792" alt="image" src="https://github.com/vuejs/docs/assets/40380293/c941894e-c3f0-44ff-b3c8-824ed98fa276">

If that URL doesn't work fine, can you try using a different browser?

**Comment by inblossoms** [comment]
> The URL appears wrong to me, it should be [cn.vuejs.org/examples/#fetching-data](https://cn.vuejs.org/examples/#fetching-data)
> 
> It seems to be working fine for me:
> 
> <img alt="image" width="1792" src="https://user-images.githubusercontent.com/40380293/254914196-c941894e-c3f0-44ff-b3c8-824ed98fa276.png">
> If that URL doesn't work fine, can you try using a different browser?

Thank you for your reply, I use chrome browser, I tried to fix this problem by refreshing, found that this problem is in a certain probability
