### ISSUE TITLE
Not found link found in doc 

### ISSUE THREAD

**Issue by tisma95** [vuejs/docs#2445]
Hello here there's a link in the doc For Node.js Stream API this url points to a not found page

It is this url should be there https://nodejs.org/dist/latest-v18.x/docs/api/stream.html ?
![255229834-9f43eeb5-1fe0-40d5-856c-c994a7a5269e](https://github.com/vuejs/docs/assets/55036198/9da66be6-8d30-437a-8b08-1e8629fe3ffa)

Link https://fr.vuejs.org/guide/scaling-up/ssr.html#rendering-an-app

https://nodejs.org/api/stream

Thanks

**Comment by brc-dd** [comment]
Ah, it should be https://nodejs.org/api/stream.html (seems like they have changed something at their server level). PRs are welcome.

**Comment by tisma95** [comment]
Thanks @brc-dd for your response

**Comment by inblossoms** [comment]
> Ah, it should be [nodejs.org/api/stream.html](https://nodejs.org/api/stream.html) (seems like they have changed something at their server level). PRs are welcome.

I fixed the problem, but I don't have access to the repository
