### ISSUE TITLE
Events for large lists, and event delegation

### ISSUE THREAD

**Issue by Andrioden** [vuejs/docs#2446]
**Description**
Not knowing the internals of Vue, I am wondering what the recommendation from the vue team is on this. I also suggest you update the documentation on this.

Image you have a game squared 100 x 100, resulting in 10 000 elements visible, each square has a data object related to it that needs to be acted upon on click. How would you add an onclick event handler?

Event delegation is an pattern of creating _one_ function that deals with events bubbled up from _all_ children.

As I see it, you have 3 options:

**Alternative A - Unique clickHandler per cell**
``` html
<div>
   <div v-for="row in rows">
      <div v-for="cell in row" @click="clickHandler(cell)"></div>
   </div>
</div>
```
``` js
function clickHandler(cell) {
    cell.act()
}
```

**Alternative B - Re-used clickHandler**
_I am uncertain if this even works, because the internals of vue might still create a new function for every cell?_
``` html
<div>
   <div v-for="row in rows">
      <div v-for="cell in row" @click="clickHandler"></div>
   </div>
</div>
```
``` js
function clickHandler(event) {
    const cell = event.target... // Some logic to find cell data from event
    cell.act()
}
```

**Alternative C - Delegated**
``` html
<div @click="delegatedClickHandler">
   <div v-for="row in rows">
      <div v-for="cell in row"></div>
   </div>
</div>
```
``` js
function delegatedClickHandler(event) {
    const cell = event.target... // Some logic to find cell data from event
    cell.act()
}
```

**Related doc pages:**
- https://vuejs.org/guide/essentials/event-handling.html
- https://vuejs.org/guide/best-practices/performance.html

**Comment by brc-dd** [comment]
C will be much better in terms of performance but IG you made a typo as `@click="clickHandler()` is not necessary if you've already a `@click="delegatedClickHandler"` on parent.

**Comment by Andrioden** [comment]
> C will be much better in terms of performance

I see, could you comment on B? Wouldnt the performance be the same? Will it be one function referenced 10 000 times? I feel B reads better than C.

> but IG you made a typo as @click="clickHandler() is not necessary if you've already a @click="delegatedClickHandler" on parent.

Ah yes, sorry, edited.

**Comment by inblossoms** [comment]
Personally, I think you're thinking the right thing.
 C has the best performance, and the callback for Plan B will be referenced 10,000 times. 
On the contrary, I think Plan C is easier to read.

**Comment by inblossoms** [comment]
> I see, could you give your thought on B? Wouldnt the performance be the same? Will it be one function referenced 10 000 times? I feel B reads better than C.

Personally, I think you're thinking the right thing. 
C has the best performance, and the callback for Plan B will be referenced 10,000 times.
 On the contrary, I think Plan C is easier to read.

**Comment by Andrioden** [comment]
Yeah, i went with C, thanks for your input.

Ill leave the issue open so the repo owners can consider adding documentation for this. If not they can close it.
