### ISSUE TITLE
https://vuejs.org/tutorial/ not found . 

### ISSUE THREAD

**Issue by coollad49** [vuejs/docs#2465]
In clicking the try tutorial at the https://vuejs.org/guide/introduction.html page... It brought 404
![Screenshot_20230807-110612](https://github.com/vuejs/docs/assets/61359635/15d14075-988c-4737-abe2-528d60fabccb)

**Comment by brc-dd** [comment]
Can you try reloading the page. Seems like a network issue to me. https://vuejs.org/tutorial/ opens up fine for me.

**Comment by coollad49** [comment]
Yea.. it worked.. thanks
