### ISSUE TITLE
Dead link on the homepage's "Get Started" button

### ISSUE THREAD

**Issue by eniiku** [vuejs/docs#2474]
![image](https://github.com/vuejs/docs/assets/112134400/7dcd8135-9c36-4e0a-874a-085893fffd9b)
I am taken to a 404 page when I click the Get Started button,

**Comment by brc-dd** [comment]
Can you try reloading your page. It appears to be working fine for me. Might be a network glitch?

**Comment by eniiku** [comment]
It seems to be working now that I modified the link from https://vuejs.org/guide/introduction.html to https://vuejs.org/guide/introduction.
