### ISSUE TITLE
Take over mode will broken code lens

### ISSUE THREAD

**Issue by cary-hu** [vuejs/docs#2478]
Hi volar team,

When I install volar in my project, and follow the [guide](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) to disable buildin TS feature, My code lens broken.
![image](https://github.com/vuejs/docs/assets/41052104/27b868ad-8486-485e-9c51-ea819f22122d)
![image](https://github.com/vuejs/docs/assets/41052104/fd2cfc6a-53b3-4c6b-b2eb-74e0f2edeaca)

Code lens will help me found the code block reference, It's very helpful.

How can I enable code lens when I using volar in my project?

**Comment by brc-dd** [comment]
Don't use takeover mode. You can use the volar typescript plugin instead.
