### ISSUE TITLE
Probable grammar mistake: "State that can trigger updates when changed are considered reactive"

### ISSUE THREAD

**Issue by amire80** [vuejs/docs#2486]
The sentence "State that can trigger updates when changed are considered reactive." appears on https://vuejs.org/tutorial/#step-2

It looks grammatically wrong. It should probably be "A state that can trigger updates when changed is considered reactive." or maybe "States that can trigger updates when changed are considered reactive."

**Comment by ijklim** [comment]
Agree, I vote for "States that can trigger updates when changed are considered reactive.".
