### ISSUE TITLE
wrong description

### ISSUE THREAD

**Issue by 13837678992** [vuejs/docs#2492]
[on this page](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#caveat-when-unwrapping-in-templates )
Caveat when Unwrapping in Templates
> Another thing to note is that a ref does get unwrapped if it is the final evaluated value of a text interpolation (i.e. a {{ }} tag), so the following will render 1:
```js
{{ object.id }}
```
However the result here should be 0

**Comment by hasan75** [comment]
Hi,
I think you are mistaking in somewhere else.
`in script 
 const object = { id: ref(1) };
`
Now in template if we use
` {{ object.id }} `

It renders 1. because the final evaluated value is 1 here. It should not be 0.
