### ISSUE TITLE
Vue DevtoolsMissing search result for Vue Devtools

### ISSUE THREAD

**Issue by DavidCao626** [vuejs/docs#2493]

**Comment by brc-dd** [comment]
Seems to be working for me:

<img width="260" alt="image" src="https://github.com/vuejs/docs/assets/40380293/eba94ecd-9906-4a60-ae0d-436a50b73e2f"> <img width="500" alt="image" src="https://github.com/vuejs/docs/assets/40380293/6b604873-dc8e-4314-950e-a5dd8001c7c6">
