### ISSUE TITLE
Breaking link in Guide => Scaling Up => Testing

### ISSUE THREAD

**Issue by tisma95** [vuejs/docs#2499]
Breaking link found here https://vuejs.org/guide/scaling-up/testing.html#e2e-testing on link [Why Playwright](https://playwright.dev/docs/why-playwright)

![image](https://github.com/vuejs/docs/assets/55036198/81addbe9-1711-45aa-986f-41a511145f88)

**Comment by brc-dd** [comment]
try checking your network. it's working fine for me.

**Comment by tisma95** [comment]
Yes thanks it is in french version the break.
Thanks
