### ISSUE TITLE
Conflicting naming convention of custom event. camelCase or kebab-case?

### ISSUE THREAD

**Issue by leochoo** [vuejs/docs#2503]
Potential conflict in doc: Which naming convention should I use for v-model  custom event for Vue 3?

https://vuejs.org/guide/components/v-model.html -> This uses `camelCase`
https://vuejs.org/guide/components/events.html -> This recommends `kebab-case`
https://eslint.vuejs.org/rules/v-on-event-hyphenation.html -> but this enforces `kebab-case`

**Comment by AloisSeckar** [comment]
The name of the emit defined in a component should be camelCase, but when being listened to in iside parent's template, then kebab-case should be used according to the convention.

The third code snippet in https://vuejs.org/guide/components/v-model.html is inaccurate. Would you like to open a PR? Or I'll do later.

**Comment by leochoo** [comment]
Yes I will open the PR! Thanks for confirming!

**Comment by brc-dd** [comment]
Technically it's correct. `v-model` gets compiled to `update:modelValue` not `update:model-value`, although the latter might be recommended by style guides. (refer JS tab here - https://play.vuejs.org/#eNp9kbFuwjAQhl/FuiWtRGFgQ6FSixjo0FYto5coXEKoY1v2OY0U5d17NiJ0QIy+/7vzd/YAL9bOu4CwgtyXrrEkPFKwz1I3rTWOxCAcVmIUlTOtyBjNpJa6NNpHtHDlcY89iXXEHrLsUep8cZ7EM/hA2FpVEPJJiHwTPJl2p20g0T215oBqLeE6R4JYMJkvpjaYAXm+rmrq+ckbzaZDHCWhNK1tFLoPSw3rSFiJlMSsUMr8vqUauYCzS708Yvlzo37yfaxJ+HTo0XUoYcqocDWyWYy33+/Jcgp5haCYvhN+oTcqRMcz9hr0gbX/ccl2l9670fXeb3tC7S9LRdFIjomXwH+wubP6VXc5X6Y+qUcY/wDG1qNa)

**Comment by AloisSeckar** [comment]
I think for the sake of clarity is better to use kebab-case everywhere in templates, even if it is not stricly necessary in SFCs that are being compiled. If you don't make it a habbit, it may once bite you back while [using in-DOM templates](https://vuejs.org/guide/essentials/component-basics.html#dom-template-parsing-caveats).

Also while using linter, you probably wont get away from that. 

And so it feels better to have it right in the docs. Kudos for @leochoo for spotting it.

**Comment by NataliaTepluhina** [comment]
Closing as https://github.com/vuejs/docs/pull/2504 was merged
