### ISSUE TITLE
Define "getter function"

### ISSUE THREAD

**Issue by nielsbom** [vuejs/docs#2528]
In the [docs](https://github.com/search?q=repo%3Avuejs%2Fdocs+%22getter+function%22&type=code) the term "getter function" seems to be an important concept but it's not defined anywhere that I've found.

Do y'all think it's an idea to define it?

**Comment by bencodezen** [comment]
@nielsbom This is technically a fundamental JS concept, but I could see value in linking to docs since this is a more advanced concept for those new to JavaScript.

I'll issue a PR to help improve this.

**Comment by nielsbom** [comment]
Ah, yeah I don't use those parts of JavaScript directly often. Saying something like "getter functions are a feature of JavaScript itself, see the docs" would already help.
