### ISSUE TITLE
Breaking Link

### ISSUE THREAD

**Issue by tisma95** [vuejs/docs#2530]
https://vuejs.org/guide/best-practices/accessibility.html#resources
Focus indicator link break
![image](https://github.com/vuejs/docs/assets/55036198/de1c9930-5dd7-41ac-8c9e-a2449b280805)

**Comment by abfahimb** [comment]
@brc-dd can you please assign me this issue?

**Comment by brc-dd** [comment]
Assigning issues is not required. Feel free to create a PR. Looks like that extension was removed from webstore due to some policy violations. If someone has a good extension that does something similar, please provide the link.

**Comment by abfahimb** [comment]
@brc-dd is that ok to use? https://chromeload.com/extension-7913-focus-indicator

**Comment by brc-dd** [comment]
Let's not rely on third-party sources. I think we can simply remove that link. NerdeFocus is already listed there which pretty much does the same job.

**Comment by abfahimb** [comment]
@brc-dd Thanks. Let me try to fix this issue

**Comment by abfahimb** [comment]
@brc-dd i have create pr. can you please check and suggest any improvement if needed
