### ISSUE TITLE
Breaking Link

### ISSUE THREAD

**Issue by tisma95** [vuejs/docs#2535]
https://vuejs.org/guide/best-practices/accessibility.html#resources
Focus indicator link break
![image](https://github.com/vuejs/docs/assets/55036198/8028c253-5611-4601-bb04-810aa9125fd4)

**Comment by AloisSeckar** [comment]
The link to https://chrome.google.com/webstore/detail/focus-indicator/heeoeadndnhebmfebjccbhmccmaoedlf doesn't work for me as well...
