### ISSUE TITLE
Twitter Icon Not Updated in Vue.js v2 and v3 Official Websites

### ISSUE THREAD

**Issue by UsmanLiaqat404** [vuejs/docs#2543]
### Vue version

v2 and v3

### Link to minimal reproduction

https://vuejs.org/

### Steps to reproduce

I've noticed that the Twitter icons on both Vue.js v2 (https://v2.vuejs.org/) and Vue.js v3 (https://vuejs.org/) official websites have not been updated to reflect the latest changes made to Twitter's logo. Despite Twitter's logo update, both versions of the Vue.js website continue to display the old Twitter logo.

### What is expected?

Display the latest twitter icon that is X

### What is actually happening?

Displaying Old version of twitter logo

**Comment by stevenks17** [comment]
Can I take this issue on? I believe I have an idea where the change has to happen.

**Comment by stevenks17** [comment]
@brc-dd I still need to alter the icon for v2 of Vue but I don't see where the docs repo is for v2 can you point me in the right direction?

**Comment by brc-dd** [comment]
https://github.com/vuejs/v2.vuejs.org

I don't think anyone is maintaining it though.

**Comment by stevenks17** [comment]
Should I skip making the adjustment then for the vue 2 docs site?  @brc-dd

**Comment by brc-dd** [comment]
Yeah ignore the old there.
