### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by leoniedarois** [vuejs/docs#2547]
dead link here -> https://vuejs.org/guide/forms.html#Radio.

<img width="1643" alt="Capture d’écran 2023-10-25 à 12 06 17" src="https://github.com/vuejs/docs/assets/50202798/56a4b9bc-e32c-481f-a246-68f8fce253ae">

**Comment by brc-dd** [comment]
Hi, can you tell which page has dead link to that?

**Comment by mahmudunnabikajal** [comment]
Thank you, @leoniedarois, for your valuable feedback.

It seems the link you've tried to access doesn't exist. To view the 'Form Input Bindings' documents, please visit the correct link provided below:

🚫 Link You Tried: https://vuejs.org/guide/forms.html
✅ Correct Link: https://vuejs.org/guide/essentials/forms.html

We appreciate your interest and hope this updated link directs you to the intended resource.

close #2547

**Comment by NataliaTepluhina** [comment]
I searched through the repository and I haven't found any link to `/guide/forms`, so most likely this was an external link. I'm closing this issue, please feel free to reopen it with the updated description of the dead link, if the bug reoccurs.
