### ISSUE TITLE
CSS Styles Failed to Load in Simplified Chinese Documentation

### ISSUE THREAD

**Issue by Clownlys** [vuejs/docs#2562]
When I switch from https://vuejs.org/ to https://cn.vuejs.org/ in the Simplified Chinese documentation, the CSS file fails to load. The website appears broken without proper styling when viewing the Simplified Chinese version.
![20231103221849](https://github.com/vuejs/docs/assets/24714577/45de446e-4ecb-4765-8a5f-2e557f9a79d1)

Console error message is as follows.
`Refused to apply style from 'https://cn.vuejs.org/assets/style.f9b4c2a4.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
![20231103222019](https://github.com/vuejs/docs/assets/24714577/97e53f46-486a-4891-bad6-1d98b9ea61db)

**Comment by brc-dd** [comment]
Seems like a cache issue. It's opening fine for me. There was a Netlify incident today, it might be related to that. Can you try doing hard reload (Ctrl + Shift + R) ? Alternatively, try using a different browser or disabling some extension. If the issue persists, try using some other internet or a VPN.

**Comment by brc-dd** [comment]
caused by cloudflare outage. please track https://www.cloudflarestatus.com/
