### ISSUE TITLE
bug : aside style error caused by banner

### ISSUE THREAD

**Issue by heygsc** [vuejs/docs#2571]
<img width="1384" alt="image" src="https://github.com/vuejs/docs/assets/103993866/aecd732a-4bdc-40cd-b567-364b3447fb75">

<br />

<br />

<br />

<br />

<br />

When the banner above exists, a small part of the aside will be missing.

<br />

<br />

<br />

<br />

<br />

<img width="1394" alt="image" src="https://github.com/vuejs/docs/assets/103993866/1d575367-3c04-47c1-9267-bef55ecdb9c5">

<br />

<br />

<br />

<br />

<br />

If we close the banner, it will display as normal.

<br />

<br />

<br />

<img width="301" alt="image" src="https://github.com/vuejs/docs/assets/103993866/cd7d52cb-cd49-4116-bdef-f93d01c2c137">

<br />

<br />

Open console, It can be observed, 
increasing the "top" value, in the style of the "aside-container"class,
may fix this error.

This bug may not be related to this repo, or it may be related to the "vitepress".

In fact, through the package.json file, it can be found that the version of "vitepress" is not the latest version. 
Currently,  "aside-container" class in this repo is "position:sticky", and in a commit of "vitepress"     (https://github.com/vuejs/vitepress/commit/aecdeb9b216803f407fe3b48574bf7664262ef01 )     , it has been changed to "fixed".

So I'm not sure if it's a problem with this repo,or with "vitepress" at the moment.

Welcome team members and others to to share their ideas. 
I am happy to fix it with a PR. 😂

**Comment by brc-dd** [comment]
Nah that `--vt-banner-height` should be set to 70px. That vue mastery PR probably missed that. Contributions are welcome.

**Comment by heygsc** [comment]
@brc-dd  Hi, I submitted a PR https://github.com/vuejs/docs/pull/2572
