### ISSUE TITLE
The retry function is undefined  in the composables section

### ISSUE THREAD

**Issue by tidycode** [vuejs/docs#2576]
docs link:https://vuejs.org/guide/reusability/composables.html#async-state-example   ,in the section    [the updated version of useFetch()](https://play.vuejs.org/#eNp9VNtu4zgM/RWuX+JiM3YXxb4USbC3LrCLuaFzefKLYtONWkcyJCppEOTfh5RsN5kpBmiRhCIPzzmkdMz+7PtiFzC7zRa+dron8EihX1VGb3vrCI7gsJ1Dbbd9IGzgBK2zW5hx0ewsKXj8F6neTOdFOYaKR8+Zlamt8QRr5fGL62AJsw1R72/L8tFb03eqxo3tGnQFHXpd2wYLblqSbawvGSCV64YrmVE++212NQZDxBsp5vkVLFdTo1+5ptipLiDnjxVHaBSpOaBz1s0ZkNyBqS8nHTljcv6iTK6wH/yDcMs8CfkXwFurGuht5HQrgcU6EFkDuzetdcsq06AN/F5l8Efd6fpJIkJeV9nqeAQNp9OiTCURvaJFo3dcrVtOjcQ4U4AZul99sL3/Be4kDMgqgiF02NwCY8XkYoveqweMuDLAWDhwmihEpYx7L59n/Tm15PbpW+KBncdERrzimn/4AzqWLW0XvUPRIWepJf9+FWMlTmnzUBTFeL4oJyuzeXa2KLyHl3u3V3xw17ZY0xzIfpU5freDlcHnWNIGU5NmtRdDhKPwSWOPZNP+mNDJgMeTaOH3R/J/RiBX/mBqSOsVUQHKkkv4yoAnVgNr5NkjtNI9Sk5Z0jftILcQ+BROc/sxfg5tux0CbTAueUoVFhtnjQ2+O4C3oGnmgZyqn/iCKg9qAmiwR9PwvhxgfbjQEgWO6hk7ObscPR72/4WNXJBBc0RWjnSra606btKpAzBbZRoeS1pdsY8A1F5pAtJbtGFoKmEGCEa8voK97jq5gMGZqJOjg07dJmVKYnJBhtaW09xe++RLyo0oa6kWoGjDG+0HAZRUspssMDGKExKRUa28DBH9YlApk6t4Ma0ZHTtBLTZCjsNq/ThJHDLl4xRfHRgVXjw8ksF/lXnFz8pM6zy5l/oNSAb38JGvAfuQ58OiyEv2yNM931Bezs8DwMXmgvibv1O0KdLg+HQF18XNmSxpFoFH8SJf7vRlirTMhU98nvLZfVqE+Gt29VI62DKHm+vrGBVzTvwCkOcJtfohGs1vQESvMnnRdYfuQy8++Crj124Yaaa6zu7/jzFyAedjvN5g/fRK/NE/S6zKPsp9dTussumMlHtASsd3n97jM3+fDre2CR1n/+TwXkwKwjGl/RVMw7TP8iLb/+LLxs/CZ3/3TGj8KEqIRjtifpXxu/b3T6S/0L0pbmKduHj6BqMzlM8=)   

the playground code like that
`const { data, error, retry } = useFetch(url)`

but 'retry' is undefined ,and it was  not exported from the useFetch.js

When you click  'Retry' button, nothing happened

**Comment by tidycode** [comment]
I believe the simplest way is to define the retry function in the App.vue ,not return from useFetch.js

change
`const { data, error, retry } = useFetch(url)`
to
`const { data, error } =useFetch(url)
 retry=()=>{
  const tmp=id.value
  id.value=''
  id.value=tmp
}`
here is the SFC Playground [link](https://play.vuejs.org/#eNp9VU1v40YM/SusLpJRr5Qi6CWwjH6lQIu2u0i3Pekylqh4EnlGmBnZMQz/9yU5kmJngz0YkjjkI98jhz4lP/d9vh8wuUtWvna6D+AxDP26MnrXWxfgBA7bJdR21w8BGzhD6+wOUgpKL5wGj79jqLfzeV5MpvzJk2dlamt8gI3y+J/roIR0G0Lv74riyVvTd6rGre0adHk49rq2DeaUtAi2sb4ggBiuG4qkirL0h3QxGQfBm0rMsgWU6znR9xST71U3IPlPESdoVFBLQOeso5rLmUBGYDOww+COZbYo16fJFHZ9OQES//GtTFmM6YN8KnOuzKqImpKa9BFwRywD0hfAX1Y10FthdMeG1WYIwRrYf2itK6tEgzbwY5XAT3Wn62e2MHVdJevTCTScz6sihgh6FVaN3lO0bslVaJEnAxN0v/5oe/8d3AtbJCaDCeiwuQPCEud8h96rRxRcbr8EjjXNJYgehPvAz4v85FpQ+vgW68DOYyyGlaaY3+gBHdHmtKveIfPgs5iSvt/FWLNS2jzmeT6dr4pZymSZXIwZTfH11B4UHdy3LdZhCcH+z915M8GVwRcJaQdTB01sryYBqPFAo8Wtl2Lj9Jmh4ymZTuIYvTni30UBmfJHU0McTkEFKAoKoQsHPhAb2CD1HqHl7EI5enHeOFmUguGjOfbta/sltO32CGGLckWiK1exddbYwXdH8BZ0SD0Ep+pnut7Kg5oBGuzRNDQvR9gcr7gIwYk9YUdly0nj8RK9VkPjMnEWZOWCbnWtVUdJOnUEqlaZhtoSR5flCwDqoDRdOb1DO4xJ2UwAg2GtF3DQXcfXdHBGeJJ15KnbyEyxjS/ImNqSmztoH3WJvoKy4WgGEhk+aD8SCNMu8EQwViQdYpLClveKoF81KnpSFA2mNZNiZ6hZRshwHK2vO0lrRTz5cZadBRPDN2tLlkxl3tGzMvM4z+rFfCOSwQN8omtAOmTZOChLOnyi7l5OKA3n5xHganKB9c3+VmGbx8bR6Rpu8tsLWpxMgCfyTJ/v9LULp8y4HllPWfoQB0G+0sVr6CjLEm5vbsTK4pxpAwRPHWr1owhNO0DQq4T/D3SH7mPPOvgqoW03tjRRXWcPf4otuAGXk73eYv38jv3Jv7CtSj7xfXV7rJL5LCj3iCEe3//7D77Q+3y4s83Qkfc3Dh9YpIFrjG6/DKahsi/8pNo/ZLPRWvjs718CGj+R4kJFDvGvEtprv36D+mu5t/mtxLGK5y9sCqvz)

**Comment by heygsc** [comment]
> docs link:https://vuejs.org/guide/reusability/composables.html#async-state-example ,in the section [the updated version of useFetch()](https://play.vuejs.org/#eNp9VNtu4zgM/RWuX+JiM3YXxb4USbC3LrCLuaFzefKLYtONWkcyJCppEOTfh5RsN5kpBmiRhCIPzzmkdMz+7PtiFzC7zRa+dron8EihX1VGb3vrCI7gsJ1Dbbd9IGzgBK2zW5hx0ewsKXj8F6neTOdFOYaKR8+Zlamt8QRr5fGL62AJsw1R72/L8tFb03eqxo3tGnQFHXpd2wYLblqSbawvGSCV64YrmVE++212NQZDxBsp5vkVLFdTo1+5ptipLiDnjxVHaBSpOaBz1s0ZkNyBqS8nHTljcv6iTK6wH/yDcMs8CfkXwFurGuht5HQrgcU6EFkDuzetdcsq06AN/F5l8Efd6fpJIkJeV9nqeAQNp9OiTCURvaJFo3dcrVtOjcQ4U4AZul99sL3/Be4kDMgqgiF02NwCY8XkYoveqweMuDLAWDhwmihEpYx7L59n/Tm15PbpW+KBncdERrzimn/4AzqWLW0XvUPRIWepJf9+FWMlTmnzUBTFeL4oJyuzeXa2KLyHl3u3V3xw17ZY0xzIfpU5freDlcHnWNIGU5NmtRdDhKPwSWOPZNP+mNDJgMeTaOH3R/J/RiBX/mBqSOsVUQHKkkv4yoAnVgNr5NkjtNI9Sk5Z0jftILcQ+BROc/sxfg5tux0CbTAueUoVFhtnjQ2+O4C3oGnmgZyqn/iCKg9qAmiwR9PwvhxgfbjQEgWO6hk7ObscPR72/4WNXJBBc0RWjnSra606btKpAzBbZRoeS1pdsY8A1F5pAtJbtGFoKmEGCEa8voK97jq5gMGZqJOjg07dJmVKYnJBhtaW09xe++RLyo0oa6kWoGjDG+0HAZRUspssMDGKExKRUa28DBH9YlApk6t4Ma0ZHTtBLTZCjsNq/ThJHDLl4xRfHRgVXjw8ksF/lXnFz8pM6zy5l/oNSAb38JGvAfuQ58OiyEv2yNM931Bezs8DwMXmgvibv1O0KdLg+HQF18XNmSxpFoFH8SJf7vRlirTMhU98nvLZfVqE+Gt29VI62DKHm+vrGBVzTvwCkOcJtfohGs1vQESvMnnRdYfuQy8++Crj124Yaaa6zu7/jzFyAedjvN5g/fRK/NE/S6zKPsp9dTussumMlHtASsd3n97jM3+fDre2CR1n/+TwXkwKwjGl/RVMw7TP8iLb/+LLxs/CZ3/3TGj8KEqIRjtifpXxu/b3T6S/0L0pbmKduHj6BqMzlM8=)
> 
> the playground code like that `const { data, error, retry } = useFetch(url)`
> 
> but 'retry' is undefined ,and it was not exported from the useFetch.js
> 
> When you click 'Retry' button, nothing happened

maybe because 'retry' didn't return from ' useFetch.js' ?

**Comment by tidycode** [comment]
> > docs link:https://vuejs.org/guide/reusability/composables.html#async-state-example ,in the section [the updated version of useFetch()](https://play.vuejs.org/#eNp9VNtu4zgM/RWuX+JiM3YXxb4USbC3LrCLuaFzefKLYtONWkcyJCppEOTfh5RsN5kpBmiRhCIPzzmkdMz+7PtiFzC7zRa+dron8EihX1VGb3vrCI7gsJ1Dbbd9IGzgBK2zW5hx0ewsKXj8F6neTOdFOYaKR8+Zlamt8QRr5fGL62AJsw1R72/L8tFb03eqxo3tGnQFHXpd2wYLblqSbawvGSCV64YrmVE++212NQZDxBsp5vkVLFdTo1+5ptipLiDnjxVHaBSpOaBz1s0ZkNyBqS8nHTljcv6iTK6wH/yDcMs8CfkXwFurGuht5HQrgcU6EFkDuzetdcsq06AN/F5l8Efd6fpJIkJeV9nqeAQNp9OiTCURvaJFo3dcrVtOjcQ4U4AZul99sL3/Be4kDMgqgiF02NwCY8XkYoveqweMuDLAWDhwmihEpYx7L59n/Tm15PbpW+KBncdERrzimn/4AzqWLW0XvUPRIWepJf9+FWMlTmnzUBTFeL4oJyuzeXa2KLyHl3u3V3xw17ZY0xzIfpU5freDlcHnWNIGU5NmtRdDhKPwSWOPZNP+mNDJgMeTaOH3R/J/RiBX/mBqSOsVUQHKkkv4yoAnVgNr5NkjtNI9Sk5Z0jftILcQ+BROc/sxfg5tux0CbTAueUoVFhtnjQ2+O4C3oGnmgZyqn/iCKg9qAmiwR9PwvhxgfbjQEgWO6hk7ObscPR72/4WNXJBBc0RWjnSra606btKpAzBbZRoeS1pdsY8A1F5pAtJbtGFoKmEGCEa8voK97jq5gMGZqJOjg07dJmVKYnJBhtaW09xe++RLyo0oa6kWoGjDG+0HAZRUspssMDGKExKRUa28DBH9YlApk6t4Ma0ZHTtBLTZCjsNq/ThJHDLl4xRfHRgVXjw8ksF/lXnFz8pM6zy5l/oNSAb38JGvAfuQ58OiyEv2yNM931Bezs8DwMXmgvibv1O0KdLg+HQF18XNmSxpFoFH8SJf7vRlirTMhU98nvLZfVqE+Gt29VI62DKHm+vrGBVzTvwCkOcJtfohGs1vQESvMnnRdYfuQy8++Crj124Yaaa6zu7/jzFyAedjvN5g/fRK/NE/S6zKPsp9dTussumMlHtASsd3n97jM3+fDre2CR1n/+TwXkwKwjGl/RVMw7TP8iLb/+LLxs/CZ3/3TGj8KEqIRjtifpXxu/b3T6S/0L0pbmKduHj6BqMzlM8=)
> > the playground code like that `const { data, error, retry } = useFetch(url)`
> > but 'retry' is undefined ,and it was not exported from the useFetch.js
> > When you click 'Retry' button, nothing happened
> 
> maybe because 'retry' didn't return in ' useFetch.js' ?

I thinks so ,I tried to define the retry function in 'useFetch.js',but the watchEffect watches the ref ID, and the ref ID was defined in the App.vue.
So the  simplest way is define the 'retry' function in the App.vue,I think

**Comment by heygsc** [comment]
i submitted a pr : https://github.com/vuejs/docs/pull/2578 
let's take a look together
