### ISSUE TITLE
"Using JavaScript Expressions" has accidentally escaped code

### ISSUE THREAD

**Issue by joezimjs** [vuejs/docs#2586]
https://vuejs.org/guide/essentials/template-syntax.html#using-javascript-expressions

![image](https://github.com/vuejs/docs/assets/1313898/a5805915-f589-40c5-82ce-9203c1f2f6bd)

The next 2 code samples in that section also have the same issue.

**Comment by NataliaTepluhina** [comment]
I added a temporary fix in https://github.com/vuejs/docs/commit/95ec9ea957404ff559df438bb00e1f14ce2a4af2, replacing `vue-html` with `html` blocks. This seems to render the mustache expressions correctly but probably should be fixed in the theme

/cc @brc-dd

**Comment by brc-dd** [comment]
Yeah I'll try to fix that in theme/vitepress by weekend.
