### ISSUE TITLE
Extra Topics --> Composition API FAQ Image Code Comparison is low-resolution and Blurry

### ISSUE THREAD

**Issue by kathleenwestPayItGov** [vuejs/docs#2617]
The image https://vuejs.org/assets/composition-api-after.GV7JGP99.png is low res and blurry while viewing from the extra topics --> composition api faq page (and after clicking view image in separate browser window). Recommend adding a link to high res picture or using code block comparisons.

**Comment by brc-dd** [comment]
I don't think the intention of that image is to show the actual code difference. It's more like giving a general idea of how the code organization differs between the two patterns.

**Comment by kathleenwestPayItGov** [comment]
@brc-dd ,  I don't see any code organization differences because of the low-res.

**Comment by pikax** [comment]
The purpose of the image is to convey the colour organisation between Options-API vs Composition-API implementation, if you read the context where that image is used you can see the places were it refers to the original files https://vuejs.org/guide/extras/composition-api-faq.html
<img width="619" alt="image" src="https://github.com/vuejs/docs/assets/4620458/92c2dc4e-6c91-4140-99ae-3e78aa73fa0b">

**Comment by kathleenwestPayItGov** [comment]
Ok... still not understanding why there could not be a larger-res version of the color organized image so we could actually see the code @pikax

**Comment by pikax** [comment]
@kathleenwestPayItGov most likely there's no high Res image of that available anymore, which means a new one would need to be done, PR is welcomed.

Both of the source files are publicly available and you can read both easily, IMO the current Res is enough to understand a pro of using the composition API in comparison with options API, that's what the docs are trying to convey.
