### ISSUE TITLE
Tutorial - Declarative Rendering - Google Chrome Browser Warning

### ISSUE THREAD

**Issue by kathleenwestPayItGov** [vuejs/docs#2627]
URL: https://vuejs.org/tutorial/#step-2
API Preferences: Options, HTML

The tutorial code should be updated from 
`import { createApp } from 'vue'`
to 
`import { createApp } from 'vue/dist/vue.esm-bundler.js'`
or include a side note on the page for the code change to be compatible with Google Chrome.

This is the warning, however the html does not render on the page unless this is fixed

`tutorial.html:7 [Vue warn]: Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js". 
  at <App>
warn2 @ chunk-EFQI2HPI.js?v=4a8bb179:1518
finishComponentSetup @ chunk-EFQI2HPI.js?v=4a8bb179:8905
setupStatefulComponent @ chunk-EFQI2HPI.js?v=4a8bb179:8820
setupComponent @ chunk-EFQI2HPI.js?v=4a8bb179:8752
mountComponent @ chunk-EFQI2HPI.js?v=4a8bb179:7150
processComponent @ chunk-EFQI2HPI.js?v=4a8bb179:7116
patch @ chunk-EFQI2HPI.js?v=4a8bb179:6589
render2 @ chunk-EFQI2HPI.js?v=4a8bb179:7883
mount @ chunk-EFQI2HPI.js?v=4a8bb179:5311
app.mount @ chunk-EFQI2HPI.js?v=4a8bb179:10889
(anonymous) @ tutorial.html:7
Show 10 more frames
Show less`

**Comment by brc-dd** [comment]
Can you try hard reloading the page once? I'm not seeing any such warning.

**Comment by kathleenwestPayItGov** [comment]
@brc-dd in order to re-create the browser warning issue, you will need to copy the code to an independent html file and run it locally.

**Comment by kathleenwestPayItGov** [comment]
This is the working version for your reference:
https://github.com/kathleenwestPayItGov/my-first-vue-project/blob/main/tutorial.html

**Comment by NataliaTepluhina** [comment]
@kathleenwestPayItGov did you create a Vite project with Vue plugin from scratch? I cannot reproduce the same issue on the clean project and I suspect there is an issue with your bundler/Vue build. In any case, this is not the problem with docs, the import from Vue is correct so I am going to close an issue. I suggest to ask the question about this particular error in [VueLand Discord](https://discord.com/channels/325477692906536972/325654285255704578)

**Comment by kathleenwestPayItGov** [comment]
@NataliaTepluhina This marks the _second_ issue/time that I have been dismissed for reporting bugs/issues on the vue tutorial documentation. As such, this has been a very frustrating experience to participate in reporting issues to the vue project. I'm not sure if feedback for code and documentation improvements is receptive in this project community? 

To make understanding of the problem explicit, I have recreated the vue tutorial with the abbreviated import here in the file here: https://github.com/kathleenwestPayItGov/my-first-vue-project/blob/main/tutorial_bug.html#L6 this is in contrast to the working version (with a full import) https://github.com/kathleenwestPayItGov/my-first-vue-project/blob/main/tutorial.html#L6 that I figured out on my own trying to hack/get the given tutorial code to work. _This is the correct way to code the tutorial project in a stand-alone-file and as-is on the tutorial site, the site code is non-functional._ 

You will need to run the file
`> npm run dev`

![image](https://github.com/vuejs/docs/assets/152927592/a5272ebc-5f5e-4d89-af60-773d6252ff2f)

**Comment by AloisSeckar** [comment]
I would suspect importing "vue" from "

**Comment by AloisSeckar** [comment]
> @kathleenwestPayItGov did you create a Vite project with Vue plugin from scratch?

For the record: I just scaffolded brand new app using `npm create vite@latest my-vue-app -- --template vue`, copied the linked file https://github.com/kathleenwestPayItGov/my-first-vue-project/blob/main/tutorial_bug.html and I am getting the same error when visiting http://localhost:5173/tutorial_bug.html

Vite: v5.0.10
@vitejs/plugin-vue: v4.6.2

Node.js : v18.14.2 (might be the cause?)

**Comment by kathleenwestPayItGov** [comment]
@AloisSeckar yes, I did create my new vue project from scratch with the template generation. Keep in mind, I was coming at this tutorial with 0% vue experience when I encountered this error. I saw your previous note about vue import referencing the plugin in the template generated config, so that is probably the root cause of the issue. I am running it with 
node -v
v20.10.0

**Comment by brc-dd** [comment]
>  I am getting the same error

That's because it is not intended to be used like that. You both are trying to use in-browser template compilation which requires esm-bundler build - https://vuejs.org/guide/scaling-up/tooling.html#note-on-in-browser-template-compilation

You need to update your vite.config.ts to do something like this:

```ts
    resolve: {
      alias: {
        vue: 'vue/dist/vue.esm-bundler.js',
        // .. other stuff
      },
    },
```

**Comment by AloisSeckar** [comment]
@brc-dd thanks for explaining

Now I just wonder - is there a way to improve Tutorial to avoid such confusion in the future? Like adding some note into https://vuejs.org/tutorial/#step-1 ? Would you say it is worth trying? (I am willing to prepare such text and open PR)

**Comment by kathleenwestPayItGov** [comment]
Per @brc-dd suggestion, I updated the config to add the vue alias, and it resolves the original issue. 
Would there be cons if that alias were part of the default file vite.config.ts from the template generation process? If not, I suggest adding that to the code base or making a note in the tutorials. Thanks

**Comment by brc-dd** [comment]
> Would there be cons if that alias were part of the default file vite.config.ts

It'll increase bundle size and is not needed for the recommended SFC based setup.
