### ISSUE TITLE
Options: Misc - inheritAttrs - what is the difference in examples?

### ISSUE THREAD

**Issue by AloisSeckar** [vuejs/docs#2629]
The two Composition API examples for [inheritAttrs API page](https://vuejs.org/api/options-misc.html#inheritattrs) look pretty much same to me 👀 

![image](https://github.com/vuejs/docs/assets/7399922/4c2a9ad8-7196-4789-984c-a36d62d2e128)

 Was there a difference prior to Vue 3.3? Should something be restored to point the difference out? Or does the second "variant" become obsolete now and should be removed?

**Comment by AloisSeckar** [comment]
And talking about this page, also this sentence at the bottom of [directives](https://vuejs.org/api/options-misc.html#directives) looks like an orphan without clear meaning to me:

![image](https://github.com/vuejs/docs/assets/7399922/ee0f3b95-3d84-4255-b3fd-fbb0f7741128)

**Comment by brc-dd** [comment]
Ah, the older syntax was something like this:

```vue
<script>
export default {
  inheritAttrs: false
}
</script>
```

We probably can update the docs to change the second paragraph to something like:

````md
On versions **older** than 3.3, you need to specify `inheritAttrs` in `<script>` block instead:

```vue
<script setup>
defineProps(['label', 'value'])
defineEmits(['input'])
</script>

<script>
export default {
  inheritAttrs: false
}
</script>

<template>
  <label>
    {{ label }}
    <input
      v-bind="$attrs"
      v-bind:value="value"
      v-on:input="$emit('input', $event.target.value)"
    />
  </label>
</template>
```
````

> also this sentence at the very bottom of [directives](https://vuejs.org/api/options-misc.html#directives) looks like an orphan

Yeah, it can be removed.
