### ISSUE TITLE
dead link vue lifecycle image 

### ISSUE THREAD

**Issue by ittid** [vuejs/docs#2634]
https://vuejs.org/assets/lifecycle.16e4c08e.png

**Comment by brc-dd** [comment]
Can you try hard reloading [the lifecycle page](https://vuejs.org/guide/essentials/lifecycle) (ctrl/cmd + shift + r)? It's most likely a cache issue. The new link should be something like https://vuejs.org/assets/lifecycle.DLmSwRQE.png

**Comment by ittid** [comment]
i try a hard reload, but still don't get the image:
Here is what i get:
![image](https://github.com/vuejs/docs/assets/44928080/25f517b6-2471-48ea-a788-aed4d2921d03)
But the new url work fine, so thank you

**Comment by brc-dd** [comment]
Why are you directly opening that image? It doesn't exist. This page has that image - https://vuejs.org/guide/essentials/lifecycle where it should show fine.

**Comment by pikax** [comment]
@ittid I suspect that link was used in some other website, we don't support direct link to a resource, when the docs are released a new file may be generated, direct referencing it on an external resource is not advisable, referencing the github image is preferred (https://github.com/vuejs/docs/blob/80d2246f77c04c8c9d5203b6877c8a9a5999c84c/src/guide/essentials/images/lifecycle.png) 

The reason the file has different names is to cause cache invalidation, you can search online for better explanation (eg: [stackoverflow](https://stackoverflow.com/questions/47290012/why-use-hashed-css-stylesheet-and-javascript-file-names#:~:text=JavaScript%20and%20CSS%20is%20often%20built%20into%20a,forces%20a%20cache%20invalidation%20whenever%20the%20file%20changes)
