### ISSUE TITLE
Document quirks with defineModel's default value

### ISSUE THREAD

**Issue by briankchan** [vuejs/docs#2650]
According to the current documentation, `defineModel` is meant to help with defining a two-way binding between refs in a parent/child component. However, using the default value feature provided by the `defineProps` API can cause the refs to go out of sync:

```
// child component:
const model = defineModel({default: 1})

// parent component:
const myRef = ref()

<Child v-model="myRef">

// now, the parent's `myRef` is undefined, but the child's `model` is 1
```

Furthermore, it's not possible to keep the the parent/child values synchronized in all cases as long as a default value exists. E.g., if we attempt to add a `watch` to the child to update the parent:

```
// code added to child component to attempt to emit the default value to update the parent ref:
watchEffect(() => model.value = model.value)
```

the watch will not run when the parent ref changes between `undefined` and the default value:

```
// sequence of updates in the parent component that desyncs the values:
myRef.value = 2         // after running this, myRef == 2 and model == 2
myRef.value = 1         // after running this, myRef == 1 and model == 1
myRef.value = undefined // after running this, myRef == undefined and model == 1
// watchEffect did not run because the value of the model did not change
```

The workaround that properly keeps the two values in sync is to not use `default` with `defineModel`:

```
// child component:
const model = defineModel()

watchEffect(() => {
  if (model.value === undefined) model.value = 1
})
```

The documentation should at least note this edge case, but I'm not sure whether it would be better to discourage use of `default` for `defineModel` entirely given that the alternative isn't too verbose--the only real downside compared to using `default` that I can think of is that the TypeScript type for `model` would include `undefined`.

For more context/runnable examples, see vuejs/core#9987

**Comment by NataliaTepluhina** [comment]
@briankchan thank you for bringing this up! _Ideally_, I believe that `defineModel` should always create a required prop - this way we would be able to remove `default` completely. Since it's not the case, I think that the best addition to docs would be:

- a warning at the end of https://vuejs.org/guide/components/v-model.html#under-the-hood mentioning that `default` can cause a de-sync between parent and child components;
- maybe a bit more detailed explanation/workaround in https://vuejs.org/api/sfc-script-setup.html#definemodel

What do you think?

**Comment by briankchan** [comment]
Yeah, that sounds about right to me.

**Comment by NataliaTepluhina** [comment]
Added the warnings in https://github.com/vuejs/docs/commit/321453fb1be83aa16e1da091ad76e03b95fe1a73
