### ISSUE TITLE
 The component demo encounters an error

### ISSUE THREAD

**Issue by tsinghua-lau** [vuejs/docs#2671]
# Teleport
## This is a minor error, or there might be a misconfiguration somewhere.
<img width="1229" alt="image" src="https://github.com/vuejs/docs/assets/43164478/d4084245-6bd8-42a1-b1c7-f3fddb1035c8">
<img width="1400" alt="image" src="https://github.com/vuejs/docs/assets/43164478/e5351962-ec25-42b0-855d-f308826cfb92">
<img width="1668" alt="image" src="https://github.com/vuejs/docs/assets/43164478/29ebebd6-c4c9-4251-a25e-d198da2d8d5b">

**Comment by bencodezen** [comment]
It looks like this should be fixed now. Feel free to re-open the issue if you still see it on your end!
