### ISSUE TITLE
Dead links: `https://vuejs.org/errors/#compiler-${code}`

### ISSUE THREAD

**Issue by boutils** [vuejs/docs#2672]
Vue compiler (function named `createCompilerError`) can generate errors with a code and a link, something with the following format: `https://vuejs.org/errors/#compiler-${code}`.

These links are dead (error 404), and then, it is very hard to understand the origin of this error. Especially when `process.env.NODE_ENV === "production"`.

Can you please fix these links?

Thanks a ton

**Comment by brc-dd** [comment]
Should be fixed in the core instead. The links should be to `https://vuejs.org/error-reference/#stuff`

**Comment by boutils** [comment]
@brc-dd Thanks for giving the right url. Should I close this issue and open a new on in the `core` repo?

**Comment by brc-dd** [comment]
I'll ask internally which is desirable and update the code/docs.

**Comment by brc-dd** [comment]
fixed in https://github.com/vuejs/core/commit/c3087ff2cce7d96c60a870f8233441311ab4dfb4
