### ISSUE TITLE
For translations, shall we provide the source files of all the diagrams & illustrations?

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/docs#2685]
just like what we did for v2 docs https://github.com/vuejs/v2.vuejs.org/tree/master/assets

then as translators people can modify the text and do necessary re-layout inside and export as their own versions, at the same time, keep tracking their update here.

Known diagrams & illustrations need to be translated:

- Directive syntax in `/guide/essentials/template-syntax`
- Component lifecycle in `/guide/essentials/lifecycle`
- Component scheme in `/guide/essentials/component-basics`

Refs:

https://github.com/vuejs-translations/docs-zh-cn/issues/643
https://github.com/vuejs-translations/docs-cs/issues/29

Thanks.

**Comment by bencodezen** [comment]
Hey @Jinjiang! Sorry for the delay in updating this issue, but Evan linked all of the Figma diagrams in comments:

https://github.com/search?q=repo%3Avuejs%2Fdocs%20figma&type=code

Hope this helps!
