### ISSUE TITLE
typo in tutorial - step 2

### ISSUE THREAD

**Issue by thanosolo** [vuejs/docs#2688]
As I was going through the tutorial I noticed a sentence that seems incorrect:

https://vuejs.org/tutorial/#step-2

`State that can trigger updates when changed are considered reactive.`

This should either be `States that can trigger updates when changed are considered reactive.` or `State that can trigger updates when changed is considered reactive.`

**Comment by NataliaTepluhina** [comment]
Closing an issue as the related PR was merged
