### ISSUE TITLE
defineModel equivalence explanation incomplete

### ISSUE THREAD

**Issue by Korijn** [vuejs/docs#2700]
In the guide we can see the following:

![image](https://github.com/vuejs/docs/assets/1882046/908c536a-e3bd-4e31-b281-f3a458adc7ed)

The code example is actually not equivalent, it's missing a piece.

The text actually does state what the missing piece of code should be:

> An event named `update:modelValue`, which is emitted when the local ref's value is mutated.

This is the actual equivalent code (note the `watch` expression which is added):

```vue
<script setup>
import { watch } from 'vue';

const props = defineProps(['modelValue'])
const emit = defineEmits(['update:modelValue'])

// start missing code
watch(() => props.modelValue, () => {
  emit('update:modelValue', props.modelValue);
});
// end missing code
</script>

<template>
  <input
    :value="props.modelValue"
    @input="emit('update:modelValue', $event.target.value)"
  />
</template>
```

In terms of behavior, the difference is subtle but important:

* without the `watch` statement, the `update:modelValue` event will only be emitted when there is an `input` event on the `<input>`
* with the `watch` statement, the `update:modelValue` will also be emitted when the prop value is modified

The second case is equivalent to `defineModel` behavior, but the docs present the first case as though it is equivalent.

This led to quite some confusion and misunderstanding in my team today!

After reviewing the code in vue, it seems this is where we can see the evidence:

https://github.com/vuejs/core/blob/272ab9fbdcb1af0535108b9f888e80d612f9171d/packages/runtime-core/src/helpers/useModel.ts#L65

**Comment by NataliaTepluhina** [comment]
@Korijn I don't think that the code you suggest is correct. If you create a sandbox where the model can be updated from both the parent component and the child component and look at the component events in Vue devtools, you will notice that `update:modelValue` is not emitted by child when parent updates the model. [Here](https://play.vuejs.org/#eNqFUstOwzAQ/JXFl4AEjRA3FCoeQgIkHuIhLr6UZNsaHNuyN6VSlH9n7TTQSgVOiXfG49ndacWZc6NFg+JYFKH0yhEEpMaNpVG1s56gBY9T6GDqbQ0ZU7Nv6MLWblUf5fEQlRiWprQmENRhBifx+m52hVpbeLVeVzvZ3kBwE4+Gbm2FeiA+2RqBcEmRVeS9J3bDB8La6QkhnwCK+eG4bTcUuq7IuZrQt4bIGjgttSo/TqTYeCm7pzn6/hUpxi+uYlWoE5ja6dlF3qv0iqnZxUFibQpKATlzinzNoNgXFLjJqZqN3oM1PN82ykhRso7S6O8dKR6CFMeQkIhNeEifN6lGvsH9oV7OsfzYUn8Py1iT4sFjQL9AKb4xmvgZUg9fPt1xr2sgd9FoZv8BPmKwuokee9p5Yyq2vcZLbq9TFJSZPYfLJaEJQ1PRaGR2iS8FRyOO8LfWf+wejY7SPWk6nuIQqy0BBVjFbJWfCqfKYFrJ7j/hqdQi/fCvMq6htcWmrxRxoxFv21To2A6T8/7i5qq7L2TvGoY=) is a simple implementation to test this behavior.

As for the code you refer to, in the condition in the setter, we're checking whether the parent component has declared a model. If not, we update `localValue` only (there is no point in emitting the event as the parent is not listening to it). If yes, we also emit an event to the parent.
