### ISSUE TITLE
Remove/update Volar Takeover Mode

### ISSUE THREAD

**Issue by stefnotch** [vuejs/docs#2723]
The Volar Takeover Mode section of the documentation https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode
talks about the "TypeScript Vue Plugin" extension. However, that extension has been deprecated today.

https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#200-202432

**Comment by brc-dd** [comment]
PR is welcome. But I would recommend to stay on v1 for a bit longer as the v2 extension has quite a few regressions. We probably can merge that after a week or so.

**Comment by ledarteaga** [comment]
Is there a way to enable Volar again in my workspace? I'm experience intellisense errors after uninstalling the deprecated Volar extension. 

The intellisense status won't stop loading. Any help or feedback is appreciated. 

![image](https://github.com/vuejs/docs/assets/57638833/7b93cbba-62c6-4333-b663-f6292a8b0591)

**Comment by brc-dd** [comment]
@ledarteaga Feel free to keep using v1 for now. You can also create an issue at https://github.com/vuejs/language-tools with a reproducible example and system details.
