### ISSUE TITLE
https://cn.vuejs.org/布局崩了

### ISSUE THREAD

**Issue by Yolo-00** [vuejs/docs#2742]
![image](https://github.com/vuejs/docs/assets/129492349/876bb9c7-5728-4183-9341-953bb155ee82)

**Comment by brc-dd** [comment]
Try disabling your VPN.

**Comment by baiwusanyu-c** [comment]
I turned off the VPN and the problem recurred. Some people in mainland China also had the problem today. I suspect there is a problem with the CDN?

**Comment by Yolo-00** [comment]
目前开启VPN和关闭VPN都不行

**Comment by baiwusanyu-c** [comment]
清清缓存试试

**Comment by brc-dd** [comment]
Some people were encountering it yesterday too - https://github.com/vuejs/docs/issues/2740

Most likely a vercel or cloudflare issue if others are also not able to access.

**Comment by sxzz** [comment]
Let's track the issue https://github.com/vuejs-translations/docs-zh-cn/issues/881
