### ISSUE TITLE
[Bug] code syntax highlight doesn't work as expected

### ISSUE THREAD

**Issue by awxiaoxian2020** [vuejs/docs#2748]
https://vuejs.org/guide/quick-start.html#creating-a-vue-application

![bug-highlight](https://github.com/vuejs/docs/assets/69554233/2b3acdb8-2d50-44d0-b392-1014082a82fd)

**Comment by awxiaoxian2020** [comment]
ping @brc-dd to confirm :)

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/3446

We can do that workaround here.
