### ISSUE TITLE
cn: web page style loading error

### ISSUE THREAD

**Issue by RSS1102** [vuejs/docs#2766]
https://cn.vuejs.org/guide/introduction.html

![image](https://github.com/vuejs/docs/assets/81673017/816aa605-72d7-4082-9f01-1769da3154a8)

**Comment by brc-dd** [comment]
Please use the workaround mentioned in https://github.com/vuejs/docs/issues/2742#issuecomment-1991054719

The site is fine, but it's cloudflare/vercel causing issues in China.

**Comment by RSS1102** [comment]
> [请使用#2742（评论）](https://github.com/vuejs/docs/issues/2742#issuecomment-1991054719)中提到的解决方法[](https://github.com/vuejs/docs/issues/2742#issuecomment-1991054719)
> 
> 该网站很好，但在中国，cloudflare/vercel 造成了问题。

thanks.
I will https://github.com/vuejs/docs/issues/2742 continued to comment, but I believe that using VPN to access CN documents deviates from its original intention of being accessible locally.

**Comment by brc-dd** [comment]
Yeah. We can't fix anything at our level though other than switching away from Vercel.

**Comment by RSS1102** [comment]
Yes, I understand. I have found a solution and the problem has been fixed, but the network cache still causes it to display errors.

https://github.com/vuejs-translations/docs-zh-cn/issues/881#issuecomment-1993390838 suggests "尝试清除浏览器与 DNS 缓存" this is useful for me .
