### ISSUE TITLE
中文文档部分按钮选项无法点击

### ISSUE THREAD

**Issue by zxy1382** [vuejs/docs#2787]
<img width="1495" alt="image" src="https://github.com/vuejs/docs/assets/113956735/60411098-0a9f-410e-a140-8aed93342c34">
蓝色框内无法切换，控制台有报错

**Comment by tt-a1i** [comment]
please assign to me

**Comment by zxy1382** [comment]
> please assign to me

how to assign to you?

**Comment by brc-dd** [comment]
It's working fine for me. It's either a network issue at your side or vercel broke again in China. Try clearing your browser cache or using some VPN. You can also try the workarounds mentioned at https://github.com/vuejs/docs/issues/2742#issuecomment-1991054719
