### ISSUE TITLE
How to use v-model-with-arguments in jsx

### ISSUE THREAD

**Issue by SpringHgui** [vuejs/docs#2793]
https://cn.vuejs.org/guide/components/v-model.html#modifiers-for-v-model-with-arguments

```
// .vue file
<MyComponent v-model:title.capitalize="myText">
```

```
// .tsxfile   error
<MyComponent v-model:title.capitalize={myText.value}>
```

![image](https://github.com/vuejs/docs/assets/22363718/b1afa0ef-6d37-4dd3-ab5e-8ec92d83bddc)

**Comment by brc-dd** [comment]
https://github.com/vuejs/babel-plugin-jsx?tab=readme-ov-file#v-model
