### ISSUE TITLE
unpkg dont work 

### ISSUE THREAD

**Issue by tomas-vahala-unbiased-co-uk** [vuejs/docs#2794]
If you want, follow this guide https://vuejs.org/guide/quick-start.html#using-the-global-build

this script have issues on unpkg https://unpkg.com/vue@3/dist/vue.global.js

cdn don't work. Maybe have some backup elsewhere. Thanks

**Comment by Jinjiang** [comment]
It's working now from my side. Maybe just a short break from unpkg

**Comment by sodatea** [comment]
Maybe related to this incident on Cloudflare?

> Slow Response Times in Eastern Europe

https://www.cloudflarestatus.com/incidents/fjh89m55qxt7

I think it was fixed a few minutes ago.

**Comment by tomas-vahala-unbiased-co-uk** [comment]
@Jinjiang @sodatea Yes it was fixed like minute ago but whole morning don't so that's why i raise this issue :)
