### ISSUE TITLE
官网部分*.js 文件出现404错误

### ISSUE THREAD

**Issue by 34205037** [vuejs/docs#2796]
部分*.js 文件出现404错误，导致页面上的一些按钮都不起作用，我注意到了这里已经有其他两个类似的问题，但是现在都已经关闭，并且里面的解决方案没有解决我的问题，所以重新开了一个。
我已经确认没有使用VPN，并已经尝试了清除dns缓存/清除浏览器缓存并重启了浏览器，问题依然存在。
另外奇怪的是，在edge/chrome中存在该问题，从firefox访问官网是正常的。
![~WL6 WQXYS9GXNN_K)KX@A](https://github.com/vuejs/docs/assets/44354736/d453a4e8-b7bf-4fa8-a708-b410b8333f3d)
![Z@VZRCVK}_L %O)}9_OXKFE](https://github.com/vuejs/docs/assets/44354736/295b9b89-fcaf-40e6-b539-70ce7d257b7f)

**Comment by brc-dd** [comment]
Seems Vercel went down again in China. Try waiting for some time.

**Comment by bencodezen** [comment]
For issues related to the Chinese docs site, please create issues at the official repo https://github.com/vuejs-translations/docs-zh-cn. Thank you!
