### ISSUE TITLE
Official website documentation-ecosystem-ui component BUG

### ISSUE THREAD

**Issue by y377** [vuejs/docs#2815]
[https://ui-libs.vercel.app/](https://ui-libs.vercel.app/)

![image](https://github.com/vuejs/docs/assets/58632405/d01f2937-15ef-4817-8741-8fafe5d55666)

![image](https://github.com/vuejs/docs/assets/58632405/d241cb80-c9fe-4f93-bff6-f71245fae639)

For some unknown reason, the URL of the UI component library cannot be opened. If you visit the URL in the red box, it is a cult organization website.

**Comment by brc-dd** [comment]
Ah, I'm not sure but that link is valid - 

<img width="1800" alt="image" src="https://github.com/vuejs/docs/assets/40380293/7802460e-6ced-4ed1-a209-0d63346ff142">

Someone in China might be able to comment more on why is it resolving to other domain.

**Comment by bencodezen** [comment]
Since this isn't directly related to the Vue Docs site, I recommend opening an issue directly on https://github.com/ddahan/ui-libs. Thanks for being a member of the community @y377!
