### ISSUE TITLE
Docs: Code blocks writing standards

### ISSUE THREAD

**Issue by xiaodong2008** [vuejs/docs#2821]
Refers to the pages in docs, I think that the first letter of text(like `button`) in code blocks should be capitalised.

For example, there is a violation of writing standards in [`/guide/components/attrs`](https://github.com/vuejs/docs/blob/main/src/guide/components/attrs.md?plain=1#L29), it should be write like this:

```diff
- <button class="large">click me</button>
+ <button class="large">Click Me</button>
```

**Comment by bencodezen** [comment]
I think you're totally right @xiaodong2008! Appreciate the call out.

**Comment by xiaodong2008** [comment]
Sure! I will fix this soon 🥰
