### ISSUE TITLE
Add documentation for "VNode Lifecycle Events"

### ISSUE THREAD

**Issue by atilkan** [vuejs/docs#2851]
Hi,
"VNode Lifecycle Events" are documented in [migration docs](https://v3-migration.vuejs.org/breaking-changes/vnode-lifecycle-events#vnode-lifecycle-events) but there is no information about them in main docs. 

Can you add some information about them?

**Comment by atilkan** [comment]
Duplicate issue => https://github.com/vuejs/core/discussions/9298

**Comment by NataliaTepluhina** [comment]
As mentioned in the PR, we didn't document this feature in both Vue 2 and Vue 3 because it's not a recommended practice to listen to `@vue:` events on child components.

**Comment by ngocsangyem** [comment]
Hi @NataliaTepluhina, please tell us why this is not a recommended practice. This approach is beneficial in many situations. Are you guys planning to remove it in breaking changes?

**Comment by AloisSeckar** [comment]
I guess the reason is that it tightly couples child to parent and therefore reducing re-usability.

It is also obsfucating logical flow of the code - because why wouldn't you handle component's lifecycle hook inside the component itself?

**Comment by atilkan** [comment]
> I guess the reason is that it tightly couples child to parent and therefore reducing re-usability.
> 
> It is also obsfucating logical flow of the code - because why wouldn't you handle component's lifecycle hook inside the component itself?

If someone uses it internally, that answers the question of why. 
Why is it a thing anyway?
