### ISSUE TITLE
Header `\*` markers showing up in render

### ISSUE THREAD

**Issue by jgaehring** [vuejs/docs#2857]
I don't think these are meant to appear in the final rendering of the docs pages, but the `\*` and `\*\*` markers used to denote composition and option APIs are showing up in the subject headings in some places. I went on a wild goose chase looking for the footnotes but finally realized it was how the `headerMdPlugin` ["differentiate between Options-API-only and Composition-API-only sections"](https://github.com/vuejs-translations/guidelines?tab=readme-ov-file#retaining-original-anchors) and so probably a bug. :sweat_smile: It looks like whatever changes effect this were pushed to production somewhere between [Apr 15](http://web.archive.org/web/20240331124007/https://vuejs.org/guide/essentials/reactivity-fundamentals) and [Apr 24](http://web.archive.org/web/20240424124042/https://vuejs.org/guide/essentials/reactivity-fundamentals). I don't know if that means there might be other issues, like displaying the wrong content. I poked around in the commit history to see if there was something obvious. Maybe #2792, which touches `headerMdPlugin`, or a177175, which reverts it, but they were both merged on Apr 8 so that seems too early. 0beaed8, which  "bumps vitepress from 1.1.0 to 1.1.3" a la dependabot #2808, seems more likely, since it was merged Apr 19 and `headerMdPlugin` depends on Vitepress's [custom header anchors extension](https://vitepress.dev/guide/markdown#custom-anchors). But that's where I gave up.

Sorry if this is totally unhelpful and those asterisks are meant to be there!

**Comment by NataliaTepluhina** [comment]
@brc-dd I believe you have better context here than me, would you mind checking?

**Comment by brc-dd** [comment]
caused by https://github.com/vuejs/vitepress/commit/f86ac56b78da76f3061e6537b897bb13c1ed802d. I'll see if we can do something in vitepress 👀

**Comment by jgaehring** [comment]
Wow, that was fast! :runner:  :stopwatch:  :raised_hands:
