### ISSUE TITLE
VueDoc: The mobile device automatically obtains focus, resulting in page offset

### ISSUE THREAD

**Issue by Tofu-Xx** [vuejs/docs#2914]
### Vue version

3

### Link to minimal reproduction

https://private-user-images.githubusercontent.com/124511155/343743718-3aad9f59-0555-4711-a5e7-076c2a2fd168.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTY2MjksIm5iZiI6MTcxOTc5NjMyOSwicGF0aCI6Ii8xMjQ1MTExNTUvMzQzNzQzNzE4LTNhYWQ5ZjU5LTA1NTUtNDcxMS1hNWU3LTA3NmMyYTJmZDE2OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwMTEyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjBiNWI4ZWJjNGNkZDAyMDVlYzU1ZmI5YTdlNDQyMzY2OTRlYmMyNmRkZDQ5MGM3ODU2YzZhZjk5ZDdlY2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rtmkXejYD9q6KLvHmBkOV8gQ32bA1SIkgNp2jhZ3TMY

### Steps to reproduce

这只是一张图片
This is just a picture

https://cn.vuejs.org/guide/reusability/custom-directives.html

### What is expected?

页面不偏移
Page not offset

### What is actually happening?

移动设备自动获得焦点，导致页面偏移
The mobile device automatically obtains focus, resulting in page offset
 

### Any additional comments?

谢谢你
thank you

**Comment by bencodezen** [comment]
Thank you for opening an issue for this @Tofu-Xx! This is definitely an issue since it's causing all pages to offset incorrectly. 

The solution is most likely changing the example since it's meant to be a live example of how it works. We'll give this some thoughts and make sure to fix it.

**Comment by Tofu-Xx** [comment]
> Thank you for opening an issue for this @Tofu-Xx! This is definitely an issue since it's causing all pages to offset incorrectly.
> 
> The solution is most likely changing the example since it's meant to be a live example of how it works. We'll give this some thoughts and make sure to fix it.

**I love you**
