### ISSUE TITLE
官方文档对“使用 JavaScript 表达式”部分的内容表达有歧义

### ISSUE THREAD

**Issue by LengGao** [vuejs/docs#2920]
### Vue version

3.4.31

### Link to minimal reproduction

https://cn.vuejs.org/guide/essentials/template-syntax.html

### Steps to reproduce

官方文档：https://blog.csdn.net/cool99781/article/details/105821546
![vue文档截图jpg](https://github.com/vuejs/core/assets/49715463/62687311-c097-4e46-aa8b-0a28a65cfc41)

### What is expected?

建议修改一i下文档的表达，特别说明一下v-model指令，因为在v-model上不可使用任何可以被求值的表达式

### What is actually happening?

实际没有说明V-model指令的特殊性

### Any additional comments?

尊敬的尤大，如果觉得我提的建议有价值，请安排对应工作人员，修复我所提的问题，感谢！

**Comment by NataliaTepluhina** [comment]
Unfortunately, we cannot explain the specificity of `v-model` here without breaking the reader's flow process - `v-model` is explained much later in the docs and at this point it will cause more questions than answers.
