### ISSUE TITLE
could u please provide a sitemap?

### ISSUE THREAD

**Issue by nickyi1990** [vuejs/docs#2931]

**Comment by Yordan-Ramchev** [comment]
Based on my observations, all generated sitemap links point to 404 error page (SiteMap.vue):
1. https://vuejs.org/sitemap.html
2. https://cn.vuejs.org/sitemap.html
3. https://bn.vuejs.org/sitemap.html
4. https://cn.vuejs.org/sitemap.html
5. etc

Maybe updating vitepress configuration and adding sitemap there https://vitepress.dev/guide/sitemap-generation#sitemap-generation and then update `SiteMap.vue` component to point to generated XML files?

**Comment by Yordan-Ramchev** [comment]
@nickyi1990 hey, you can use https://vuejs.org/sitemap.xml
