### ISSUE TITLE
中文网站很多地方都有问题，不能使用了。Many parts of the Chinese website have problems and cannot be used anymore

### ISSUE THREAD

**Issue by chenlei0608** [vuejs/docs#2932]
以下功能不能使用了：
1. 搜索
2. 文档-->互动教程
3. 文档-->示例 

The following functions are no longer available:
1. Search
2. Docs -->Tutorial
3. Docs -->Example

**Comment by chenlei0608** [comment]
现在又可以使用了✌

**Comment by lointain** [comment]
composition-api.html:1  Refused to apply style from 'https://cn.vuejs.org/assets/style.96teQKz1.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by WangJincheng4869** [comment]
遇到同样的问题，不开代理官网没有样式
![图片](https://github.com/user-attachments/assets/3e907580-49e4-4b18-952f-b105104f7ea8)

**Comment by zealot-wei** [comment]
开了代理样式也是乱的

**Comment by Deceivee** [comment]
我遇到了只有简体中文的文档样式显示不出来，其他语言的文档内容样式能正常显示

**Comment by EnochGao** [comment]
好几天了，没人管？

**Comment by Deceivee** [comment]
先用繁体中文凑合着看吧

**Comment by joyholmes** [comment]
有什么临时处理方案吗，开了代理也没用

**Comment by zzs89117920** [comment]
![image](https://github.com/user-attachments/assets/9e201ead-713d-4059-9b37-dde1eea9e5bb)

**Comment by CccryQwQ** [comment]
> 有什么临时处理方案吗，开了代理也没用

我挂日子节点是可以的

**Comment by snowwindsand** [comment]
开代理也不行，mime那个过不去。其它js加载不了可以用浏览器打开链接把文件加载就行了。如果有json加载不了看一下是被广告插件拦了。就是mime没办法。
看英文或者繁体了。
![image](https://github.com/user-attachments/assets/4da8aad4-5673-44bf-968f-5ce6bf241c87)

**Comment by VolturiHao** [comment]
+1，一直是简体中文的加载不出样式，其他语言可以，开代理也没用，最近一直看繁体的
![image](https://github.com/user-attachments/assets/9ce9a1aa-59f5-46e7-8a9d-a07d89056b66)

**Comment by chenlei0608** [comment]
这是英文原版的文档仓库issues，请移步至简体中文版文档仓库issues：https://github.com/vuejs-translations/docs-zh-cn/issues

此外中文版文档仓库已有类似issues：https://github.com/vuejs-translations/docs-zh-cn/issues/984

**Comment by chenlei0608** [comment]
关注此issues的小伙伴请尽快移步至简体中文版文档仓库的issues讨论，两天后我将关闭此issues

**Comment by Jinjiang** [comment]
非常抱歉中文站近期访问问题请统一移步至这里，我们会保持关注和信息同步，谢谢
https://github.com/vuejs-translations/docs-zh-cn/issues/984
