### ISSUE TITLE
`inheritAttrs` should be supplemented with more See also

### ISSUE THREAD

**Issue by hotdogc1017** [vuejs/docs#2933]
In the content about [inheritAttrs](https://vuejs.org/api/options-misc.html#inheritattrs), it is only mentioned to use the `defineOptions` macro to control the attribute pass-through behavior, but `defineOptions` is only available in `3.3+` and cannot be used for lower versions, and there is no obvious indication of other methods. Later, I accidentally found in the content of [<script setup>](https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script) that this can be achieved by declaring an additional `<script>` tag, so have you considered linking this content to the See also section of [inheritAttrs](https://vuejs.org/api/options-misc.html#inheritattrs)?

**Comment by NataliaTepluhina** [comment]
Good point! This content actually was there pre-3.3+ (and we had most of the examples without the script setup), so it's worth adding it back.
