### ISSUE TITLE
Vue3 official website cannot be opened in Chinese ,vue3官网中文打不开 

### ISSUE THREAD

**Issue by Yingluoye5** [vuejs/docs#2941]
### Vue version

vue3

### Link to minimal reproduction

https://cn.vuejs.org/

### Steps to reproduce

Chrome 已是最新版本
版本 126.0.6478.183（正式版本） （64 位）无法打开vue3z中文版本，英文版本可以打开

### What is expected?

期望能正常打开中文版本Vue3
I hope to be able to open the Chinese version of Vue3 normally

### What is actually happening?

![Uploading 微信图片_20240719171255.png…]()
https://cn.vuejs.org/assets/chunks/framework.CNnSiKPY.jss 返回Status Code:404
https://cn.vuejs.org/assets/chunks/theme.CpnkbvfY.js返回Status Code:404

**Comment by Jinjiang** [comment]
非常抱歉中文站近期访问问题请统一移步至这里，我们会保持关注和信息同步，谢谢
https://github.com/vuejs-translations/docs-zh-cn/issues/984
