### ISSUE TITLE
中文的官网都挂了多久了，没人维护吗？

### ISSUE THREAD

**Issue by Hooper93** [vuejs/docs#2942]
![image](https://github.com/user-attachments/assets/a8bf5831-048d-43ee-989e-5d0ffcff4a48)

**Comment by Hooper93** [comment]
北京联通。

**Comment by Hooper93** [comment]
![image](https://github.com/user-attachments/assets/9c6feb36-5bd2-41a1-ba58-e4f23c3487e9)

**Comment by lingjieding** [comment]
![image](https://github.com/user-attachments/assets/5354a57e-1142-4311-9bb2-296b9b6c23b0)

**Comment by Jinjiang** [comment]
非常抱歉中文站近期访问问题请统一移步至这里，我们会保持关注和信息同步，谢谢
https://github.com/vuejs-translations/docs-zh-cn/issues/984
