### ISSUE TITLE
Missing search result for vModelText

### ISSUE THREAD

**Issue by xcsweb** [vuejs/docs#2949]
demo like this:
vModelText.beforeUpdate = function (el, {value, modifiers}) {
  console.log(modifiers)
  if (value && modifiers.c) {
    el.value = el.value[0].toUpperCase() + el.value.slice(1)
  }
}

**Comment by NataliaTepluhina** [comment]
I believe this is an expected behaviour: search doesn't index code snippets and this does look like a code snippet
