### ISSUE TITLE
Create Community section

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs#295]
Similar to v2, we want a section to help people get involved with the community.

**Comment by edimitchel** [comment]
Including https://vue-community.org/ ? @gustojs

**Comment by skirtles-code** [comment]
@bencodezen Was the objective here just to reach parity with v2? Is there anything specific that still needs to happen before this can be closed?

**Comment by bencodezen** [comment]
@skirtles-code nope! we can close this!
