### ISSUE TITLE
Found a dead link

### ISSUE THREAD

**Issue by actual-deuteragonist** [vuejs/docs#2966]
Here it is: 
https://vuejs.org/guide/essentials

**Comment by AloisSeckar** [comment]
Thank you for reporting. Can you please specify a place where you have encountered this link? I can't find any place in current docs. 

There is no falback "index" content provided for `/guide/essentials`, there should always be a link pointing to specific page under this folder.

**Comment by actual-deuteragonist** [comment]
> Thank you for reporting. Can you please specify a place where you have encountered this link? I can't find any place in current docs.
> 
> There is no fallback "index" content provided for `/guide/essentials`, there should always be a link pointing to specific page under this folder.

I'm sorry I don't think i understand your request. I think you mean whether a link in the docs points to this page if that's the case then I don't think so.
I accessed the page deliberately from the address bar hoping I can find a page that lists all the essentials in one place.

**Comment by AloisSeckar** [comment]
Ok, thanks for claryfying. In that case, as of the current state of the docs, there are no such pages in most of the folders. Usually only a given set of concrete pages are provided.

Currently available routes are listed in this file: https://vuejs.org/sitemap.xml

We may think about it. But senior members of Vue team should give their opinions before we start creating new pages.

**Comment by actual-deuteragonist** [comment]
> Ok, thanks for claryfying. In that case, as of the current state of the docs, there are no such pages in most of the folders. Usually only a given set of concrete pages are provided.
> 
> Currently available routes are listed in this file: https://vuejs.org/sitemap.xml
> 
> We may think about it. But senior members of Vue team should give their opinions before we start creating new pages.

That's okay !
I just wanted to report it and then you guys do what you do.

**Comment by NataliaTepluhina** [comment]
I don't think we would put work into trying to match a non-existing link to the existing one and redirecting - there is too much uncertainty in the guesswork. Since there is no reference on the dead link in the current docs, I am closing the issue.
