### ISSUE TITLE
There is an issue with the Vue Chinese official website's Mac option and combination switch buttons

### ISSUE THREAD

**Issue by jacksyk** [vuejs/docs#2969]
There is an issue with the Vue Chinese official website's Mac option and combination switch buttons

**Comment by jacksyk** [comment]
![image](https://github.com/user-attachments/assets/9cf3bb72-9964-48cb-87b4-8981406710ce)

**Comment by bencodezen** [comment]
Hi @jacksyk! The Chinese translation is managed by a different team in another repo, so I would recommend filing a new issue here https://github.com/vuejs-translations/docs-zh-cn. Thanks for filing an issue and being a part of the community!
