### ISSUE TITLE
What is problem whth chinese document ?

### ISSUE THREAD

**Issue by Ricky816845** [vuejs/docs#2970]
English version (vuejs.org) work is fine 

Chinese version (cn.vuejs.org) 
- Searching function is not work  
- API Preference switch is not work 
- It  happend a long time ago ,and still no body fix it.

What happend?
![QQ_1723516621063](https://github.com/user-attachments/assets/41c5c084-c003-4352-b787-277a11b2b0d2)

**Comment by Jinjiang** [comment]
https://github.com/vuejs-translations/docs-zh-cn/issues/984
For Chinese version, you are welcome to discuss it here or open another particular issue on that repo.
Thanks.
