### ISSUE TITLE
essential application link is missing

### ISSUE THREAD

**Issue by ImanAski** [vuejs/docs#2981]
![image](https://github.com/user-attachments/assets/24fde684-c8ea-41b4-aa7e-679b9997bbaf)

**Comment by AloisSeckar** [comment]
Looks like some temp issue, the reported page works for me now:
![image](https://github.com/user-attachments/assets/0f8b900c-955e-4e26-b4b0-710d85f3dd8f)

Can you please share more info, how did you encountered the problem? From which page you came upon the dead link mentioned above?

**Comment by bencodezen** [comment]
Agreed. I can't seem to replicate this issue.

If you could provide more info, it would be greatly appreciated. Thank you!
