### ISSUE TITLE
https://cn.vuejs.org/ 国内访问需要使用vpn  不使用vpn的时候访问不到

### ISSUE THREAD

**Issue by yuanzengding-1234** [vuejs/docs#3008]
![image](https://github.com/user-attachments/assets/e6e50e71-72c7-4005-ad62-d983a4c20e21)

**Comment by bencodezen** [comment]
Please open an issue in the official Chinese docs repo: https://github.com/vuejs-translations/docs-zh-cn.

Thank you!
