### ISSUE TITLE
bug: Syntax highlighting seems to be broken

### ISSUE THREAD

**Issue by icarusgk** [vuejs/docs#3022]
![Screenshot 2024-09-16 at 7 46 38 AM](https://github.com/user-attachments/assets/f5712911-1e9e-47a2-a4b3-481f17c39412)

**Comment by mahmudunnabikajal** [comment]
@icarusgk 
Maybe this is a network issue. Works fine on our device. Clear browser cookies and try again.

**Comment by icarusgk** [comment]
Thank you, the problem persists when clearing the browser's cookies 🤔

**Comment by mahmudunnabikajal** [comment]
@icarusgk can you please share the link?

**Comment by icarusgk** [comment]
@mahmudunnabikajal This is the one from the image: https://vuejs.org/tutorial/#step-5
