### ISSUE TITLE
Discord Link in Docs is Expired

### ISSUE THREAD

**Issue by seeniOlabode** [vuejs/docs#3057]
<img width="1680" alt="Screen Shot 2024-10-10 at 4 29 51 PM" src="https://github.com/user-attachments/assets/140ecc92-51ab-41b3-a311-b9492544eec5">

**Comment by Bayn-Web** [comment]
Dose the link like https://discord.com/invite/HBherRA? I can open it.

**Comment by seeniOlabode** [comment]
No, it's an invalid invite.

**Comment by mahmudunnabikajal** [comment]
@seeniOlabode 
Can you mention the page link where you found this issue?

**Comment by seeniOlabode** [comment]
It's on the homepage, here:

![CleanShot 2024-10-17 at 10 04 53@2x](https://github.com/user-attachments/assets/3e9c2e6c-88d8-406a-9fbf-e479dd84d127)

**Comment by mahmudunnabikajal** [comment]
@seeniOlabode  Looks good on my device.

Try this steps:
- Remove browser cookies and visit the homepage
- Or, manually visit [https://discord.com/invite/vue](https://discord.com/invite/vue) to join
- Or, Try incognito tab

![Screenshot from 2024-10-17 15-36-47](https://github.com/user-attachments/assets/d84b6fb2-b8ba-4478-82f5-712e7e484c11)

**Comment by seeniOlabode** [comment]
This worked, thanks!!!
