### ISSUE TITLE
Dead link: /guide/built-ins/teleport.html

### ISSUE THREAD

**Issue by Ser5** [vuejs/docs#3080]
Source page:   
https://v3-migration.vuejs.org/

The link:   
https://vuejs.org/guide/built-ins/teleport.html

Quote:
> Page Not Found
> 
> You found a dead link: /guide/built-ins/teleport.html
> Please [let us know](https://github.com/vuejs/docs) so we can fix it.

**Comment by mahmudunnabikajal** [comment]
@Ser5  Looks good on my device.

Try these steps:

- Remove browser cookies Or Try the incognito tab
- Then visit https://v3-migration.vuejs.org/ and check the 'Teleport' link

[screen-capture1.webm](https://github.com/user-attachments/assets/dd52d36d-20fd-4990-bc33-99033b42b82e)

**Comment by Ser5** [comment]
@mahmudunnabikajal , I tested the link. Indeed, it works fine now.

Earlier only the first link worked for me, but now both are OK:

1. https://vuejs.org/guide/built-ins/teleport.html
2. https://vuejs.org/guide/built-ins/teleport
