### ISSUE TITLE
Monospace fonts on Vue Docs not working on Ubuntu

### ISSUE THREAD

**Issue by otabekoff** [vuejs/docs#3105]
It is worth 100x than long text.
![image](https://github.com/user-attachments/assets/800464f4-cff8-4f16-8870-f3b81eb293f3)

See this. I inspected and find that you were using a monospace font called Menlo. But even if I install it and renew font cache on my Ubunt 24.04 latest, it is not working. It is so thing and UGLY.

I hope that you will fix this issue soon.

EDIT:
I've also checked on codepen:
![image](https://github.com/user-attachments/assets/f20524ad-1912-4e0e-b61f-609ad78f5297)

And on highlight.js:
![image](https://github.com/user-attachments/assets/6b1258f0-6dee-450d-90b0-a3ddbb283224)

and on Shiki.js website:
![image](https://github.com/user-attachments/assets/d5e20fa9-93de-43a9-84ec-8c831b9eb7f6)

On all of these websites it is working. But not on vuejs.org

**Comment by haoqunjiang** [comment]
What's your browser? Do you have any enhanced privacy features turned on, or are you browsing in a private window?
Because it looks very much like an anti-font-fingerprinting issue to me.
https://undetectable.io/blog/fonts-browser-fingerprints/

**Comment by otabekoff** [comment]
I am using Firefox latest version on Ubuntu 24.04 latest. But I also checked this on Chrome and Brave browsers. The issue is still persisting on them too.

**Comment by otabekoff** [comment]
I am closing this issue as it has been resolved.
