### ISSUE TITLE
Breaking link

### ISSUE THREAD

**Issue by tisma95** [vuejs/docs#3110]
In file src/guide/extras/web-components.md {#web-components-and-typescript} we have the breaking link [`GlobalComponents` interface](https://github.com/vuejs/language-tools/blob/master/packages/vscode-vue/README.md#usage) the page is not found.

https://github.com/vuejs/language-tools/blob/master/packages/vscode-vue/README.md#usage

**Comment by AloisSeckar** [comment]
Good catch. The referenced section got commented out a while ago: 
https://github.com/vuejs/language-tools/commit/1a636ed3e56878715e560fd6972cf59fc73c5dcd

Now the question is how to replace it? Or is this piece of information outdated completely, as the Vue Official VS code extension keep evolving?

**Comment by tisma95** [comment]
Hello @AloisSeckar,

Thanks for your support.

I think maybe it is this link https://github.com/vuejs/language-tools/wiki/Global-Component-Types

because in previous link we don't have the global interface definition.

Let me know your point.

Thanks

**Comment by AloisSeckar** [comment]
Yea, this looks like it. Thanks for finding out.

Do you think you can prepare a PR to fix the link? Or should I (later today)?

**Comment by tisma95** [comment]
Hi @AloisSeckar,

I fixed it check https://github.com/vuejs/docs/pull/3111
