### ISSUE TITLE
where is the NOT outdated style guide

### ISSUE THREAD

**Issue by devinschumacher** [vuejs/docs#3130]
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/dba27fb1-2ab1-433b-a00b-5825626ae87f" />

**Comment by AloisSeckar** [comment]
There is none at the moment. The team is aware of the necessity to do some major Vue 3 Composition API update, but I don't know about any particular road map for this. Once it comes out, we will be told.

There were already similar questions asked, namely the oldest #2030

**Comment by devinschumacher** [comment]
> There is none at the moment. The team is aware of the necessity to do some major Vue 3 Composition API update, but I don't know about any particular road map for this. Once it comes out, we will be told.
> 
> There were already similar questions asked, namely the oldest #2030

okay thanks for the reply!
