### ISSUE TITLE
Add Suspense docs

### ISSUE THREAD

**Issue by fxxjdedd** [vuejs/docs#328]
I think it needs a separate section to doc Suspense

**Comment by NataliaTepluhina** [comment]
@fxxjdedd Suspense is still experimental feature so we won't take this as a first priority but let's keep issue open to track what we're missing 👍🏻

**Comment by fadamakis** [comment]
There are some references on suspense that should either be completed or removed
https://v3.vuejs.org/guide/component-dynamic-async.html#using-with-suspense

**Comment by softboy99** [comment]
+1

**Comment by softboy99** [comment]
Hi,
i just want to use aync setup. after google, it said,it should be used with suspense together. However, currently, there is little documentation about suspense. please update docs about how to  use suspense. i find the following:
https://github.com/vuejs/vue-next/pull/2099
but, it too little

**Comment by skirtles-code** [comment]
An introduction to the core features of Suspense can now be found here:

https://v3.vuejs.org/guide/migration/suspense.html

It is still considered experimental, so it won't be added to the main guide or API reference for now. Advanced use cases, such as SSR, will also need documenting.

**Comment by LinusBorg** [comment]
I'd suggest that we close this issue for now. Documentating this experimental feature in the mirgsation guide is enough until it has stabelized, in my opinion.

Thoughts?

**Comment by skirtles-code** [comment]
Closing. We can revisit this once Suspense is stable.
