### ISSUE TITLE
Add section regarding useHooks

### ISSUE THREAD

**Issue by splincool** [vuejs/docs#404]
I have not found the information regarding useHooks logic(how to create, describe, etc.) and it will be awesome if some examples are described how to use typescript inside hooks.

**Comment by bencodezen** [comment]
Thanks for filing an issue @splincool! When you refer to `useHooks` logic, are you referring to the Composition API?

**Comment by splincool** [comment]
Yes

**Comment by NataliaTepluhina** [comment]
I would say that this is rather `Examples` material than a guide. Would be happy to create an example though!

**Comment by splincool** [comment]
Thank you 😍

**Comment by skirtles-code** [comment]
The new guide at https://vuejs.org/guide/reusability/composables.html covers this topic.

I think we can use #1293 for further discussion.
