### ISSUE TITLE
Document scoped style changes

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs#460]
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md

**Comment by zhenzhenChange** [comment]
Yes! I also think that this part of the documentation is needed, and many people don’t know about it: scoped style changes

**Comment by skirtles-code** [comment]
@bencodezen The core features of scoped CSS are now documented in the API reference:

https://v3.vuejs.org/api/sfc-style.html

Do you think we need a separate entry in the migration guide, or can this be closed?

**Comment by bencodezen** [comment]
@skirtles-code At the time, I was thinking that this would be better to have in the core docs, but I think this is something we can hold off for now since there is an official page. Thanks for the assist!
