### ISSUE TITLE
Add Single File Component (SFC) examples to Vue 3 docs

### ISSUE THREAD

**Issue by iamsanteri** [vuejs/docs#555]
_Disclaimer: I'm not sure if this is the right place for suggestions, so please direct me to the right forum if I'm wrong here._ 

Is there any chance we could add to the "examples" section of Vue 3 docs some samples of Single File Components (SFCs)?

For example the following two basic examples: 
1. An SFC that is composed in-line with the new Composition API
2. An SFC that is composed with the old Options based API

I truly think this would be helpful for especially the beginner level Vue developers out there. Overall it's my impression that these docs don't cover Single File Components in enough of a detail while most developers actually work with those first and foremost (that is only my impression, no evidence here). Or are the docs for these SFCs somewhere else like in the Vue CLI docs? Maybe I'm missing something. 

I would love to get your opinion on this, what do you think?

**Comment by NataliaTepluhina** [comment]
@iamsanteri I share your concern regarding SFCs. Would it make sense to enhance https://v3.vuejs.org/guide/single-file-component.html#introduction and make it more detailed?

**Comment by iamsanteri** [comment]
Definitely @NataliaTepluhina, how should we go about it? Should I try and look for some good generic examples for both? I'm not sure if I'm myself the right person to add more detail for such an important introduction section especially as I'm not a very experienced Vue dev. What do you think?

**Comment by NataliaTepluhina** [comment]
@iamsanteri I will try to work on this next week :)

**Comment by sevillaarvin** [comment]
I was wondering if SFC was deprecated in vue 3 since I didn't see it in the [provide/inject guide](https://v3.vuejs.org/guide/component-provide-inject.html). So I googled `single file component vue3` and this was the third result. Anyway I'm glad it's not deprecated.

**Comment by NataliaTepluhina** [comment]
Closing as we have switched to new docs and this is not relevant anymore
