### ISSUE TITLE
Search breaks if menu has been opened

### ISSUE THREAD

**Issue by thedamon** [vuejs/docs#598]
This is on iOS 14, iPhone 8 Plus. 

If I click search either nothing happens, or an empty space appears above the page which is then disabled. I think this is only if I have opened the site menu previously to clicking search. Going "back" fixes it and brings the functioning search modal back

![image](https://user-images.githubusercontent.com/1375267/95082310-dcb59880-06e8-11eb-8e6a-705c3b480b2b.jpeg)

**Comment by gtsiolis** [comment]
Can't reproduce this. 😭

**Comment by thedamon** [comment]
I tried it again.. looks like the issue happens if I am scrolled down on the page.

**Comment by NataliaTepluhina** [comment]
Closing as it doesn't happen on the new website
