### ISSUE TITLE
Typescript, how to annotate a non-reactive instance property?

### ISSUE THREAD

**Issue by nilptr** [vuejs/docs#694]
In Vue 2, it is common to assign an instance of third part library to a property of `this` and perform some destroy actions in `destroyed` hook.

But I get a type error `Property 'xxx' does not exist on type 'ComponentPublicInstance<...>` when I do this with Vue 3 and Typescript.

How to annotate a non-reactive instance property?

```typescript
export default defineComponent({
  mounted() {
    // Error: Property 'tooltipInstance' does not exist on type 'ComponentPublicInstance<...>
    this.tooltipInstance = new Tooltip(this.$ref.reference);
  },
  beforeUnmount() {
    this.tooltipInstance?.destroy();
    this.tooltipInstance = null;
  },
});
```

**Comment by skirtles-code** [comment]
I don't use TypeScript myself but I've seen this question asked a lot. I haven't yet come across a proper answer.

Whatever the correct approach is, I think it would be worth documenting it in `typescript-support.md`.

**Comment by IlCallo** [comment]
https://github.com/vuejs/docs-next/issues/694
Is this the same problem? Cause there are examples on how to do this into the TSDocs of the related interfaces
