### ISSUE TITLE
Add `ComponentCustomProperties` and `ComponentCustomOptions` usage into TS documentation

### ISSUE THREAD

**Issue by IlCallo** [vuejs/docs#721]
Seems like the instruction on how to type `ComponentCustomProperties` and `ComponentCustomOptions` aren't covered by the TS integration page of Vue3 docs.
A section about global plugin usage is probably needed, as there where in [Vue2 docs](https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins)

I could find some examples into the TSDocs of the related interfaces.

https://github.com/vuejs/vue-next/blob/11a76ebd94932d04a54c8c60e60121ecf13c35a9/packages/runtime-core/src/componentPublicInstance.ts#L66

https://github.com/vuejs/vue-next/blob/11a76ebd94932d04a54c8c60e60121ecf13c35a9/packages/runtime-core/src/componentOptions.ts#L79

This may be the same as https://github.com/vuejs/docs-next/issues/694

**Comment by IlCallo** [comment]
```ts
 declare module '@vue/runtime-core' {
   interface ComponentCustomOptions {
     beforeRouteUpdate?(
       to: Route,
       from: Route,
       next: () => void
     ): void
   }
 }
 ```

AFAIK this way of declaring a new option (written as example into TSDocs) would actually overwrite `@vue/runtime-core` original declaration instead of augmenting it. So you probably need to add a `import 'vue'` at top to specify you're doing an augmentation. Even if it's not clear to me the trick which makes augmentations to `@vue/runtime-core` work by importing `vue` :thinking:

**Comment by IlCallo** [comment]
Related to `ComponentCustomOptions` augmentation, which is they way to specify the context (both of Options API and what has been returned by the setup method) to a method added as option?
Previously we're using this syntax on Quasar Framework

```ts
declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    meta?: object | ((this: V) => object)
  }
}
```

can we accomplish the same thing with Vue3 typings?

**Comment by NataliaTepluhina** [comment]
Added in new docs: https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties
