### ISSUE TITLE
cookbook idea: developing in Docker

### ISSUE THREAD

**Issue by eikooc** [vuejs/docs#727]
Hi. I'd like a cookbook guide to show how to develop and serve a vuejs application inside Docker.

**Comment by skirtles-code** [comment]
The Vue CLI documentation includes a section about deploying with Docker:

https://cli.vuejs.org/guide/deployment.html#docker-nginx

Our current feeling within the docs team is that there wouldn't be enough Vue-specific content to justify having a separate entry in the Vue 3 Cookbook.
