### ISSUE TITLE
[Suggestion] Don't show sidebar on tablet width, as in Vue 2.x documentation

### ISSUE THREAD

**Issue by corneliusroemer** [vuejs/docs#811]
I've started reading through Vue 3 documentation [loving it!] on my iPad (in vertical orientation).

I find it a nuisance that the sidebar is always expanded, taking up a lot of screen real estate cutting off codelines. It also means that I cant scroll conveniently from the left hand side of the screen, which is inconvenient when lying on my right shoulder and holding the tablet with my left hand.

In Vue 2 docs, the sidebar only shows above 900px screen-width, in Vue 3 docs, the change is at 720px. The iPad is around 780px.

If this was a conscious decision, ignore me, but I just wanted to draw attention to this in case this change happened coincidentally.

Below comparison at 768px (standard tablet width according to Chrome dev tools).

### Vue 3 (with sidebar expanded, which I don't like)
![image](https://user-images.githubusercontent.com/25161793/104640515-e025cc00-56a8-11eb-81d2-225a4581a689.png)

### Vue 2 (with sidebar retracted, which I would prefer)
![image](https://user-images.githubusercontent.com/25161793/104640509-de5c0880-56a8-11eb-8cb7-1fd4e8473511.png)

**Comment by NataliaTepluhina** [comment]
Added the issue to VuePress repository.
