### ISSUE TITLE
Debug Vue SFC files with TypeScript in VS Code

### ISSUE THREAD

**Issue by shuxiaoman** [vuejs/docs#813]
In SFC files,i can debug well in js,but when i use `<style lang="less">`,it show Unbound breakpoint.
plugin:**Debugger for Chrome**

However,it works in plugin **Debugger for Firefox**

My launch.json is the same as [documents](https://v3.vuejs.org/cookbook/debugging-in-vscode.html#prerequisites)

**Comment by seanwuapps** [comment]
it shows unbound breakpoint for me in js as well 
![image](https://user-images.githubusercontent.com/10577684/118418050-28f29d80-b6fa-11eb-9652-7efd2f40c679.png)

**Comment by seanwuapps** [comment]
realised the issue was to do with typescript... probably a different issue then.
