### ISSUE TITLE
Code block component's language info text overlaps "New content is available" modal in top right corner

### ISSUE THREAD

**Issue by rico-et22** [vuejs/docs#865]
As in this picture:
![image](https://user-images.githubusercontent.com/28688352/108611441-d0538300-73de-11eb-95da-486cdbe68792.png)

This is not an issue with core VuePress, as on their docs everything is normal
![image](https://user-images.githubusercontent.com/28688352/108611416-b154f100-73de-11eb-953b-19c0526c7963.png)

**Comment by NataliaTepluhina** [comment]
Closing an issue as we have switched to new docs.
