### ISSUE TITLE
Before & After example of the code

### ISSUE THREAD

**Issue by sakirma** [vuejs/docs#947]
Hello this is a request for the composition introduction.
An example about a component file is given in the introduction. It explains how complicated the component can get when its responsibility gets bigger. 
This is the [picture](https://v3.vuejs.org/images/options-api.png)

I thought that it would be informative and inspire other people to use Vue 3, if you also could show a similar picture of the same component but then in Vue 3.

**Comment by NataliaTepluhina** [comment]
Closing an issue as we have switched to new docs.
