### ISSUE TITLE
SSR guide: add examples for 3rd party libraries not supporting SSR

### ISSUE THREAD

**Issue by NataliaTepluhina** [vuejs/docs#968]
A comment by @CyberAP:

---
I would really like to see some common examples of 3rd party library integrations that do not support SSR environment. It's probably the most common issue when you're switching from CSR to SSR.

The approaches I would suggest are:

1. Using dynamic imports plus mounted flags (set a flag to true when mounted, which triggers dynamic import for components hidden with this flag)
2. Using environment constants: IS_SERVER, IS_CLIENT, and how to define them.

**Comment by CyberAP** [comment]
An example for a library that has to be executed only on the server:

```html
<script>
export default {
  created() {
    if (typeof window === 'undefined') {
      import('server-only-library').then(({ default }) => {
        // assume the server-only-library exports function as a default export
        default();
      });
    }
  }
}
</script>
```

We can replace dynamic `import` here with `require`, but I like the import version a bit more since it aligns with the ECMAscript spec.

----

An example of 3rd party library integration that doesn't support SSR:

```html
<template>
  <MyComponent v-if="visible" />
</template>

<script>
export default {
  components: {
    MyComponent: () => import('my-component'),
  },
  data() {
    return { visible: false };
  },
  mounted() {
    this.visible = true;
  }
}
</script>
```
