### ISSUE TITLE
SSR guide: refactor to a webpack build w/o Vue CLI

### ISSUE THREAD

**Issue by NataliaTepluhina** [vuejs/docs#969]
A suggestion by @CyberAP

---

Maybe it's worth exploring into the vue-cli agnostic SSR idea? Because right now if you're not using vue-cli your first migration step would be to migrate your current build config to vue-cli and only then apply all the SSR practices in the guide.

---
Also, within this refactoring it would be nice to split webpack config onto base one, server and client builds like it was done in Vue 2 SSR guilde

**Comment by CyberAP** [comment]
Base config examples:

### Client
```js
const path = require('path');
const VueLoaderPlugin = require('vue-loader/lib/plugin');

module.exports = {
  entry: './src/entry-client.js',
  output: {
    path: path.resolve(__dirname, './dist/client'),
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        // required if you want to use Vue files inside node_modules:
        // https://vue-loader.vuejs.org/migrating.html#importing-sfcs-from-dependencies
        exclude: file => /node_modules/.test(file) && !/\.vue\.js/.test(file),
      },
      {
        test: /\.css$/,
        use: [
          'vue-style-loader',
          'css-loader'
        ]
      }
    ],
  },
  plugins: [
    new VueLoaderPlugin(),
  ],
}
```

### Server
```js
const path = require('path');
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const { WebpackManifestPlugin } = require('webpack-manifest-plugin');
const nodeExternals = require('webpack-node-externals');
const webpack = require('webpack');

module.exports = {
  entry: './src/entry-server.js',
  target: 'node',
  output: {
    libraryTarget: 'commonjs2',
    path: path.resolve(__dirname, './dist/server'),
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        // required if you want to use Vue files inside node_modules:
        // https://vue-loader.vuejs.org/migrating.html#importing-sfcs-from-dependencies
        exclude: file => /node_modules/.test(file) && !/\.vue\.js/.test(file),
      },
      {
        test: /\.css$/,
        use: 'null-loader',
      }
    ],
  },
  plugins: [
    new VueLoaderPlugin(),
    new WebpackManifestPlugin({ fileName: 'ssr-manifest.json' }),
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1
    }),
  ],
  optimization: {
    splitChunks: false,
    minimize: false,
  },
  externals: nodeExternals({ allowlist: /\.(css|vue)$/ }),
}
```

I am not 100% sure about the `null-loader` practice that I added here for performance reasons, maybe there's a better one but right now it seems to be a reasonable choice to get fast builds for node environment (maybe `css-loader` can do this out of the box, can't verify).

**Comment by HomyeeKing** [comment]
build:serer error w/  the given vue-cli config ，
here is the debug log:

![image](https://user-images.githubusercontent.com/49113249/118369575-74139000-b5d6-11eb-8557-6c9909aa2f95.png)

but my global npm version is :
![image](https://user-images.githubusercontent.com/49113249/118369625-9c9b8a00-b5d6-11eb-83a2-5af8dbc16ab3.png)

**Comment by skirtles-code** [comment]
@HomyeeKing I can't really tell what problem you're having from those pictures. It doesn't seem to be related to this GitHub issue, which is about documenting a non-CLI webpack config for SSR.

I suggest asking for help on the [Vue Discord](https://chat.vuejs.org/) if you need help debugging the problem.

If it turns out to be an error in the documentation then please open a new issue.

**Comment by HomyeeKing** [comment]
just a auto-fixed bug, it works today w/  no extra config
you can fold my comment
