### ISSUE TITLE
SSR guide: add missing parts

### ISSUE THREAD

**Issue by NataliaTepluhina** [vuejs/docs#971]
We have to extend the SSR guide with missing important parts

- [ ] CSS Management
- [ ] Head management
- [ ] Caching
- [ ] Streaming
- [ ] Data fetching and local store
- [ ] Error handling

**Comment by CyberAP** [comment]
I'd also add error handling here as well because it depends on the execution environment (we might want to show a toast on a client or render an error on the server).

**Comment by NataliaTepluhina** [comment]
@CyberAP added!

**Comment by runxc1** [comment]
So going through the documentation I am running into a lot of little items that are taking an hour here or two hours there even though I had set this up using VueJs 2 a while ago and am not new to the process.   I'm still looking for the way to get the CSS as @vue/server-renderer's renderToString does not include the CSS
