### ISSUE TITLE
Puzzled about Lifecyle Diagram

### ISSUE THREAD

**Issue by gavinliu6** [vuejs/docs#987]
As shown in the figure below, is there sth wrong? 

![QQ20210410-114741](https://user-images.githubusercontent.com/29831211/114257551-578ea180-99f3-11eb-9fbc-e4f8485aa96b.png)

😕  Shouldn't the `$el` property belong to the component instance, not the application instance?

**Comment by skirtles-code** [comment]
Thanks, I think you're right.

Perhaps the first step should say:

```
app = Vue.createApp(options)
vm = app.mount(el)
```

Then that later step could be changed to:

```
Create vm.$el and
append it to el
```

**Comment by NataliaTepluhina** [comment]
@skirtles-code I don't think it's a good idea to put the code in this flowchart 🤔 Also we are already past `created` step at this moment. Should we say `Append the result to 'el'` (assuming the result of the previous step)?

**Comment by skirtles-code** [comment]
@NataliaTepluhina I'm not sure I follow. Are you suggesting removing the current first step altogether?

**Comment by NataliaTepluhina** [comment]
@skirtles-code ye, because it seems to be 'spread' throughout a few previous steps in the flowchart.

**Comment by NataliaTepluhina** [comment]
Fixed in the new docs: https://vuejs.org/guide/essentials/lifecycle.html#lifecycle-diagram
