### ISSUE TITLE
Fix animation in Dropdown Transition

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs#99]
There is a method in `DropdownTransition.vue`: `setHeight(items)` that is inappropriately animating the heights.

Per @sdras:

> we shouldn't be animating height here. I know the alternative is more work but I can do it in a followup PR, this causes layout thrashing and repaints

**Comment by sdras** [comment]
I haven't dug in yet but self-assigned. @bencodezen in the docs meeting on Friday let's sync on it. :)

**Comment by NataliaTepluhina** [comment]
Closing an issue as we have switched to new docs and this is not relevant anymore
