### ISSUE TITLE
Collapsing sidebar on larger screen

### ISSUE THREAD

**Issue by Zenthae** [vuejs/docs#990]
At the moment, the sidebar of the doc can be toggled when the max width of the screen is under `(max-width: 719px)`, the issue is that on slightly bigger screen (iPad, iPad mini) the sidebar cannot be toggled which make the doc hard to read (nearly unreadable on iPad mini because everything is squeezed).

I'd like to know if it would be possible to increase the size at which the sidebar can be collapsed so that even on iPad i can collapse it.

**Comment by NataliaTepluhina** [comment]
Closing this as we have switched to new docs with a different design of the sidebar
